### ISSUE TITLE
Bug: DoubleValue, FloatValue not Converted to Simple Types

### ISSUE THREAD

**Issue by Faendrek** [stephenh/ts-proto#10]
DoubleValue, FloatValue are not being converted into `number | undefined` when `protoc` is run. 

**Reproduce**
Modify `simple.proto`'s SimpleWithWrapper message:

```
message SimpleWithWrappers {
  google.protobuf.StringValue name = 1;
  google.protobuf.Int32Value age = 2;
  google.protobuf.BoolValue enabled = 3;
  repeated google.protobuf.Int32Value coins = 6;
  repeated google.protobuf.StringValue snacks = 7;
  google.protobuf.FloatValue weight = 8;
  repeated google.protobuf.FloatValue weights = 9;
}
```

Compile proto: ` protoc --plugin=./node_modules/.bin/protoc-gen-ts_proto --ts_proto_out=. ./simple.proto`

The Float/DoubleValue's are preserved. 

```
export interface SimpleWithWrappers {
  name: string | undefined;
  age: number | undefined;
  enabled: boolean | undefined;
  coins: Array<number | undefined>;
  snacks: Array<string | undefined>;
  weight: FloatValue | undefined;
  weights: FloatValue[];
}
```

**Comment by Faendrek** [comment]
I would be happy to other the other types to the conversion logic if you point me to where you're doing it.

**Comment by stephenh** [comment]
@Faendrek great! It's here:

https://github.com/stephenh/ts-proto/blob/master/src/types.ts#L232

**Comment by Faendrek** [comment]
Implemented by https://github.com/stephenh/ts-proto/pull/11
