### ISSUE TITLE
google.type.Date generates an output that conflicts with builtin Date

### ISSUE THREAD

**Issue by mscolnick** [stephenh/ts-proto#100]
Not sure what an appropriate solution is but importing `google.type.Date` will conflict with the built-in `global.Date`.

Possible solution could be to special-case the naming of `google.type.Date` to `GoogleTypeDate`.

The generated code looks something like:

```ts
export interface Date {
  /**
   *  Year of date. Must be from 1 to 9999, or 0 if specifying a date without
   *  a year.
   */
  year: number;
  /**
   *  Month of year. Must be from 1 to 12, or 0 if specifying a year without a
   *  month and day.
   */
  month: number;
  /**
   *  Day of month. Must be from 1 to 31 and valid for the year and month, or 0
   *  if specifying a year by itself or a year and month where the day is not
   *  significant.
   */
  day: number;
}
```

**Comment by stephenh** [comment]
Well hm, I can see that causing problems I guess. 

Although if I do this in a local `date.ts` test file:

```typescript
export interface Date {
  foo: boolean;
}
```

And then in `foo.ts`:

```typescript
import { Date as MyDate } from "./date";

const d: MyDate = null!;
d.foo;

const e: Date = d;
```

It seems to work. I.e. do an alias on the import.

I wouldn't be surprised if there are more nuances though.

Does this approach work for you, or does ts-proto's generated code already have compile errors in it when using `google.type.Date`?

**Comment by mscolnick** [comment]
I would be fine to do the alias import, but the errors are in the generated code. It happens when `google.type.Date` and a `Timestamp` is in a protobuf file. The generate code wants to depend on both `Date`  from `google.type.Date` (i.e. `./date.ts`) and from built-in Date that comes from the timestamp.

**Comment by stephenh** [comment]
Okay, this should be fixed on master / included in the next release. I went with `DateMessage` as the name of the file. Maybe eventually we could have a config flag / something to let the user control what the "not `Date`" name is.

Fwiw I could also be convinced to use `CalendarDate` instead of `DateMessage`, although I suppose users could create their own type alias to call it whatever they want locally in their projects.

**Comment by mscolnick** [comment]
i think `DateMessage` is a good alternative. thank you for the fix!

**Comment by awan1** [comment]
Wanted to leave a note that I ran into this problem exactly as described in [this comment](https://github.com/stephenh/ts-proto/issues/100#issuecomment-660573134), and this fix was exactly what I needed. (I hadn't updated this package since v1.2x :) ) Thank you!
