### ISSUE TITLE
basic_string::_M_construct null not valid

### ISSUE THREAD

**Issue by HeCorr** [stephenh/ts-proto#1009]
Hello. I am unable to compile Proto files using this plugin. Other plugins (like the official Go plugin) work fine.

Full error:
```
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
```
OS: Windows 10, running Git Bash
TS-Proto version: `1.167.8`
Protoc version: `libprotoc 25.3`
Proto file:
```
syntax = "proto3";
package test;

message Msg {
    string name = 1;
}
```

Command: `protoc --plugin=./front-end/node_modules/.bin/protoc-gen-ts_proto --ts_proto_out=. ./proto/basic.proto`

Please help.

**Comment by stephenh** [comment]
`what():  basic_string::_M_construct null not valid`

Huh! I've not seen that error before, but it's coming from the protoc lib and not ts-proto itself.

If you can find the root cause, curious to hear it, but sorry otherwise I can't be much help.

**Comment by Juliiiian** [comment]
I know this is probably not the best place since you said it would be protoc, but I tried 25.4, 25.2 and 24.4 and all return the same error. Just wanted to know how you fixed it.

**Comment by Juliiiian** [comment]
I don't really know what I changed, but it works now, and I will not touch it again:

```
grpc_tools_node_protoc^
    --js_out=import_style=es6,binary:%PROTO_DIR%^
    --ts_out=import_style=es6,binary:%PROTO_DIR%^
    --ts_opt=target=node^
    --ts_opt=esModuleInterop=true^
    --grpc_out=%PROTO_DIR%^
    -I ./^
    ./*.proto
```

**Comment by stephenh** [comment]
I don't think you have the right open-source project; `grpc_tools_node_protoc` is probably this project:

https://github.com/agreatfool/grpc_tools_node_protoc_ts#readme

**Comment by Juliiiian** [comment]
Yeah, you are right, but I tried it before with yours and the normal protoc command, and then I got the error. Just wanted to paste a solution that helped me.
