### ISSUE TITLE
removeEnumPrefix not working

### ISSUE THREAD

**Issue by lucaschan1020** [stephenh/ts-proto#1011]
version: 1.167.9

this is the command that I have executed.
`protoc --plugin=./node_modules/.bin/protoc-gen-ts_proto --ts_proto_opt=nestJs=true --ts_proto_opt=useDate=true --ts_proto_opt=stringEnums=true --ts_proto_opt=removeEnumPrefix=true --ts_proto_out=. libs/common/src/apps/organization.proto`

in the proto file it is defined like this.
```proto
enum OrganizationTypeEnum {
  ORGANIZATION_TYPE_ENUM_GOVERNMENT_EP = 0;
  ORGANIZATION_TYPE_ENUM_GOVERNMENT_NON_EP = 1;
  ORGANIZATION_TYPE_ENUM_GOVERNMENT_LINKED_COMPANY = 2;
  ORGANIZATION_TYPE_ENUM_MULTI_NATIONAL_COMPANY = 3;
  ORGANIZATION_TYPE_ENUM_PRIVATE_COMPANY = 4;
  ORGANIZATION_TYPE_ENUM_OTHERS = 5;
}
```

the output ts file is this. (actual)
```typescript
export enum OrganizationTypeEnum {
  GOVERNMENT_EP = "ORGANIZATION_TYPE_ENUM_GOVERNMENT_EP",
  GOVERNMENT_NON_EP = "ORGANIZATION_TYPE_ENUM_GOVERNMENT_NON_EP",
  GOVERNMENT_LINKED_COMPANY = "ORGANIZATION_TYPE_ENUM_GOVERNMENT_LINKED_COMPANY",
  MULTI_NATIONAL_COMPANY = "ORGANIZATION_TYPE_ENUM_MULTI_NATIONAL_COMPANY",
  PRIVATE_COMPANY = "ORGANIZATION_TYPE_ENUM_PRIVATE_COMPANY",
  OTHERS = "ORGANIZATION_TYPE_ENUM_OTHERS",
  UNRECOGNIZED = "UNRECOGNIZED",
}
```

I expect the output ts file will be like this. (expect)
```typescript
export enum OrganizationTypeEnum {
  GOVERNMENT_EP = "GOVERNMENT_EP",
  GOVERNMENT_NON_EP = "GOVERNMENT_NON_EP",
  GOVERNMENT_LINKED_COMPANY = "GOVERNMENT_LINKED_COMPANY",
  MULTI_NATIONAL_COMPANY = "MULTI_NATIONAL_COMPANY",
  PRIVATE_COMPANY = "PRIVATE_COMPANY",
  OTHERS = "OTHERS",
  UNRECOGNIZED = "UNRECOGNIZED",
}
```

is this not possible? to auto deserialize/serialize into string value without prefix, over the wire is still transferring with string value with prefix
I have also tried `--ts_proto_opt=removeEnumPrefix=all`
still give the same result

**Comment by stephenh** [comment]
Hi @lucaschan1020 , no, that's just how the current `removeEnumPrefix` works; we have the TS keys being prefix-less, and the values prefix-full, because the values are what go over the wire.

If you really wanted to have the values be prefix-less, and then quickly put them back before putting them on the wire, you could do that; I'm a little worried it'd be overly complicated, but it'd be doable if you're sufficiently motivated.

Thanks!
