### ISSUE TITLE
Questions about defaults, optionals, arrays, null/undefined

### ISSUE THREAD

**Issue by biljecki** [stephenh/ts-proto#1016]
Hello, I'm rather a beginner with grpc - have been using the library for some time now but only now encountered a few issues after getting the actual requirements. I read through some issues and the documentation - and what I found either did not help or I didnt understand it.

First is arrays - apparently `repeated` fields are implicitly optional, and my fromJSON removes them entierly when they are empty. Because of this - I have to do `children ||= []` in multiple places in my client to manually set as empty array. This is rather annoying, is there a way to not remove empty arrays? Or is this unrelated to the library and rather proto stuff?

Second is the useOptionals which im confused by. 
<img width="1097" alt="image" src="https://github.com/stephenh/ts-proto/assets/33548026/80c11d77-3599-4128-8b3a-e210826773e9">

however for me, what happened is this:
<img width="699" alt="image" src="https://github.com/stephenh/ts-proto/assets/33548026/6b964eac-0ca4-4ef8-834d-7622fe44f501">

the description that was already optional did not change, while the title got both `?` and  `| undefined`. Not sure if the documentation is wrong, this is a bug or im just missing something. But also, whats even the point of having both ? and undefined?  I guess the only difference is essentially whether you can have it both implicitly undefined by omitting or explicitly set it to undefined?

And my third issue is default values. I have a cost property that is a number, and if I want to set it to `0`, the  `fromJSON` in the client still has the cost as 0, and then in my server controller it is no longer there. My problem with this is - well - how do i set it to 0? Do i now have to have logic to check if its undefined and then manually set it to 0? But what if i want to set it as null in the database? Do i now have to have another property like `isCostNull boolean` and again have to manually take care of it?

EDIT: actually just remembered I could use wrapper types instead of an extra field, so will give that a try. But still - i would manually have to take care of whether is null or 0.

**Comment by paralin** [comment]
Protobuf 3 cannot distinguish between unset fields and zero fields. The zero value is not sent on the wire.

**Comment by stephenh** [comment]
Hi @biljecki ; unfortunately @paralin is right and this is just a fact of life with protobuf, that optional handling is really suboptimal/all over the place.

Per the arrays, I glanced at a `fromJSON` in our `integration/simple` directory and it is setting the array to `[]`:

```ts
  fromJSON(object: any): Simple {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      age: isSet(object.age) ? globalThis.Number(object.age) : 0,
      createdAt: isSet(object.createdAt) ? fromJsonTimestamp(object.createdAt) : undefined,
      child: isSet(object.child) ? Child.fromJSON(object.child) : undefined,
      state: isSet(object.state) ? stateEnumFromJSON(object.state) : 0,
      grandChildren: globalThis.Array.isArray(object?.grandChildren)
        ? object.grandChildren.map((e: any) => Child.fromJSON(e))
        : [],
```

And the type of `grandChildren` is `[]`.

As you can tell, many others have disliked proto3's optional behavior, and we have ~more than a few options for attempting to make them not suck, but there are pros/cons to each.

Happy to see doc/bug fix PRs if you have very specific behavior that needs improved/fixes bug, but otherwise I'm going to close this out. Thanks!
