### ISSUE TITLE
TypeError on Runtime ChannelCredentials object

### ISSUE THREAD

**Issue by supachok768** [stephenh/ts-proto#1024]
Hi, I'm trying to run my client project to call the server, but I got a TypeError on Runtime. 
So I already tried ChannelCredentials.createInsecure() and credentials.createInsecure() both, but still got the same error.
![Screenshot 2024-03-31 at 21 51 15](https://github.com/stephenh/ts-proto/assets/35305328/5b2ecb00-a29d-4352-888f-0aae4ce7f493)

my proto file
```
syntax = "proto3";

service HelloService {
    rpc HelloUnary(HelloRequest) returns (HelloReply);
}

message HelloRequest{
    string sayHello = 1;
}

message HelloReply{
    string replyMessage = 1;
}
```

additional information about library version
```
protoc: 3.20.3
ts-proto: 1.169.1
@grpc/grpc-js: 1.10.3
```

build.sh
```
protoc --plugin=$(npm root)/.bin/protoc-gen-ts_proto \
 --ts_proto_out=$(pwd)/generate/ts \
 --ts_proto_opt=outputServices=grpc-js \
 --ts_proto_opt=esModuleInterop=true \
 -I=./protobufs ./protobufs/*.proto 
```

**Comment by stephenh** [comment]
Hi @supachok768 , sorry I don't really have time to debug ; we have a test like:

https://github.com/stephenh/ts-proto/blob/main/integration/grpc-js/grpc-js-test.ts

That looks similar to what you're doing, but otherwise I'm not sure. Let us know if you figure it out, thanks!
