### ISSUE TITLE
Release updated ts-proto-descriptors?

### ISSUE THREAD

**Issue by bhollis** [stephenh/ts-proto#1042]
Since [v1.169.0](https://github.com/stephenh/ts-proto/releases/tag/v1.169.0), `proto2` optional fields are better supported. Since Google's `descriptors.proto` is `proto2` syntax, this should fix several issues with encoding descriptors using `ts-proto-descriptors` - for example, since it won't write out optional fields, it's impossible to make an `EnumValueDescriptorProto` that describes the zero-value option.

I *think* what's required is to bump the version of `ts-proto-descriptors`, build it with the latest `ts-proto`, and publish.

**Comment by stephenh** [comment]
Hi @bhollis ; well I put up #1043 , lets see if you're right :crossed_fingers: :-)

**Comment by bhollis** [comment]
Thanks for doing that! Unfortunately I was wrong - it wasn't as simple as just releasing the newest version. Even when removing `disableProto2Optionals`, fields still aren't set when they are at their default value. Here's the change when removing `disableProto2Optionals`:

```diff
    toJSON(message: EnumValueDescriptorProto): unknown {
     const obj: any = {};
-    if (message.name !== "") {
+    if (message.name !== undefined && message.name !== "") {
       obj.name = message.name;
     }
-    if (message.number !== 0) {
+    if (message.number !== undefined && message.number !== 0) {
       obj.number = Math.round(message.number);
     }
     if (message.options !== undefined) {
```

You can see that the optional fields aren't set when the value is not undefined, when I think they should be.

I can switch over to `protobuf-es` for this task, so this isn't urgent, but I really prefer `ts-proto`'s approach to generated code in general. This is my first time having to deal with proto2 semantics. 

Thanks for the project! If I get some free time I might try to file a PR to fix this, though I have some other things I'd probably want to try first.
