### ISSUE TITLE
Proto import statements not being recognized

### ISSUE THREAD

**Issue by mprisehk** [stephenh/ts-proto#1044]
### Dependencies
- ts-proto@1.176.0
- typescript@5.3.3
- protoc v26.1

### Problem
I am trying to generate TS definitions for my proto files for NestJS. As I am on Windows it took some time to find a protoc command that would work, but this one ended up working for my simplest file (general.proto):

```
protoc --ts_proto_out="./ts" --plugin=protoc-gen-ts_proto="C:/path/to/repo/node_modules/.bin/protoc-gen-ts_proto.cmd" --ts_proto_opt=nestJs=true --proto_path="." general.proto
```

Then I tried one of my other files. It was missing the `HealthInput` and `HealthResponse` types, which makes sense, as these are defined in `general.proto`.
```
> protoc --ts_proto_out="./ts" --plugin=protoc-gen-ts_proto="C:/path/to/repo/node_modules/.bin/protoc-gen-ts_proto.cmd" --ts_proto_opt=nestJs=true --proto_path="." ms-users.proto
ms-users.proto:9:21: "HealthInput" is not defined.
ms-users.proto:9:43: "HealthResponse" is not defined.
```

To counteract this I started using `*.proto`. **However the output of the command remained the same.** I tried with different scenarios, though to make a long story short, in the end I cannot get my proto imports to work with ts-proto.

Stripping it down to a minimal example of only two files, the output of the protoc call remains the same.

**Command:**
```
> protoc --ts_proto_out="./ts" --plugin=protoc-gen-ts_proto="C:/path/to/repo/node_modules/.bin/protoc-gen-ts_proto.cmd" --ts_proto_opt=nestJs=true --proto_path="." *.proto
ms-users.proto:9:21: "HealthInput" is not defined.
ms-users.proto:9:43: "HealthResponse" is not defined.
```

**general.proto:**
```
syntax = "proto3";

package general;

message HealthInput {
}

message HealthResponse {
    string health = 1;
}
```

**ms-users.proto:**
```
syntax = "proto3";

import "general.proto";

package ms_users;

service UsersService {
    rpc GetUsers(GetUsersInput) returns (Users);
    rpc HealthCheck(HealthInput) returns (HealthResponse);
}

//Omitted message definitions for GetUsersInput and Users for brevity
```

Additional info
- All proto files live in the same directory. The command is also executed in this directory.
- The proto files themselves (including imports) should be valid as we are using them in practice.

**Comment by stephenh** [comment]
Hi @mprisehk ; unfortunately these error messages:

```
ms-users.proto:9:21: "HealthInput" is not defined.
ms-users.proto:9:43: "HealthResponse" is not defined.
```

Are coming from `protoc`. I understand `protoc` is a bug-bear to get working, especially on windows, but I'm not sure there is much I can do to help. Sorry!

We do have examples of file imports in our `integration/` tests directory, but they all assume linux/mac.
