### ISSUE TITLE
Support for messages with the same name as an rpc method

### ISSUE THREAD

**Issue by mprisehk** [stephenh/ts-proto#1045]
### Description

Currently ts-proto does not support having messages with the same name as an rpc operation. The following file is a simplified example:
```
syntax = "proto3";

package ms_orders;

service OrderService {
    rpc ActiveOrders(ActiveOrdersInput) returns (ActiveOrders);
}


message ActiveOrders {
    repeated string orders = 1;
}

message ActiveOrdersInput {
    string search = 1;
}
```
### Command used
(on Windows):
```
> protoc --ts_proto_out="./ts" --plugin=protoc-gen-ts_proto="C:/path/to/repo/node_modules/.bin/protoc-gen-ts_proto.cmd" --ts_proto_opt=nestJs=true --proto_path="." ms-orders.proto
```
### Expected outcome
Output is generated.

### Actual outcome
```
ms-orders.proto:6:50: "ActiveOrders" is not a message type.
```

I do not know whether there is a specific technical reason for disallowing this. In any case, we (apparently) use this construct in a few places, and since grpc can handle it (we use these files in practice and they work), it'd make sense for ts-proto to be able to handle it too.

**Comment by stephenh** [comment]
Hi @mprisehk ; it makes sense this should work. I'm not sure how hard it would be to do so--could be easy, could not. If you could submit a PR that fixes this, that'd be great! Thanks!

**Comment by stephenh** [comment]
Actually after looking at your other issue, I realized the ^ error looks like a `protoc` error message. And grepping the ts-proto codebase, we don't have any validation errors that look like "is not a message type".

You mentioned that grpc handles this somehow, so it would be interesting to see how they're invoking protoc; or maybe they're doing their own codegen that doesn't actually go through `protoc`?

Either way, I don't think this is a ts-proto issue atm.

If you figure it out, or confirm it is actually a ts-proto issue, I'm happy to re-open. Thanks!
