### ISSUE TITLE
Incorrect message names in the generated code for repeated fields

### ISSUE THREAD

**Issue by avlyalin** [stephenh/ts-proto#1072]
Hi! Thanks for the lib 🙂 

## Problem
In the proto files for which I generate TS code, there are messages with the same names but in different packages. For example, within one message, there can be a field of a type with the same name, but from a different package.
It's easier to demonstrate with an example:

```proto
// model.proto
syntax = "proto3";

package model;

message User {
    string id = 1;
}
```

```proto
// api.proto
syntax = "proto3";

package api;

import "model.proto";

message User {
    repeated model.User users = 1;
    model.User user = 2;
}
```

In the code generated for **api.proto**, the import of `User` includes an alias to avoid collisions:
```js
import { User as User1 } from "./model.js";
```

However, in the constructor methods `toJson` and `fromJson` of `User` (in `api.ts`) incorrect message name is generated. Instead of the alias `User1`, there is `User` (`User.fromJson`/`User.toJson`) in map-functions:

```ts
// api.ts

export const User = {
...

  fromJSON(object: any): User {
    return {
      // expected: ... => User1.fromJSON(e)) : [],
      users: globalThis.Array.isArray(object?.users) ? object.users.map((e: any) => User.fromJSON(e)) : [],
      user: isSet(object.user) ? User1.fromJSON(object.user) : undefined,
    };
  },

  toJSON(message: User): unknown {
    const obj: any = {};
    if (message.users?.length) {
      // expected: ... => User1.toJSON(e));
      obj.users = message.users.map((e) => User.toJSON(e));
    }
    if (message.user !== undefined) {
      obj.user = User1.toJSON(message.user);
    }
    return obj;
  },

...
}
```
For non-repeated fields, the correct alias `User1` is created.

## Solution
After studying the code, I guess I found a place with an error. Calling [toCodeString](https://github.com/stephenh/ts-proto/blob/main/src/main.ts#L2336), [toString](https://github.com/stephenh/ts-proto/blob/main/src/main.ts#L2118) leads to caching of the calculated value ([code](https://github.com/stephenh/ts-poet/blob/main/src/Code.ts#L68), [codeWithImports](https://github.com/stephenh/ts-poet/blob/main/src/Code.ts#L49)).
As far as I understand, because of this, when code is generated from all the collected `Code` instances later, these objects retain an incorrect value that does not take into account the necessary parameters/context.

I've opened a small PR, that fixes this.

**Comment by stephenh** [comment]
Ah! Your diagnosis is exactly right; we need to keep the `readSnippet` as the `Code` object for its import to get rewritten appropriately. Thanks for the fix and great PR!
