### ISSUE TITLE
grpc client receive date wrong with grpc server create by nestjs and type orm

### ISSUE THREAD

**Issue by kuribo001** [stephenh/ts-proto#1082]
hi all,
the first, i sorry because my english not good.
i got the issue:
in nestjs domain, i create entity typeorm with type timestamp and save data. it worked good.
![image](https://github.com/user-attachments/assets/7413c744-79ff-40bb-92e6-5d804b42f465)
but when i  using rgpc client create by nestjs and then,  i receive date is "creatdt": "1970-01-01T00:00:00.000Z"
i have check data in database and debug, everything is good.
please help me fix it
---- data debug in domain---
![image](https://github.com/user-attachments/assets/8f7c4438-ab13-4ad4-9a2a-5522643a896c)
---- data debug in bff ----
![image](https://github.com/user-attachments/assets/c7dd0644-f8a0-49d9-aff7-1fa6a7362587)
---- proto ffile ---
![image](https://github.com/user-attachments/assets/8e24339c-9531-4e06-a982-9c44290c5876)
---- model after buf generate
![image](https://github.com/user-attachments/assets/320f25df-749e-4f8f-93e2-75acece771d2)
---- buf.gen.yml ----
![image](https://github.com/user-attachments/assets/b9a5454d-59dd-43f7-91a7-bcea0de79a65)

**Comment by stephenh** [comment]
Hi @kuribo001 ! My guess is that you're running into https://github.com/stephenh/ts-proto/issues/852 ; that issue is blocked on a protobufjs issue, that we might get unblocked from in ts-proto 2.x, but for now I'm going to close this out; thanks!

**Comment by kuribo001** [comment]
hi @stephenh , tks for your respone,

i read about issue #852  before asking this question.

i think i confused you in the 2nd picture, that picture i took from jsoneditoronline.org so you might have misunderstood that i used string type for date.

this is the result i debugged at domain level.

`{
  gameusers: GameUserEntity {
    gid: '94c7ae03-6537-469f-a5bc-d9cd241ba140',
    uid: '7bfd761d-5d2a-48c6-b65d-08fc7573ceb2',
    name: 'addfbc',
    logintype: 'device',
    linkeduid: null,
    linkedtype: null,
    dataversion: 5,
    keyversion: 332844,
    creatdt: 2024-08-04T11:24:04.338Z
  }
}`

you can see i using date type for creatdt attribute.
