### ISSUE TITLE
Flag to make arrays optional/nullable

### ISSUE THREAD

**Issue by philikon** [stephenh/ts-proto#109]
Repeated fields in proto are somewhat by definition optional, because repeating a field zero times is valid. It'd be nice if (optionally) ts-proto generated code would not require consumers to specify empty array fields.

**Comment by stephenh** [comment]
@philikon I believe that makes sense, probably if the existing `useOptionals` flag is `true`?

Fwiw wonder if `fromPartial` would alleviate some of this (just musing, but even the original `useOptionals`) case. I.e. the idea of `fromPartial` is that you can play fast-and-loose when _creating_ the data, but then the "protobuf defaults" are applied and you get non-optionals fields out the either side.

(I.e. during creation, optional fields are nice, but during reading, they're kinda a PITA b/c then you have to `undefined` check everything. In theory `fromPartial` is the best of both worlds...)

Nonetheless, we already have `useOptionals`, so I suppose having them mean all repeated fields are key-optionals as well wouldn't hurt. I.e. if you're already opting in to the "make creation nicer but more null checks for readers".

**Comment by philikon** [comment]
Sounds good. Will send a PR.

**Comment by maxdbn** [comment]
Interested in this feature myself! @philikon any luck with that?

**Comment by hpx7** [comment]
In typescript you can have an interface with both required and optional arrays:
```
interface Example {
  required: string[];
  notRequired?: string[];
}
```

In proto you can achieve this using a wrapper message:
```
message MaybeArray {
  repeated string array = 1;
}
message Example {
  optional MaybeArray notRequired = 1;
}
```

@stephenh what are you thoughts on this pattern? Do you think ts-proto could support it somehow?

**Comment by stephenh** [comment]
@hpx7 yeah, the `StringArrayValue` makes sense, its a lot like the existing wrapper values i.e. `google.protobuf.StringValue` or what not that are conventionally used to make strings optional.

It'd be great if your idea was similarly canonized by protobuf, i.e. as an official `google.protobuf.StringArrayValue` type. That'd make it fairly obvious for ts-proto to support.

Without that, I'm somewhat ambivalent. I guess for me personally, I rarely care about modeling the difference between "this array is not set" and "this array is set but zero length"; i.e. I almost always go with the 2nd, which can be done with the `fromPartial` approach today.

**Comment by oyvindwe** [comment]
Looks like this is now supported with `useOptionals=all`.

**Comment by stephenh** [comment]
Thanks for noticing that @oyvindwe ! Going to close this out.
