### ISSUE TITLE
protoc-gen-ts_proto no longer points to the correct plugin location in version 2.0.0

### ISSUE THREAD

**Issue by harrychap** [stephenh/ts-proto#1090]
Noticed when using with gradle like this:
```
protobuf {
    plugins {
        ts {
            path = './node_modules/ts-proto/protoc-gen-ts_proto'
        }
    }
    generateProto.finalizedBy copyGeneratedProto
    protoc {
        artifact = "com.google.protobuf:protoc:${protobufVersion}"
    }
    generateProtoTasks {
        all().each { task ->
            task.plugins {
                js {
                    option "import_style=commonjs"
                    option "binary"
                }
                ts {
                }
            }
        }
    }
}
```

It fails with this path `./node_modules/ts-proto/protoc-gen-ts_proto`

 Error: Cannot find module './build/plugin'
 
 because build is now './build/src/plugin'

**Comment by stephenh** [comment]
Shoot! Thanks for the report @harrychap , will take a look. I had tried to release 2.0 as an alpha, but it didn't work , and told npm to `unpublish` it, but that doesn't seem to have worked :grimacing:

**Comment by stephenh** [comment]
Okay, I pushed out a fix -- @harrychap if you could confirm it works, that would be great! Thank you!

**Comment by harrychap** [comment]
hmm might be more to it than that actually @stephenh 
`> protoc: stdout: . stderr: FAILED!Cannot find module '../package.json'`
Which I think relates to this https://github.com/stephenh/ts-proto/blob/main/src/utils.ts#L334

**Comment by stephenh** [comment]
:grimacing: sorry guys, as you can tell, I don't have a great project-in-the-wild to actually test these things, and our CI pipeline isn't picking them up.

I'll merge #1091 as soon as it passes CI and please do report back! :pray: :crossed_fingers:

**Comment by wakingrufus** [comment]
It is working for me now

**Comment by wakingrufus** [comment]
Thanks for the quick fix!

**Comment by stephenh** [comment]
Whew! Thanks for confirming @wakingrufus ! Going to close this out, but happy to address any more issues/gotchas. :crossed_fingers:
