### ISSUE TITLE
v2.0.2 missing package.json

### ISSUE THREAD

**Issue by rfenlon** [stephenh/ts-proto#1093]
`getVersions` inside `build/src/utils.js` references `../package.json` which does not exist in this version.

**Comment by stephenh** [comment]
Hi @rfenlon ; I'm pretty sure this just got fixed in 2.0.2; can you run 

```
cat node_modules/ts-proto/package.json | grep version
```

And verify you have the 2.0.2 fix? Thanks!

**Comment by rfenlon** [comment]
Oh, weird. Both my source tree from earlier in the day and a test dir I just created were version 2.0.2 but the newer test dir had the correct path `    const path = "../../package.json";`  

Must be user error. Sorry, for the confusion!

**Comment by stephenh** [comment]
No problem! Always appreciate reaching out.
