### ISSUE TITLE
Flag to generate enums as TypeScript enums

### ISSUE THREAD

**Issue by philikon** [stephenh/ts-proto#110]
What's the reason for generating protobuf enums the way they're currently being generated, e.g.

```proto
enum StateEnum {
  UNKNOWN = 0;
  ON = 2;
  OFF = 3;
}
```

becomes
```ts
export const StateEnum = {
  UNKNOWN: 0 as const,
  ON: 2 as const,
  OFF: 3 as const,
  UNRECOGNIZED: -1 as const,
}
export type StateEnum = 0 | 2 | 3 | -1;
```

rather than

```ts
enum StateEnum {
  UNKNOWN = 0,
  ON = 2,
  OFF = 3,
  UNRECOGNIZED = -1,
}
```

Would it be ok if we made the native TypeScript enum available as a flag? It's handy for a variety reasons, including the ability to do reverse lookups (find name by value).

**Comment by stephenh** [comment]
Yeah, they are not `enum`s b/c of this issue:

https://github.com/stephenh/ts-proto/issues/40

Where I was "adding" methods to the enum like `StateEnum.encode` / `StateEnum.decode` by using a `namespace StateEnum`, which doesn't work in babel.

I had also looked at putting the enum `encode` / `decode` methods "somewhere else", but having them be "like static methods on `StateEnum`" makes it really convenient when using enums across different proto files...

Granted, could fix this, and then go back to actual-`enum`s.

**Comment by philikon** [comment]
Ah, of course. The `encode`/`decode` thing makes sense. I mostly care about the reverse lookup, not having them be actual enums. Any objections to adding the reverse lookup? Should it be behind a flag? My inclination is no, since regular TS enums support reverse lookup out of the box.

**Comment by stephenh** [comment]
Yeah, I agree would be great to avoid yet-another-flag for this...

I'm torn. I'm tempted to just go back to `enum`s and just figure out where to put the `encode`/`decode` methods.

Part of the wrinkle is that it can't be something generic like:

```
export class Enums {
  public static decodeStateEnum(...) ...
  public static encodeStateEnum(...) ...
}
```

B/c then `import { Enums } from file-a` and `import { Enums } from file-b` will conflict (technically ts-poet 3.x solves this and would do `Enums as Enums1` and `Enums as Enums2`...so could just bite the bullet and upgrade to that...

Or could use top-level functions, i.e. just `export function decodeStateEnum`...

**Comment by stephenh** [comment]
I moved back to `enum`s in this PR https://github.com/stephenh/ts-proto/pull/113. Should have probably done that as the original solution to the "babel doesn't support namespaces" problem. Thanks for the nudge!

**Comment by philikon** [comment]
Thank you!
