### ISSUE TITLE
ts-proto needs to rev ts-proto-descriptors version so no protobufjs packages install

### ISSUE THREAD

**Issue by jereklas** [stephenh/ts-proto#1101]
When protobufjs was replaced the `ts-proto-descriptor` package.json changed it's dependencies, but never published a new package. The `ts-proto` package also did not rev the `ts-proto-descriptor` dependency version (as there isn't one yet). 

This results in a bunch of `@protobufjs/*` packages being installed by package managers (for type information) that shouldn't be installed at all (e.g. installing ts-proto@^2 will install ts-proto-descriptors@1.16.0 which installs protobufjs@7.2.5 -- which isn't correct based on the current set of files on the main branch)

**Comment by stephenh** [comment]
Ah yeah, great catch @jereklas -- thanks for filing the issue! I believe I've fixed this in the latest minor release; let us know if not.

**Comment by jereklas** [comment]
I installed 2.1.0, but the issue is fixed there so I'll assume it was also correct in 2.0.4. Thanks for the quick turn around on this!
