### ISSUE TITLE
Error "illegal buffer" on decoding (deno)

### ISSUE THREAD

**Issue by samuelsiv** [stephenh/ts-proto#1103]
Hello, after rewriting most of my protobuf schema it seems like my server cannot decode the serialized protobuf it's being sent, it seems like it's failing inside the decoding of the existing "oneof" field of the sent data.

Example schema:
```
syntax = "proto3";
package testissue;
option optimize_for = LITE_RUNTIME;

message UserString {
  string data = 1;
}

message Ping{
  int32 number = 1;
}

message Request {
  int32 packet_type = 1;
  oneof payload {
    Ping ping = 2;
    UserString string = 3;
  }
}
```

Code:
```
Deno.test({
    name: "Protobuf",
    fn() {
        const sampleData: Request = {
            packetType: 1,
            ping: {
                number: 1
            }
        };

        const encoded = PacketRequest.encode(sampleData).finish();

        console.log(encoded);

        const decoded = PacketRequest.decode(encoded);

        console.log(decoded);

        assertEquals(
            sampleData,
            decoded,
            "Sample data does not equal to the decoded data",
        );
    },
});
```

Output:
```
------- output -------
Uint8Array(8) [
  8, 4, 26, 2,
  8, 1, 40, 1
]
----- output end -----
Protobuf ... FAILED (5ms)
P token ... ok (5ms)

 ERRORS 

Protobuf => ./src/test.ts:8:6
error: Error: illegal buffer
    at Function.create (https://esm.sh/v131/protobufjs@7.2.5/denonext/minimal.js:12:10135)
    at Object.decode (file:///G:/**/proto/packet.ts:311:69)
    at Object.decode (file:///G:/**/proto/packet.ts:583:41)
    at fn (file:///G:/**/src/test.ts:23:39)
```

The protobuf declarations have been built with the following command line: ```protoc --plugin=protoc-gen-ts_proto=\".\\node_modules\\.bin\\protoc-gen-ts_proto.cmd\" --ts_proto_out=. ./proto/packet.proto```
ProtoC version: libprotoc 25.1

**Comment by stephenh** [comment]
Hi @samuelsiv , it looks like the error is happening within `protobufjs@7.2.5` , which is the underlying protobuf library that ts-proto uses for serialization...

Our latest 2.x releases moved to using `@bufbuild/protobuf` instead of `protobufjs`; can you try using a ts-proto release and see if that fixes the issue?

Thanks!

**Comment by stephenh** [comment]
Whoops, didn't mean to close...

**Comment by samuelsiv** [comment]
![image](https://github.com/user-attachments/assets/38635c3f-ec44-4d83-a2ae-e3c963405434)
Seems like that did it!
Thank you so much :)

**Comment by stephenh** [comment]
Oh that's great! Kudos to @timostamm -- `@bufbuild/protobuf` FTW! :-)
