### ISSUE TITLE
Add support for reserved message names.

### ISSUE THREAD

**Issue by halkeye** [stephenh/ts-proto#1110]
```
// Function notification settings
message Function {
    string namespace = 1;
    string name = 2;
}
```

Generates a file that typescript is unable to process (for good reason)
```
 error TS2345: Argument of type 'Function | {}' is not assignable to parameter of type 'Function'.
  Type '{}' is missing the following properties from type 'Function': namespace, name
```

I know i can use `--ts_proto_opt=typePrefix=MyPrefix` or `--ts_proto_opt=typeSuffix=MySuffix` to add extra to each type, but that would do it for everything, not just reserved words, which would make migrated to generated output a little rougher.

Is there anything I can do to handle the reserved ones? I am up for contributing.

```
message Object {
  string key = 1;
}
```

Is another example.

**Comment by stephenh** [comment]
Hi @halkeye ! That makes sense...kinda surprised we haven't ran into this before :thinking: 

Ah yeah, I think it's here:

https://github.com/stephenh/ts-proto/blob/ffacf3aaa8fad43c69e75a184c0703fc050b7868/src/visit.ts#L63

Maybe just add `Function` to that `builtinNames`? 

A PR would be great! Thanks!

**Comment by halkeye** [comment]
I'm going to get you a pr soon, but so i don't forget it, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects is probably some others that might be worth grabbing a few from

**Comment by halkeye** [comment]
for the life of me I can't reproduce it, either inside my work container or here. So i'm not sure what changed.

I tried copying over the tsconfig, and the entire protofile.

When i get a minute I'll ry running the build at work again.

**Comment by jdillon** [comment]
This change causes nested messages to break from previous behavior.

```
message Scope {
   message Function {
   }
}
```

Used to render as `interface Scope_Function` but now will render as `interface Scope_FunctionMessage` ... which is erroniously appending `Message` to this type name.
