### ISSUE TITLE
Message fields marked with `x | undefined` even when `useOptionals=none`

### ISSUE THREAD

**Issue by tresabhi** [stephenh/ts-proto#1116]
```proto
message BoundingBox {
  Vector3 min = 1;
  Vector3 max = 2;
}
```

turns into

```ts
export interface BoundingBox {
  min: Vector3 | undefined;
  max: Vector3 | undefined;
}
```

though this is what I expected

```ts
export interface BoundingBox {
  min: Vector3;
  max: Vector3;
}
```

If I understand this correctly, `useOptionals` only controls the TypeScript optional parameter (`key?: Value`) in which case the issue above is functioning as intentional. How would I go about eliminating the `x | undefined`? I would like just `key: Value` as stated by the original message?

As for type-safety (because Protobuf doesn't guarantee the presence of a field when parsing), I have full faith in my API to serve all fields because it will literally throw an error 500 if it doesn't populate the fields.

Also using `useOptionals=anythingherebutvalidoptions` achieves my desired effect but breaks the generated encoding/decoding code.

**Comment by tresabhi** [comment]
Perhaps this behavior or assuming populated message fields should be an option `assumePopulatedMessageFields=true`.

**Comment by tresabhi** [comment]
I am stupid

**Comment by stephenh** [comment]
No worries @tresabhi ! It's common to want/expect this behavior from protobuf, but not much we can do... :shrug:

**Comment by tresabhi** [comment]
@stephenh what if I do want a required field? Using required for a message in proto2 still results in undefined.

**Comment by tresabhi** [comment]
Yes, it does support required. In fact, you must explicitly state if a field is optional or required. I will PR ASAP.
