### ISSUE TITLE
Omit optional fields from construuction using fromJSON/fromPartial

### ISSUE THREAD

**Issue by ii64** [stephenh/ts-proto#1129]
When fields are optional, json-methods `toJSON` does omit fields when they are `undefined`. However if we are trying to round-trip the output into `fromJSON` it will construct an object with default value even fields are marked as an optional - this break the consistency of what data expected before and after the JSON method transform.

Should we have an implementation that checks if fields are optional during the construction from JSON? I understand that people may have the need of constructing it with default value - but at the other perspective putting the optional fields value `undefined` does make sense if the field itself is marked as optional.

**Comment by stephenh** [comment]
Hi @ii64 , will `--ts_proto_opt=noDefaultsForOptionals=true` do what you're looking for?

**Comment by ii64** [comment]
The `initializeFieldsAsUndefined` is enabled by default and it does not change anything in the output, however turning it to `false` giving me the consistency I want from JSON method transforms round-trip, closing this as resolved. Thanks
