### ISSUE TITLE
Support for reading the raw bytes of a message

### ISSUE THREAD

**Issue by zakhenry** [stephenh/ts-proto#1130]
While I really appreciate the mechanism that construction of proto messages with this library feels just like a plain old javascript object, when reading the messages that have been parsed from elsewhere it is often useful to be able to read the underlying bytes.

Reasons for this are when the TS application is acting as a middleware, and it is not up to date with the latest api version, it should still be able to pass a message around verbatim without losing the original value. Another use case is if an outdated client receives a message from a service that it doesn't recognise, it can at least lodge the failure to an external issue tracker as bytes that devs might be able to diagnose the issue with the up-to-date protocol.

It would appear this library already is not quite a plain js object underneath as in order to serialize them I have to delete the `.toObject()` method.

I'd suggest overriding the `.valueOf()` to return the original encoded data as `Uint8Array`. An alternative would be to attach it as a property using a `symbol`.

This does raise the question of what to do for modified messages, for this either the implementation of `.valueOf()` re-encodes self each time and returns that, or it maintains a hidden field to mark the object as dirty and re-encodes when needed, or an explicit `.update()` method is added (kinda like nodejs hashing apis).

Since this option would increase the memory footprint of decoded messages, it should be an opt-in feature flag.

---

If there is interest I'd be happy to raise a PR to implement this functionality

**Comment by stephenh** [comment]
Hi @zakhenry , yep, totally get that middleware type usages need to keep ahold of unknown fields.

I'm actually kinda surprised more people have not asked for this feature sooner. :-)

I think ideally (?) we wouldn't have to store the entire message as it's original `Uint8Array` (unless there was a flag that explicitly turned on that behavior?) but instead something like:

```ts
  authorMessage[unknownFields] = map/array of only the unknown data
```

Which I think is basically what our `unknownFields=true` flag started to do, i.e. it generates code like:

```ts
  it("works with repeated fields", () => {
    const test: Extendable = {
      field: "repeated",

      _unknownFields: {
        [(6 << 3) | 2]: [new Uint8Array([1, 1]), new Uint8Array([1, 1])],
        [(6 << 3) | 0]: [new Uint8Array([2]), new Uint8Array([3]), new Uint8Array([5])],
      },
    };
```

Granted, I think:

* Currently `_unknownFields`, when enabled, is added to all messages, and I like the idea of a symbol that is hidden by default better
* I don't think (?) we've taught `encode` to put the unknown fields back on the wire.

...er, actually we did?

```ts
export const Extendable: MessageFns<Extendable> & ExtensionFns<Extendable> = {
  encode(message: Extendable, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.field !== undefined && message.field !== "") {
      writer.uint32(10).string(message.field);
    }
    if (message._unknownFields !== undefined) {
      for (const [key, values] of Object.entries(message._unknownFields)) {
        const tag = parseInt(key, 10);
        for (const value of values) {
          writer.uint32(tag).raw(value);
        }
      }
    }
    return writer;
  },
```

So maybe `unknownFields` already does what you want? Albeit maybe the symbol would be cleaner/less obtrusive than the `_unknownFields`.

**Comment by zakhenry** [comment]
Ah yea I think you might be right, I'll have a go with that option turned on

**Comment by stephenh** [comment]
@zakhenry going to close this out since we think that `_unknownFields` provides the "reading raw bytes of a message"; but lmk if you think we should keep it/change it?

**Comment by zakhenry** [comment]
Yep happy to keep it closed until I find some time to revisit this and try the existing functionality, cheers
