### ISSUE TITLE
It seems that outputEncodeIncludeTypes and outputDecodeIncludeTypes in opt are not working properly.

### ISSUE THREAD

**Issue by Bloomingg** [stephenh/ts-proto#1144]
I am trying to convert multiple protobufs and generate encode and decode methods only for specific types. However, after I specify the `outputEncodeIncludeTypes` and `outputDecodeIncludeTypes` parameters, although some types indeed do not generate these two methods, there are still a large number of redundant types that generate them. Below is my script. Can you help me troubleshoot the problem? Thank you very much!
```bash
#!/bin/bash

ROOT_DIR="$(pwd)"

OUT_DIR="${ROOT_DIR}/pbts_out"
rm -rf ${OUT_DIR}
mkdir -p ${OUT_DIR}

proto_files=()
while IFS= read -r -d $'\0' proto_file; do
    proto_files+=("${proto_file}")
done < <(find ${ROOT_DIR} -name "*.proto" -print0)

protoc --plugin=protoc-gen-ts_proto="${ROOT_DIR}/node_modules/.bin/protoc-gen-ts_proto" \
       --ts_proto_opt=esModuleInterop=true,messages=true,outputJsonMethods=false,outputPartialMethods=false,outputClientImpl=false,outputEncodeIncludeTypes='^(MsgData|GetActiveConversationsReq|GetConversationsHasReadAndMaxSeqReq|PullMessageBySeqsReq|GetDesignatedConversation|GetSeqMessageReq|SubUserOnlineStatus)$',outputDecodeIncludeTypes='^(?GetMaxSeqResp|PullMessageBySeqsResp|UserSendMsgResp|GetSeqMessageResp|PushMessages|SetAppBackgroundStatusResp|SubUserOnlineStatusTips|GetConversationsHasReadAndMaxSeqResp|GetActiveConversationsResp|GetConversationsResp)$' \
       --proto_path="${ROOT_DIR}" \
       --ts_proto_out="${OUT_DIR}" \
       "${proto_files[@]}"

echo "Generated TypeScript files in ${OUT_DIR}"
```

**Comment by stephenh** [comment]
Hi @Bloomingg can you clarify what "redundant types" are showing up? You've not provided any *.proto flies to have a clue about what the output is, and saying "please debug my script" is putting a lot of onus on me.

For now I'm going to close this issue.

If you'd like us to look at something, please post the most minimal proto file possible, with the most minimal IncludeTypes possible, and show specifically what is wrong in the output. Thanks!

**Comment by Bloomingg** [comment]
> Hi @Bloomingg can you clarify what "redundant types" are showing up? You've not provided any *.proto flies to have a clue about what the output is, and saying "please debug my script" is putting a lot of onus on me.
> 
> For now I'm going to close this issue.
> 
> If you'd like us to look at something, please post the most minimal proto file possible, with the most minimal IncludeTypes possible, and show specifically what is wrong in the output. Thanks!

I am very sorry. Because I am worried that this is caused by incorrect usage or configuration on my part. Regarding the proto file and the new test script, I will propose them below.

**Comment by Bloomingg** [comment]
This is the git address of a proto repository: https://github.com/openimsdk/protocol. I need to convert all the files in it. Now I have only done the conversion for the `auth/auth.proto` file. I specified two IncludeTypes, but it can be seen that there are still types that are not included in the result and encode and decode methods are generated.
```bash
#!/bin/bash
ROOT_DIR="$(pwd)"

protoc --plugin=protoc-gen-ts_proto="${ROOT_DIR}/node_modules/.bin/protoc-gen-ts_proto" \
       --ts_proto_opt=esModuleInterop=true,messages=true,outputJsonMethods=false,outputPartialMethods=false,outputClientImpl=false,outputEncodeIncludeTypes='^(getAdminTokenReq|getAdminTokenResp)$',outputDecodeIncludeTypes='^(getAdminTokenReq|getAdminTokenResp)$' \
       --proto_path="./auth" \
       --ts_proto_out="./" \
       auth.proto

echo "Generated TypeScript files in ${OUT_DIR}"
```

**Comment by Bloomingg** [comment]
Hi @stephenh could you please take a look at this problem again for me? Thanks very much!
