### ISSUE TITLE
Support option fields

### ISSUE THREAD

**Issue by randy75828** [stephenh/ts-proto#1150]
Is there a way to map option fields in ts-proto as well? Currently it seems omitted.

Original Proto file:
![image](https://github.com/user-attachments/assets/b6c76fb9-d4b9-42c4-bfc2-01a68c317e98)

Generated ts file:
![image](https://github.com/user-attachments/assets/5ca56bbd-1f3e-45db-a02d-9362b878e24f)

As you can see, `cosmos.msg.v1.signer` and `amino.name` are not mapped over

**Comment by stephenh** [comment]
Hi @randy75828 , `option`s are not the same thing as fields, so they would not show up on the `MsgExec` itself. However I'm pretty sure if you turn on `outputSchema` we'll output metadata with the options in it; not 100% but that's what I'd try. Thanks!
