### ISSUE TITLE
Support string enums option

### ISSUE THREAD

**Issue by stephenh** [stephenh/ts-proto#119]
I.e. generate

```typescript
export enum StateEnum {
  UNKNOWN = "UNKNOWN",
  ON = "ON",
  OFF = "OFF",
  UNRECOGNIZED = "UNRECOGNIZED",
}
```

**Comment by philikon** [comment]
What does this ticket entail? I read through #117 but don't really understand what's being proposed here.

**Comment by stephenh** [comment]
@philikon ah yeah, this was vague. I updated the description, basically to do `FOO = "FOO"` as enum values instead of `FOO = 0`.

There was an old PR that started work on this:

https://github.com/stephenh/ts-proto/pull/38

But didn't handle the `encode`/`decode` side of things, which would still need to be the numbers.
