### ISSUE TITLE
Optional primitives

### ISSUE THREAD

**Issue by rubennaatje** [stephenh/ts-proto#120]
Is there a way to make sure everything is optional? 

We used to have our own interface generator from protos that did that but we're now opting for an open source one, that is the only issue however. 

Reason is that we use an gRPC service that breaks when some values are used with some calls.

**Comment by rubennaatje** [comment]
@stephenh thanks for the well explained answer. I get all your points. 

And especially the last bit was interesting for me. I don't know why at some point we thought we needed all optionals but now I've completely replaced our stuff with yours.  And it works fine :)

So thanks for your time and thanks for your work.

**Comment by stephenh** [comment]
@rubennaatje cool, thanks for the follow up. :-) Glad it worked out!
