### ISSUE TITLE
Can't set options - Getting "Unknown flag: --ts_proto_opt"

### ISSUE THREAD

**Issue by szymski** [stephenh/ts-proto#121]
I'm using version 1.28.0.
Command: ``protoc --plugin=./node_modules/.bin/protoc-gen-ts_proto --ts_proto_opt=env=node --ts_proto_out=./src proto/manager.proto``
Output: ``Unknown flag: --ts_proto_opt``

**Comment by PhilipMantrov** [comment]
same issue
tried with 3.13.0 and 3.11.4 versions of protobuf, same thing
os: win10, x64

**Comment by stephenh** [comment]
@PhilipMantrov have you seen the readme entry for windows:

```
protoc --plugin=protoc-gen-ts_proto=.\node_modules\.bin\protoc-gen-ts_proto.cmd --ts_proto_out=. ./imple.proto
```

In general, this is not a ts-proto issue, and a `protoc` CLI usability issue, which I sympathize with but generally can't do much about.

**Comment by PhilipMantrov** [comment]
`protoc --plugin=protoc-gen-ts_proto=%CD%/node_modules/.bin/protoc-gen-ts_proto.cmd --ts_proto_opt=outputClientImpl=grpc-web --ts_proto_out=#{dir} #{dir}\#{base} -I #{dir} #{base} `

%CD% -- resolve this issue 
@stephenh add this in readme pls, its will help all windows users
