### ISSUE TITLE
[Suggestion] export const for generateGrpcServiceDesc and generateGrpcMethodDesc

### ISSUE THREAD

**Issue by PhilipMantrov** [stephenh/ts-proto#128]
Need do generateGrpcServiceDesc and generateGrpcMethodDesc const's exportable for additional customs unary methods. 
Example: I have `export function grpcInvokeToObservable<T>(host: string, def: any, request: any): Observable<T>` with custom factory and some additional checkers and i need to provide "def" but i cant because they not exportable.

**Comment by stephenh** [comment]
Looks like this was already fixed in a separate PR.
