### ISSUE TITLE
Can't get it working

### ISSUE THREAD

**Issue by Daniel15** [stephenh/ts-proto#13]
I'm trying to see if this project will generate TypeScript definitions for my Protobuf types (sounds like it will). However, I can't seem to get it working. I tried a command similar to the one in the readme, which gave me:
```
c:\apps\protobuf\bin\protoc --plugin=./node_modules/.bin/protoc-gen-ts_proto --ts_proto_out=./src/generated --proto_path=../../Proto ../../Proto/dnstools.proto

--ts_proto_out: protoc-gen-ts_proto: %1 is not a valid Win32 application.
```

After reading https://github.com/protocolbuffers/protobuf/issues/3923, I tried `protoc-gen-ts_proto.cmd` as the plugin path, which gave me a different error:
```
c:\apps\protobuf\bin\protoc --plugin=./node_modules/.bin/protoc-gen-ts_proto.cmd --ts_proto_out=./src/generated --proto_path=../../Proto ../../Proto/dnstools.proto
'protoc-gen-ts_proto' is not recognized as an internal or external command,
operable program or batch file.
--ts_proto_out: protoc-gen-ts_proto: Plugin failed with status code 1.
```

Any ideas?

**Comment by Daniel15** [comment]
This worked for me:
```
c:\apps\protobuf\bin\protoc --plugin=protoc-gen-ts_proto=.\node_modules\.bin\protoc-gen-ts_proto.cmd --ts_proto_out=./src/generated --proto_path=../../Proto ../../Proto/dnstools.proto
```

I had to prefix the plugin path with `protoc-gen-ts_proto=`, and use `\` instead of `/` in the path.

Should I submit a PR for the readme?

**Comment by stephenh** [comment]
Huh, I hadn't seen the `--plugin=...plugin...=path` syntax before, wonder why it was working for me without that. Either way, that looks more canonical, so sure, a readme PR sounds great. Thanks!

**Comment by stephenh** [comment]
Thanks @Daniel15 !

**Comment by SySagar** [comment]
I was making auth system in the same folder as the proto file is.
For me it worked something like this:

protoc --plugin=protoc-gen-ts_proto=.\node_modules\.bin\protoc-gen-ts_proto.cmd --ts_proto_out=./ --ts_proto_opt=nestJs=true ./proto/auth.proto

**Comment by arifMediaNv** [comment]
> I was making auth system in the same folder as the proto file is. For me it worked something like this:
> 
> `protoc --plugin=protoc-gen-ts_proto=.\node_modules\.bin\protoc-gen-ts_proto.cmd --ts_proto_out=./ --ts_proto_opt=nestJs=true ./proto/auth.proto`

thank you also worked for me

**Comment by edgaremirborbonjimenez** [comment]
> I was making auth system in the same folder as the proto file is. For me it worked something like this:
> 
> `protoc --plugin=protoc-gen-ts_proto=.\node_modules\.bin\protoc-gen-ts_proto.cmd --ts_proto_out=./ --ts_proto_opt=nestJs=true ./proto/auth.proto`

I have been trying to do that but the terminal returns me this:

this is what I put in the terminal:

$ protoc --plugin=protoc-gen-ts_proto=.\node_modules\.bin\co/api-cliente-movil (featurprotoc-gen-ts_proto.cmd --ts_proto_out=./ --ts_proto_opt=nestJs=true ./proto/product.proto 

and this is the response:
--ts_proto_out: protoc-gen-ts_proto: The system cannot find the file specified.

And it says that may be doesn´t can find the protoc-gen-ts_proto file, but if I look for the protoc-gen-ts-proto file i found it in ./node_modules/bin/protoc-gen-ts_proto.cmd

**Comment by Nickbrian246** [comment]
this works to me 
* install again => npm install ts-proto
* change the "\" for "\\" like this  => protoc --plugin=protoc-gen-ts_proto=.\\node_modules\\.bin\\protoc-gen-ts_proto.cmd --ts_proto_out=./ --ts_proto_opt=nestJs=true  ./proto/auth.proto
