### ISSUE TITLE
ts-proto does not support `optional` keyword

### ISSUE THREAD

**Issue by maxdbn** [stephenh/ts-proto#135]
_Although the doc says that this package supports `optional` keyword, it does not_

`ts-proto` version: `1.34.0`
`protoc` version: `libprotoc 3.13.0`

Executing the following command:
```
PROTOC_GEN_TS_PATH="./node_modules/.bin/protoc-gen-ts_proto"
PROTO_FILE="./src/protobuf/foo.proto"
OUT_DIR="."

protoc \
    --plugin="${PROTOC_GEN_TS_PATH}" \
    --experimental_allow_proto3_optional \
    --ts_proto_opt=env=node,oneof=unions,useOptionals=true,outputEncodeMethods=false,outputJsonMethods=false,outputClientImpl=false \
    --ts_proto_out="${OUT_DIR}" "${PROTO_FILE}"
```

gives the following message:
> foo.proto: is a proto3 file that contains optional fields, but code generator protoc-gen-ts_proto hasn't been updated to support optional fields in proto3. Please ask the owner of this code generator to support proto3 optional.--ts_proto_out:

And it totally ignores the `optional` keyword

**Comment by stephenh** [comment]
Ah shoot, forgot to return the "yes we support optional" flag in the response. Can you try v1.35.0?

**Comment by maxdbn** [comment]
It works! Thank you so much for your work
