### ISSUE TITLE
don't encode scalar zero values

### ISSUE THREAD

**Issue by philikon** [stephenh/ts-proto#138]
Following up on https://github.com/stephenh/ts-proto/issues/102#issuecomment-674537698:

> re "not even emit the bytes for myType if its value is 0", in theory that's "how protobuf is supposed to work" for default values, i.e. any primitive that has a value that is that primitive's default value, "it's a feature" to not include it on the wire, and just assume that the reader/decoder is going to treat any missing-primitive as that fields value.

I realized that that's actually NOT how ts-proto currently works. ts-proto will always encode a scalar field, even when it's 0, the empty string, etc. Should we change that? I'd like to at least have an option for it. Will be happy to write the code for it.

**Comment by stephenh** [comment]
@philikon sure!
