### ISSUE TITLE
Lookup Decoder by google.protobuf.Any typeUrl

### ISSUE THREAD

**Issue by andrewparmet** [stephenh/ts-proto#142]
We have a use case where we'd like to send a batch of protobuf messages from a server to a client that uses ts-proto for its version of the protobuf definitions. They'll be embedded in Any objects. Rather than having to manually maintain a map of typeUrl to Decoder, is there any way to (possibly reflectively) access all available Decoders and index them by typeUrl?

Thanks!

**Comment by stephenh** [comment]
@andrewparmet hm, interesting. I'm not entirely sure what `typeUrl` is (probably the protobuf package + type name like `.google.protobuf.Foo`)?

I could see something like:

```
import * as mod1 from "mod1";
import * as mod2 from "mod2";

const registry = buildRegistry([mod1, mod2])
```

Where `buildRegistry` scans for the `const FooMessage = { ... }` objects that have `FooMessage.decode` keys.

I don't think the protobuf package is currently in the output (like if there was a `export const protobufPackage = ...`) that you could also lookup on the `mod1` namespace...

So, other than that `protobufPackage` const, I think you could probably build this `buildRegistry` as a user-land thing?

I.e. w/o the `packageBackage` it might have to be:

```
import * as mod1 from "mod1";
import * as mod2 from "mod2";

const registry = buildRegistry({ ".google.protobuf": mod1, ".yourpackage.foo": mod2 });
```

**Comment by andrewparmet** [comment]
Yes - the `typeUrl` is the protobuf package + type name but without the leading dot (and preceded by an optional custom `typeUrlPrefix` or `type.googleapis.com` if unspecified during packing). I imagined the indexing would mostly be a user-land reflective operation - I think the availability of the protobuf package at runtime is the only missing piece.

When you say "scan for the ... objects" - do you know a good reference on TS/JS that outlines how to do this kind of reflection? It's fairly new to me.

**Comment by stephenh** [comment]
@andrewparmet I'd take the `mod1` from `import * as mod1 from ...` and do something like `Object.entries(mod1)` and `console.log`/poke at them to see what they look like.

I haven't done it before but I'm pretty sure you'll see things like `FooMessage` come back (the `const` that has the `FooMessage.decode` function within it), and so could start building out your registry from there.

If you end up with a nice `buildRegistry` snippet, would appreciate pasting it here...

Hm, thinking more about it, maybe some sort of `export const typeRegistry: Record<string, SomeMetadataType>` would be pretty easy to produce at the codegen step, and then you could do:

```
const registry = { ...mod1.typeRegistry, ...mod2.typeRegistry };
```

I'm not entirely sure what `SomeMetadataType` should look like.

...well, and now I'm going back/forth, because I think you could build exactly this via the runtime reflection-ish approach, so maybe that is preferable to teaching the codegen output to do yet-another-thing.

I suppose it'd depend on how frequently / in what scenarios users need to do `google.protobuf.Any` handling. I've personally not used it myself yet, so don't have a lot of opinions/thoughts on it.

**Comment by andrewparmet** [comment]
I agree with your leaning toward runtime reflection until a more compelling use case is available. We do need that protobuf package available to write `buildRegistry` though, right? As far as I know that's something codegen has to provide.

**Comment by stephenh** [comment]
@andrewparmet yeah agreed on the protobuf package, I guess I was assuming you could just hard-code the protobuf package in a call like `buildRegistry({ ".google.protobuf": mod1, ".yourpackage.foo": mod2 });` for now.

How many modules do you have? If it's ~1-5 that should be fine. If it's 10s eh, if it's 100s that's going to suck. :-) 

That said, I'm perfectly fine adding a `export const protobufPackage` to the build output right away; if you want to submit a PR for that, that'd be great.

**Comment by andrewparmet** [comment]
It's in the 10s for now, but the idea for a generic registry of this sort would be to discover. I'll take a look at submitting a PR.

**Comment by andrewparmet** [comment]
I've opened a small PR #144 which adds the `protobufPackage` constant to each generated file. Playing around with the console and the `import * as ...` you mentioned looks like it'll do what I want.

Unfortunately it looks like there's no getting away from listing every terminal directory containing protobuf files. Is that true, or is there some magical way of traversing every file available and looking for constants named `protobufPackage`?

**Comment by andrewparmet** [comment]
Here's a demo of the new code working:
```typescript
type AppState = {
  listAll: any
}

export class App extends Component<{}, AppState> {
  constructor (props: {}) {
    super(props)

    var listAll = () => {
      var context = require.context('../../../node_modules/path/to/my/lib/top-proto-package', true, /\.js$/)
      var obj: any = {}
      context.keys().forEach(function (key) {
        obj[key] = context(key)
      })
      return obj
    }

    setState({ listAll: listAll })
  }
}

// Chrome debugger
$r.state.listAll()
// => 
// {
//   'top-proto-package/path/to/proto/proto_file.js':
//     GeneratedType:
//       decode: <...>
//       encode: <...>
//     GeneratedType2: <...>
//     protobufPackage: "path.to.proto"
// }
```

From here it should be straightforward to index the generated types by protobuf package and dynamically deserialize `Any`s.

Thanks for the guidance!

**Comment by stephenh** [comment]
> or is there some magical way of traversing every file available

Right, there is not once you're in the browser...

You could do something as a build-step, i.e. something like `npm run generate-any-registry` and then have this scan your `node_modules` for ts-proto-generated output. You could potentially add some sort of well-known output file to the ts-proto output, i.e. something like:

```
* node_modules
  * ts-proto-lib-a
     * a.proto
     * b.proto
     * dist
        * .ts-proto.json (contains files: [ "./a.ts", "./b.ts" ] )
        * a.ts
        * b.ts
 * ts-proto-lib-b
   * same thing...
```

Then scan for `**/ts-proto.json`s and use those to generate a single `ts-proto-libs.ts` file in your project that looks like:

That's assuming you've got multiple separate ts-proto-built libraries in your node_modules.

But anyway, probably only a concern once you get past low-10s of files.

Glad what you have so far is working out.
