### ISSUE TITLE
Allow disabling UNRECOGNIZED enum value

### ISSUE THREAD

**Issue by ShakedH** [stephenh/ts-proto#148]
I'm using this tool in order to create a client for defined values expected in a database.
I expect the data in the DB to be consistent with enums defined.

Hence, the `UNRECOGNIZED` option which is added automatically to enums causes noise and is unnecessary for me.

I think that adding an option to disable this value generation will be helpful.

**Comment by stephenh** [comment]
Published in 1.38.0. Thanks!
