### ISSUE TITLE
Tests failing after clone

### ISSUE THREAD

**Issue by Joehunk** [stephenh/ts-proto#15]
Hello. I am interested in contributing base64 support for the `bytes` type in JSON, as this is important to my use case.

I am having trouble running tests after cloning however. I run `./pbjs.sh` as the README instructs, but I get this when trying to run tests still:

>     TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
>     build/integration/simple.ts:1:31 - error TS2307: Cannot find module './import_dir/thing'.
> 
>     1 import { ImportedThing } from './import_dir/thing';
>                                     ~~~~~~~~~~~~~~~~~~~~
>     build/integration/simple.ts:4:27 - error TS2307: Cannot find module './google/protobuf/timestamp'.
> 
>     4 import { Timestamp } from './google/protobuf/timestamp';
>                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     build/integration/simple.ts:5:52 - error TS2307: Cannot find module './google/protobuf/wrappers'.
> 
>     5 import { StringValue, Int32Value, BoolValue } from './google/protobuf/wrappers';
>                                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~_

My exact procedure is:
- Clone
- `yarn install` (this fails due to `pbjs` not running)
- `./pbjs,.sh`
- `yarn install` (gets much farther but fails in tests)

**Comment by stephenh** [comment]
Hey! Sorry, I almost lost track of this. You are right, I was missing some steps. I should do some sort of CI setup to make sure these always build/pass on a fresh check out.

I checked in those missing files + added a small update to the readme; can you see if it works for now? Thanks!

**Comment by stephenh** [comment]
Pretty sure this is resolved now, so closing out.
