### ISSUE TITLE
--ts_proto_out: protoc-gen-ts_proto: The system cannot find the file specified

### ISSUE THREAD

**Issue by Icyfirefists** [stephenh/ts-proto#153]
Hello, I am having quite alot of trouble getting this plugin to work for me.

When I run this line below:

`protoc --plugin=protoc-gen-ts_proto=.\node_modules\.bin\protoc-gen-ts_proto.cmd --ts_proto_out=. ./test.proto
`

I am returned with the error: The system cannot find the file specified. 

I do not know if this plugin wants a very very VERY specific file path that goes from the source of the system or whatever but it is holding me back from generating a single typescript file.

Please help if you can.

I should note, any slight alterations to the path name usually result in another error: "Missing input file". I am also aware of the `--proto_path=` addition but this usually returns to the first error I mentioned. It is as if once I give an actual file for input, it proclaims the path is bad, but it makes no sense. Unless there is some underlying reason why paths do not work as expected.

**Comment by stephenh** [comment]
The `protoc` command line program can be hard to get right, especially since you're on Windows. Maybe try `test.proto` or `.\test.proto` because you're on Windows. Otherwise no I can't really help b/c this is not an issue with the ts-proto plugin and instead just a `protoc` setup/configuration issue.

**Comment by lili2012** [comment]
`C:\Users\username\Downloads\protoc-30.0-rc-2-win64\bin\protoc.exe -I='./protobuf' --plugin=protoc-gen-ts_proto=C:/Users/username/Desktop/playwrighttest/report2/webcad/frontend/node_modules/.bin/protoc-gen-ts_proto.cmd    --ts_proto_out=./frontend/  db.proto`
`--plugin=protoc-gen-ts_proto=` should follow absolute path, As https://github.com/stephenh/ts-proto/issues/21#issuecomment-575135727 suggested.
you could write all path absolute, after success. change to relative path one by one if you like shorter command.
