### ISSUE TITLE
Do not ignore options when using NestJS

### ISSUE THREAD

**Issue by mo4islona** [stephenh/ts-proto#165]
`useDate` and `returnObservable` are depending from `nestJs` option.It will more flexible and obvious not to skip them if they are set explicitly. For example, we override some default methods (or grpc wrappers) in NestJS so last lib releases unfortunately broke our typings

**Desired behaviour:**

`nestJs=true`
Use Timestamp.
Return Observable

 `nestJs=true & useDate=true`
Use Date instead of Timestamp.

`nestJs=true & returnObservable=false`
Return Promises only for unary calls like it is not in a NestJS

**Comment by jtag05** [comment]
@stephenh are there any plans to handle these scenarios?

**Comment by stephenh** [comment]
@jtag05 This is not high on my personal todo list but I'd accept PRs.

**Comment by stephenh** [comment]
@jtag05 and @mo4islona the options handling recently got refactored and I'm ~80% sure this was fixed as part of that. I'm going to optimistic close this as closed/fixed, but let me know if not? Thanks!

**Comment by jtag05** [comment]
@stephenh can confirm the output type for Timestamp is now `Date | undefined` thanks so much!
