### ISSUE TITLE
Correct falsy values are stripped by fromJSON and fromPartial

### ISSUE THREAD

**Issue by antogyn** [stephenh/ts-proto#17]
Hey,

Because of these lines :

https://github.com/stephenh/ts-proto/blob/8ba50d9618b7589dbcb77e3a567f987ab01874fb/src/main.ts#L523

https://github.com/stephenh/ts-proto/blob/8ba50d9618b7589dbcb77e3a567f987ab01874fb/src/main.ts#L616

falsy values (e.g. `0` from enums) are stripped by `fromJSON` and `fromPartial`.

My suggestion would be:

```ts
func = func.beginControlFlow('if (object.%L) != null', fieldName)
```

**Comment by stephenh** [comment]
@antogyn thanks for the report! This should be fixed in v1.6.0; let me know if not.
