### ISSUE TITLE
Option to use Maps instead of objects for proto map types

### ISSUE THREAD

**Issue by coreywoodfield** [stephenh/ts-proto#173]
Is there a particular reason that protobuf `map`s are represented as plain old objects on the typescript side, rather than javascript `Map`s? I generally prefer to work with `Map`s rather than raw objects, so it'd be nice if there were an option to use `Map`s instead

**Comment by stephenh** [comment]
Good question, but yes, one of the core principles of the ts-proto approach is that messages should be "just data" / just POJOs and not classes. This makes creating / massaging / consuming data more idiomatic TS/JS b/c you can use destructures/object spread/etc.

So, given protobuf maps are part of messages, they fall into the "just a POJO / object literal" approach.
