### ISSUE TITLE
Separate option for generating fromPartial method

### ISSUE THREAD

**Issue by coreywoodfield** [stephenh/ts-proto#175]
Currently the `outputJsonMethods` option determines whether the `fromJSON`, `toJSON` _and_ `fromPartial` methods are generated. Given how each of these methods work, I would like to have the `fromPartial` method, but not the `fromJSON` or `toJSON` methods. It'd be nice if there were an option to generate `fromPartial` without generating `fromJSON` and `toJSON`.

Alternatively, it'd be nice if there were a separate flag for generating the json methods using `foo['bar']` syntax instead of `foo.bar`. We run all our javascript through a minifier, so the `foo.bar` accesses wouldn't work for parsing actual json after being minified (as it would end up being something like `f.b`), but the `foo['bar']` syntax would (since the string key would get preserved through minification)

**Comment by stephenh** [comment]
This has been implemented in some recent-ish release. :-)
