### ISSUE TITLE
Experience with Timestamp (nestjs) over grpc for Dates ?

### ISSUE THREAD

**Issue by iangregsondev** [stephenh/ts-proto#179]
Hi everyone,

First time I am using Timestamp over gRPC, does anyone have any experience with this for Dates ?

I am using NestJs and there doesn't seem to be. a lot of docs on it, probably due to it using the gRPC library underneath.

I created a timestamp  in a proto and noticed ts-proto created a Timestamp type with types of "numbers" but after looking at the value being sent over the wire it seems that it is using the "Long" library by default - or I am assuming as I am looking at the value on the client-side and it is {low:xxxx, high:xxx, unsigned:boolean|}

So I changed ts-proto by passing

```
--ts_proto_opt=forceLong=long
```

Now I get a timestamp with a Long value for the seconds and number for the nanos.

I was wondering what the best way of sending this over the wire as the way I am doing it  I seem to be getting a negative number.

I am using a quick function I wrote (Am I re-inventing the wheel here ? does ts-proto create anything like this when run in the nestjs context ?)

```
  private toTimestamp(date: Date): Timestamp {
    const time = date.getTime()
    const long = Long.fromNumber(time, true)

    const timestamp: Timestamp = {
      seconds: long,
      nanos: 0,
    }
    return timestamp
  }
```

If anybody has any insight on the above it would really help.

After thinking about it a bit longer I could just send Dates over the wire as strings using toISOString of the date type :-)

But the above is annoying me - that I don't fully understand the timestamp :-)

Any ideas ?

The idea would be to send over a value the server (encoding it as a Timestamp) and then on the client decoding the Timestamp into a date object (or any other number :-) )

I did do a quick output of hte values I got from getTime and the values that the Long had created - this is why I am confused

```
here is the gettime 1608764064000

converted! {
  seconds: Long { low: -1848672000, high: 374, unsigned: true },
  nanos: 0
}
```

**Comment by iangregsondev** [comment]
I figured this out, its configurable in nest by passing options to the grpc loader.

Anyway, to make my life easier - I am passing a string over the wire now.

**Comment by stephenh** [comment]
@iangregsondev hey, glad you figured it out; sorry for not being able to help.

>  its configurable in nest by passing options to the grpc loader.

Can you share / link to how you did this? I'd be curious to know. Thanks!

**Comment by iangregsondev** [comment]
Hi @stephenh ,

Actually in the end I am just using a string BUT this may be useful also.

You can control a lot of options, for example how NestJS would send Longs (be it a string or using the Long Library etc)

here is some of my code - I am using the loader options
i.e.

```
              loader: {
                arrays: true,
              },
```

here's a larger abstract.


```
    ClientsModule.registerAsync([
      {
        name: DATA_SERVICES_CLIENT,
        useFactory: async (configService: ConfigService): Promise<GrpcOptions> => {
          return {
            transport: Transport.GRPC,
            options: {
              url: configService.endpointDataServices,
              package: [MAIN_NET_DATA_SERVICE_PACKAGE_NAME, STN_DATA_SERVICE_PACKAGE_NAME],
              loader: {
                arrays: true,
              },
```

There are quite a few things you can pass and its all documented here

https://github.com/grpc/grpc-node/blob/master/packages/proto-loader/README.md

I am using arrays:true as this was another issue that is fixed. For example, if an array has a zero length it would arrive as undefined. With this set to true it arrives as an empty array which is way better.

Back to the original comment thought with regards to the LONG library, you will find that at the link above but I am pasting it here for clairty

![image](https://user-images.githubusercontent.com/2370364/103479517-79620200-4dce-11eb-9b87-61f6e623a31a.png)

Hope that helps.

Thanks.

**Comment by stephenh** [comment]
Oh cool, I was expecting to need some nestjs-specific configuration, but they just defer to the grpc-node package; I didn't realize that. Thanks for the write up and links!
