### ISSUE TITLE
Runtime error with ES modules

### ISSUE THREAD

**Issue by jonaskello** [stephenh/ts-proto#181]
My code where I put the generated output from ts-proto is using ES modules and has `"type": "module"` set in package.json. Node >=14 has direct support for importing with `import` instead of `require` so in tsconfig.json I use `"module": "ESNext"`.

Now I run into trouble because the generated code imports protobufjs like this:

```
import { Writer, Reader } from "protobufjs/minimal";
```` 

This compiles fine with `tsc` using `"module": "ESNext"` but since the compiled code does not replace import with require I get this error in run-time:

```
import { Writer, Reader } from "protobufjs/minimal";
                 ^^^^^^
SyntaxError: Named export 'Reader' not found. The requested module 'protobufjs/minimal' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'protobufjs/minimal';
const { Writer, Reader } = pkg;

    at ModuleJob._instantiate (internal/modules/esm/module_job.js:104:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:149:5)
    at async Loader.import (internal/modules/esm/loader.js:166:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
```

As the error message states, it works OK if you do this instead:

```ts
import m from "protobufjs/minimal";
// ...other code
decode(input: Uint8Array | m.Reader, length?: number): CalculateRequest {
// ...other code
encode(message: CalculateRequest, writer: m.Writer = m.Writer.create()): m.Writer {
```

So I made some sed scripts to fix it:

```json
{
    "proto:fix": "run-s proto:fix1 proto:fix2 proto:fix3 proto:fix4",
    "proto:fix1": "find $npm_package_config_proto_out_dir -type f -name '*.ts' -print0 | xargs -0 sed -i 's/new Reader(input)/new m.Reader(input)/g'",
    "proto:fix2": "find $npm_package_config_proto_out_dir -type f -name '*.ts' -print0 | xargs -0 sed -i 's/decode(input: Uint8Array | Reader,/decode(input: Uint8Array | m.Reader,/g'",
    "proto:fix3": "find $npm_package_config_proto_out_dir -type f -name '*.ts' -print0 | xargs -0 sed -i 's/import { Writer, Reader } from \\\"protobufjs\\/minimal\\\";/import m from \\\"protobufjs\\/minimal\\\";/g'",
    "proto:fix4": "find $npm_package_config_proto_out_dir -type f -name '*.ts' -print0 | xargs -0 sed -i 's/writer: Writer = Writer.create()): Writer/writer: m.Writer = m.Writer.create()): m.Writer/g'",
}
```

This should really be fixed upstream in protobufjs, see [this issue](https://github.com/protobufjs/protobuf.js/issues/1230). However not much seems to happen there so I was wondering if it would be possible for ts-proto to adjust its output to make it compatible with current protobufjs by using the default import as above?

**Comment by jonaskello** [comment]
Many commonjs based packages support named imports when being imported from a module based package. Unfortunately protobufjs is not one of them. This [blog post](https://simonplend.com/node-js-now-supports-named-imports-from-commonjs-modules-but-what-does-that-mean/) has some more details.

I'm don't really like default exports but I think using the default export like above would support all cases.

**Comment by stephenh** [comment]
Hm, well shoot. Thanks for the links. And yeah that makes sense as both the problem and solution.

I was thinking it'd be nice if the codegen library could just handle this, and so I played around with that feature in ts-poet and have something kinda cool, where we can give it a list of "these are actually cjs modules" and it will rewrite any named imports into `_m.Symbol`:

```typescript
    // codegen template/generator still thinks its doing named imports
    const b = code`const types = [
      ${imp('Foo@foo')},
      ${imp('Bar@bar')},
      ${imp('Zaz@zaz')},
    ];`;
    // but when actually building the output, we tell which modules are CJS
    expect(await b.toStringWithImports({ forceDefaultImport: ['foo', 'bar'] })).toMatchInlineSnapshot(`
      "import { Zaz } from 'zaz';
      import _m0 from 'foo';
      import _m1 from 'bar';
      const types = [_m0.Foo, _m1.Bar, Zaz];
      "
    `);
```

The wrinkle is that ts-proto is still using the 2.x version of the ts-poet library, and I've not sunk the effort into porting it over to the 3.x/4.x version of ts-poet, b/c its an egregiously large breaking change (but worth it once we're on the other side).

So, dunno, that doesn't help you immediately, but yeah I get the problem. With the ts-poet feature, this is now like ~10-lines-of-code-for-a-config-flag away ... modulo that whole upgrade to ts-poet 4.x wrinkle.

**Comment by jonaskello** [comment]
Ah, I guess this will have to wait then until ts-poet is upgraded in this project. I'll leave it open for now.

**Comment by stephenh** [comment]
Okay, I pushed out `v1.46.0` that adds a `esModuleInterop` flag that uses the `import m from protobuf/minimal` syntax.

Can you see if that works? Thanks!

**Comment by jonaskello** [comment]
Yes it works now :-) However I cannot really upgrade because I ran into #191 when upgrading. However if I manually fix that issue for the generated code it works.
