### ISSUE TITLE
Deprecated properties in proto should be marked as deprecated in JSDoc comments 

### ISSUE THREAD

**Issue by ShakedH** [stephenh/ts-proto#183]
Marking a field as deprecated is [supported in proto](https://developers.google.com/protocol-buffers/docs/proto#options).

According to the docs, when generating Java code from the proto files, the property is marked with `@Deprecated` annotaion.

When generating Typescript code, the field should be marked as deprecated in [JSDoc](https://jsdoc.app/tags-deprecated.html)

**Comment by stephenh** [comment]
Fixed in v1.42.0.
