### ISSUE TITLE
Latest version from npm install ts-proto is not bundled correctly

### ISSUE THREAD

**Issue by and5555** [stephenh/ts-proto#196]
The src and build directory do not match in the latest version. When I npm install ts-proto and try to use --ts_proto_opt=exportCommonSymbols=false, it does not work. Digging into the code, it appears that this is because the feature is available in src but the build directory does not have the logic to handle it (see main.ts).

**Comment by stephenh** [comment]
Oh shoot, that's embarrassing. I have CI running tests but not the actual publish and must have gotten lazy. Can you try v1.51.0?

Thanks for reporting it!

**Comment by stephenh** [comment]
@and5555 pretty sure this is fixed, let me know if not.

**Comment by and5555** [comment]
Sorry for the delay. Yes; it's fixed now. Thanks.
