### ISSUE TITLE
[Feature request] Make all "message" properties optional 

### ISSUE THREAD

**Issue by tomasweigenast** [stephenh/ts-proto#197]
Since proto3 syntax set all messages as optional, it can be a good idea if you a flag to implement that behavior. 
For example:
```protobuf
message Example {
    string id = 1;
    repeated Second this_should_be_optional = 2;

   message Second {
          double value = 1;
    }
}
```

**Comment by oyvindwe** [comment]
Isn't this supported with `useOptionals=true`/`useOptionals=messages`?

**Comment by stephenh** [comment]
Ah man, "January 2021" shoot, sorry @tomasweigenast , but I believe @oyvindwe is right, so I'm going to close this issue out. Thanks!
