### ISSUE TITLE
Enum default value is 0 even with stringEnums=true

### ISSUE THREAD

**Issue by mharsat** [stephenh/ts-proto#198]
With the `stringEnums=true` config, the default value for an enum should be its 0th string value. Instead the default value set in `fromJSON` & `fromPartial` is 0, causing a type error.
``` tsx
export const Node = {
  fromJSON(object: any): Node {
    const message = { ...baseNode } as Node;
    if (object.type !== undefined && object.type !== null) {
      message.type = node_TypeFromJSON(object.type);
    } else {
      message.type = 0;
    }
}
```
Since `object.type` is a `string` we get an error in the else clause
```
Type '0' is not assignable to type 'Node_Type'.ts(2322)
```

**Comment by mharsat** [comment]
@stephenh can you review this [PR](https://github.com/stephenh/ts-proto/pull/199)?

**Comment by stephenh** [comment]
Yep, I tweaked a few things to include a repro of the bug, and then release the fix in v1.51.0. Thanks!

**Comment by stephenh** [comment]
Er, v1.52.0. :-)

**Comment by mharsat** [comment]
Thanks for the quick release!
