### ISSUE TITLE
Support to generate field names "as-is" instead of converting to camelCase

### ISSUE THREAD

**Issue by SchroederChris** [stephenh/ts-proto#20]
Currently, the original field names (as defined in a .proto file) are converted to camelCase for the generated typescript interfaces. It would be nice if there was an option to keep the original names (e.g. in snake_case) instead.

**Comment by stephenh** [comment]
@SchroederChris yep, I think that makes sense, just hadn't included it yet b/c we'd personally not needed it. Want to submit a PR for this?

There is already support for a "context" parameter, i.e.:

```
  const options: Options = { useContext: false };
  if (parameter && parameter.includes('context=true')) {
    options.useContext = true;
  }
```

So should be pretty easy to reuse that approach to change `snakeToCamel(name)` into `maybeSnakeToCamel(opts, name)`.

**Comment by SchroederChris** [comment]
@stephenh I just created pull request #22. That would also be the final change so that we can use your version again instead of our fork.

**Comment by stephenh** [comment]
Great, thanks! Added a sanity check of running `ts-proto` with that option and a small test to make sure there are no compile errors, and pushed out as v1.8.0.

**Comment by SchroederChris** [comment]
Perfect, thank you!
