### ISSUE TITLE
DeepPartial is incorrectly distributed between files

### ISSUE THREAD

**Issue by Raiondesu** [stephenh/ts-proto#209]
### Problem

If a service and a model (used by the service) with optional values are placed into separate files, ts-proto generates a `DeepPartial` util type and wraps the model into it, assuming that it exists in the file.

It means that if a model with optional fields is defined like this:
```proto
// model.proto
syntax = "proto3";

import "google/protobuf/wrappers.proto";

message RequestModel {
  google.protobuf.StringValue foo = 1;

  google.protobuf.StringValue bar = 2;
}

message Empty {}
```

and used like this:
```proto
// service.proto
syntax = "proto3";

import "model.proto";

service Service {
  rpc request (RequestModel) returns (Empty);
}
```

the output will be the following:
```ts
// model.ts

// other contents...

export interface RequestModel {
  foo?: string;
  bar?: string;
}

// other contents...

// This type is declared, but not used anywhere throughout the entire file
export type DeepPartial = /* implementation of deep partial */;
```

```ts
// service.ts
// Note the lack of `DeepPartial` in the import
import { RequestModel, Empty } from './model';

// other contents...

interface ServiceClient {
  // "Cannot find name 'DeepPartial'"
  // Because it wasn't imported
  request(request: DeepPartial<RequestModel>, metadata?: grpc.MetaData): Promise<Empty>;
}

// other contents...
// No DeepPartial declaration here
// ts-proto assumes that if it's used, then it must be declared
```
It seems like the declaration of DeepPartial needs to at least be in the file it's actually used in.

Moreover, why even use DeepPartial here, if all of the optional properties are already optional?

### Versions

This bug seems to be absent in 1.35, but present in 1.55

### Used flags

```
env=browser
useOptionals=true
oneof=unions
outputClientImpl=grpc-web
returnObservable=true
esModuleInterop=true
```

**Comment by stephenh** [comment]
> It seems like the declaration of DeepPartial needs to at least be in the file it's actually used in.

Ah yep, this should be fixed in v1.59.0. Thanks for the bug report.

> Moreover, why even use DeepPartial here, if all of the optional properties are already optional?

ts-proto could do a smart check along the lines of "if all properties are optional" before wrapping params in `DeepPartial`, but its simpler to just always do it. Plus checking "all properties are optional" deeply (i.e. for your fields' fields) would be more tedious. So I don't think it hurts/is preferable to leave as is.
