### ISSUE TITLE
Omit scalar fields with default value

### ISSUE THREAD

**Issue by webmaster128** [stephenh/ts-proto#213]
According to the proto3 Language Guide, [default values should be omitted](https://developers.google.com/protocol-buffers/docs/proto3#default) during encoding:

> Also note that if a scalar message field is set to its default, the value will not be serialized on the wire.

This behaviour is implemented in a variety of protobuf encoders and it would be great to have it here as well.

The encoder from code generated by protobuf.js looks like this:

```ts
SignDoc.encode = function encode(m, w) {
    if (!w) w = $Writer.create();
    if (m.bodyBytes != null && Object.hasOwnProperty.call(m, "bodyBytes"))
    w.uint32(10).bytes(m.bodyBytes);
    if (m.authInfoBytes != null && Object.hasOwnProperty.call(m, "authInfoBytes"))
    w.uint32(18).bytes(m.authInfoBytes);
    if (m.chainId != null && Object.hasOwnProperty.call(m, "chainId")) w.uint32(26).string(m.chainId);
    if (m.accountNumber != null && Object.hasOwnProperty.call(m, "accountNumber"))
    w.uint32(32).uint64(m.accountNumber);
    return w;
};
```

This does not conform to the spec as well, but allows applications to implement the ommiting themselves.

After the migration to ts-proto the same message type is encoded like this:

```ts
export const SignDoc = {
  encode(message: SignDoc, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    writer.uint32(10).bytes(message.bodyBytes);
    writer.uint32(18).bytes(message.authInfoBytes);
    writer.uint32(26).string(message.chainId);
    writer.uint32(32).uint64(message.accountNumber);
    return writer;
  },

  // ...
}
```

In contrast to the previous version, we don't have `| null | undefined` types in the fields anymore, which is good. But for scalar values we can and should check for the default values.

- `double`/`float`/`int32`/`int64`/`uint32`/`uint64`/`sint32`/`sint64`/`fixed32`/`fixed64`/`sfixed32`/`sfixed64`: 0
- `bool`: false
- `string`: ""
- `bytes`: 0-length

**Comment by stephenh** [comment]
Yep, this sgtm, I just haven't historically cared about this enough to implement (since it was optional). A PR would be great.

**Comment by webmaster128** [comment]
Thank you for the evaluation @stephenh. [In our use case](https://github.com/cosmos/cosmos-sdk/blob/master/docs/architecture/adr-027-deterministic-protobuf-serialization.md) [we](https://github.com/cosmos/cosmjs) care a lot about this particular aspect and are happy to work out a PR for it in the near future.
