### ISSUE TITLE
Object.create name collision with actual types.

### ISSUE THREAD

**Issue by Vilsol** [stephenh/ts-proto#216]
If you have a message/enum with the name `Object` it collides with the usage of `Object.create` in generated JSON functions.

This issue was introduced in 136cd28e5d2e0e708d0cc150d64d890c7dfcbd37

The only workaround I am aware of is to use `global.Object` instead.

**Comment by stephenh** [comment]
Ha, a message name of `Object`? I didn't think of that, but I think we can use `globalThis.Object.create` to avoid the collision (I'd already ran into this with someone using a message name of `Error` and so `throw Error` breaking).

This should be fixed in v1.63.0.

**Comment by Vilsol** [comment]
@stephenh Looks like this actually introduces another issue. The function you use to grab a valid `globalThis` contains a reference to `Error`. If the file contains an object called `Error` it cannot compile.

Assuming that it's unable to detect any global instances, it's probably safer as well to not use the Error object as it may not even exist, so you could just use `throw "Unable to locate global object"` which would throw a string error.

**Comment by stephenh** [comment]
Ah yeah, good idea re throwing the string. I've released that as v1.65.0.
