### ISSUE TITLE
Compilation of ts-proto-descriptor fails when using esModuleInterop tsc flag

### ISSUE THREAD

**Issue by Vilsol** [stephenh/ts-proto#217]
When using the tsc `esModuleInterop` flag, compilation of ts-proto-descriptor fails with the following error:

```js
node_modules/ts-proto-descriptors/google/protobuf/descriptor.ts:4528:5 - error TS2367: This condition will always return 'true' since the types 'Constructor<Long>' and '{ default: LongConstructor; prototype: Long; MAX_UNSIGNED_VALUE: Long; MAX_VALUE: Long; MIN_VALUE: Long; NEG_ONE: Long; ONE: Long; ... 11 more ...; fromValue(val: string | ... 2 more ... | { ...; }): Long; }' have no overlap.

4528 if (util.Long !== Long) {
```

A temporary workaround is to label the statement to be ignored by typescript:
```js
// @ts-ignore
```

**Comment by stephenh** [comment]
Well this is really disappointing...

I might end up needing to publish two different `ts-proto-descriptors` to npm; one for esModuleInterop false and one for esModuleInterop true...

It might be a long-shot, but would be interesting if long.js would just move over to ESM. We'll see what they say:

https://github.com/dcodeIO/long.js/issues/96

**Comment by stephenh** [comment]
Fwiw no response from long.js on the ESM issue; fwiw the long.js library is so small, we could just work it, and make/publish a `long-esm` fork on npm, and have ts-proto-generated output use that.

I'm not going to prioritize personally working on that now, but I think that's how I'd move forward with this.

**Comment by shravanshetty1** [comment]
Any workaround for this, cannot use long library during runtime with esModuleInterop

**Comment by stephenh** [comment]
Hm, @shravanshetty1 and @protango I'm pretty sure my intent of `ts-proto-descriptor` was to use it internally just within the `ts-proto` plugin itself, for decoding/encoding the responses from the `protoc` compiler.

How are you using `ts-proto-descriptors`? For writing your own protoc plugins?

**Comment by shravanshetty1** [comment]
@stephenh bundling the generated code with some custom logic and using it as a library in the browser

**Comment by stephenh** [comment]
@shravanshetty1 unless you're _specifically_ using `ts-proto-descriptor` directly, you should be able to pass `--ts_proto_opt=esModuleInterop` and it will change on long is imported within the `ts-proto` generated code.

**Comment by fenos** [comment]
@stephenh I'm using `ts-proto-descriptor` directly as a library, any workaround for this?

I'm getting the same:

```
node_modules/ts-proto-descriptors/google/protobuf/descriptor.ts:4526:5 - error TS2367: This condition will always return 'true' since the types 'Constructor<Long>' and '{ default: LongConstructor;
prototype: Long; MAX_UNSIGNED_VALUE: Long; MAX_VALUE: Long; MIN_VALUE: Long; NEG_ONE: Long; ONE: Long; ... 11 more ...; fromValue(val: string | ... 2 more ... | { ...; }): Long; }' have no overlap.

4526 if (util.Long !== Long) {
         ~~~~~~~~~~~~~~~~~~
```

**Comment by stephenh** [comment]
@fenos earlier today I recently `ts-proto-descriptor`'s 1.3.0 which has @protango 's PR to ship the compiled JS code, instead of the TS code. That should fix your issue, can you try that?

**Comment by fenos** [comment]
@stephenh thanks a lot for the quick reply!
I've just updated to 1.3.0 but unfortunately I still get the same issue

Please, let me know what i else i can try 👍

**Comment by stephenh** [comment]
Hm, @tenos try 1.3.1, I added a `types` entry to `package.json` and also excluded the `.*ts` files from the tar.gz. It should be only JS + `.d.ts` files now.

**Comment by fenos** [comment]
@stephenh legend!!! It works!!!!

**Comment by stephenh** [comment]
Great, going to close this out. Thanks @fenos for verifying and @protango for the fix!

**Comment by gotjoshua** [comment]
long is now ESM
https://github.com/dcodeIO/long.js/issues/96#issuecomment-953556502
