### ISSUE TITLE
useDate=false still outputs Date

### ISSUE THREAD

**Issue by mharsat** [stephenh/ts-proto#222]
Hey,
When setting `useDate=false` the `fromJSON` method converts a `Timestamp` field input into a `google.protobuf.Timestamp`, however the `toJSON` method still keeps converting a `Timestamp` field to `Date`.
The expected behavior is that when `useDate=false` is set, Timestamp fields would work without `Date` at all, with the normal methods created from `google/protobuf/timestamp`.
Maybe this is a misunderstanding and this is intentional?
It forces me to workaround with a local copy of Google's `timestamp` instead of importing it from `google.protobuf.timestamp`.

**Comment by mharsat** [comment]
@stephenh can you comment on this? Using `useDate=false` should basically create JSON methods that are purely based on `google/protobuf/timestamp.proto` right? Can this be addressed?

**Comment by jessebutterfield** [comment]
If you want to share an example of the code that is incorrect, I'd be happy to take a look, but I think that code is just using Date as an intermediate step to produce the ISO formatted string. According to https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/Timestamp, the json form of timestamp is always the ISO formatted string. The useDate behavior just controls the types of the typescript interfaces.

**Comment by stephenh** [comment]
Yeah, sorry for the delayed response, but @jessebutterfield is right, the `useDate=false` does turn of `Date`-the-type in the message fields, and uses `Timestamp` all the time; however we still assume that the JSON-spec should be followed, and send `Timestamp`s over the wire as ISO formatted strings.

So, yeah, in theory/AFAIU we're doing the right thing here. 

Do you have a better articulation for why this is not good? I.e. are you sending the `toJSON`'d data to a library/destination that doesn't support the `Timestamp`-is-ISO-string behavior/spec?

**Comment by mharsat** [comment]
Hey, thanks for your answer. I missed the point where `Timestamp`'s specification states that it should be treated as `Date` in JS and saved as ISO string in JSON.
I'll adapt my code to comply with these formats 👍🏼
