### ISSUE TITLE
Using proto Timestamp creates TS2367 error

### ISSUE THREAD

**Issue by ebakoba** [stephenh/ts-proto#224]
using Timestamp generates following code

```ts
if (util.Long !== Long) {
  util.Long = Long as any;
  configure();
}
```

Which in turn generates following error:
![image](https://user-images.githubusercontent.com/14753019/109301159-38bbbd80-7840-11eb-8b42-ca25af701215.png)

**Comment by stephenh** [comment]
See the readme note about `esModuleInterop`. This should probably be the default but its a breaking change so waiting for a major version bump.
