### ISSUE TITLE
Drop shared enum prefixes

### ISSUE THREAD

**Issue by fgblomqvist** [stephenh/ts-proto#228]
It's very common to write your protobuf enums like this:
```proto
enum Foo {
   FOO_BAR = 0;
   FOO_BAZ = 1;
}
```

It would be nice if there was an option (and later the default) to drop the shared prefix (if there is one), so that the TS enums can be generated like this:
```ts
enum Foo {
   BAR = 0;
   BAZ = 1;
}
```

**Comment by stephenh** [comment]
Ah sure, sounds good I guess. I haven't worked in a schema with that convention, but seems useful, especially for longer enum names.

I'd be open for yet-another-config-flag to turn that on if you'd like to submit a PR.

**Comment by fgblomqvist** [comment]
That convention is enforced by default by the Buf linter/style guide: https://docs.buf.build/style-guide/#enums
But yes okay, sounds good. We're currently evaluating using this library, so we'll look into making a PR if the choice falls on `ts-proto`. But regardless, excellent work so far, this looks like one of the best libs for proto TS codegen out there🥇

**Comment by jake-tourtech** [comment]
This would be a very welcome feature for .proto files that define multiple enums. The protobuf system disallows enums in the same scope that have values of the same name, which is what leads many to use the shared prefix approach. Otherwise you're met with this error:

```
Note that enum values use C++ scoping rules, meaning that enum values are siblings of their type, not children of it.  Therefore, "VALUE" must be unique within "package.service", not just within "EnumName".
```

TS does not make this enum scoping distinction, so being able to strip the shared enum prefixes would really clean up the generated code.

**Comment by doochik** [comment]
I guess using of custom enum option is more idiomatic solution for this case

```proto
extend google.protobuf.EnumOptions {
    string json_omit_prefix = 61210;
}

enum MyEnum {
    option (json_omit_prefix) = "STATUS_";

    STATUS_UNKNOWN = 0;
    STATUS_ACTIVE = 1;
    STATUS_ERROR = 2;
}
```

I can try to find out how to implement it

**Comment by stephenh** [comment]
Fwiw I wouldn't be against some sort of cute flag like `--ts-opt=dedupEnumPrefixes` which would, for each enum:

* Split a name like `AAA_BBB_CCC` on `_`
* Find the longest common `AAA_` or `AAA_BBB_` prefix across all values and
* Dropped that prefix from all enum values...

I agree @doochik that custom options would be more explicit, and custom option support in general would be great to have ... I've glanced at a few times but never had a strong enough reason to really figure it out/build it.

And, even with custom options, I personally kind of like "rule of thumb" conventions like a `dedupEnumPrefix` that would "just work" across all enums in a potentially large schema...

@fgblomqvist are you interested in working on a PR for such a flag?

**Comment by stephenh** [comment]
This got implemented as an `removeEnumPrefix` option ~awhile ago.
