### ISSUE TITLE
Compilation error when using buf

### ISSUE THREAD

**Issue by JeyoungKwon** [stephenh/ts-proto#229]
Buf has a [protoc drop-in replacement](https://docs.buf.build/generate-protoc) that my team uses with other plugins with no issue. Could be a buf thing, but maybe someone here has insight as to what could be going on?

Here is the minimal reproduction of the error:
Command:
```
OUT_DIR="./src/proto"
buf protoc \
    --plugin=../node_modules/ts-proto/protoc-gen-ts_proto \
    --ts_proto_out=${OUT_DIR} \ 
     test.proto
```

Input:
``` 
syntax="proto3";
package test;
message TestRequest {}
message TestResponse {}
service Test {
  rpc Test(TestRequest) returns (TestResponse) {}
}
```

Output:
```
--ts_proto_out: error
```

**Comment by stephenh** [comment]
Hey! I hadn't heard of `buf` before, that looks cool.

Yeah, I have no idea what the error is. :-) Let me know if you find a debug mode or something that gives us a better idea of whats going on.

**Comment by JeyoungKwon** [comment]
Problem solved it seems!: https://github.com/bufbuild/buf/issues/276 

Linking here for anybody who looks this up. Looks like the issue was internal to buf.
