### ISSUE TITLE
Support for generating TSDoc content from the message and field level comments in the Protobuf definition

### ISSUE THREAD

**Issue by dteirney** [stephenh/ts-proto#23]
Hello,

Has there been any thought around using the comments for the protobuf message and field definitions to generate TSDoc comments for the generated typescript?

We'd love to be able to have the field comments from the proto files available for devs within VS Code and other editors. Many IDEs and documentation generators support comments using the [TSDoc format](https://github.com/Microsoft/tsdoc).

Many of our proto definitions follow both [comment guidelines for Uber prototool](https://github.com/uber/prototool/blob/dev/style/README.md#documentation) and [Google Documentation AIP](https://aip.dev/192). It would be awesome for those comments to come along for the ride with the TS that's generated, similar to the comments that are generated with the [Google GAPIC typescript generator](https://github.com/googleapis/gapic-generator-typescript).

Thanks!
David

**Comment by stephenh** [comment]
@dteirney sure, that makes a lot of sense. The ts-poet code generator library that ts-proto uses supports outputting comments, I just hadn't bothered hooking that up yet. If you'd like to take a crack at it, that'd be great.

Most of the ts-poet `addFunction`/`addProperty` calls take builders that accept a "javaDoc" parameter for outputting comments, and the incoming CodeGenerationRequest (forget the exact name) protos from the protoc compiler should have `.comment`-type fields that are easily accessible.

(Somewhat of a small disclaimer, the latest ts-poet release, v3, doesn't use this same builder api anymore, so if you dig too much into ts-poet, just note that ts-proto is still on the v2 ts-poet api.)

I can probably sneak this in to at some point too.

**Comment by n3rdyme** [comment]
@dteirney see https://github.com/stephenh/ts-proto/pull/31

**Comment by stephenh** [comment]
This is merged to master and will go out in the next release, which will be next-day-ish or so. Going to go ahead and close. Thanks @n3rdyme ! That was actually more involved than I thought it was going to be, with the index-based/etc. encoding of the comments in the protobuf file.

**Comment by dteirney** [comment]
@n3rdyme thanks! Will test once the next release goes out.

**Comment by stephenh** [comment]
@dteirney version 1.11.0 is out with this change. :-)
