### ISSUE TITLE
[Feature Request] Decoding delimited messages

### ISSUE THREAD

**Issue by ChristianIvicevic** [stephenh/ts-proto#233]
I'd like to start a discussion since I am not sure whether my feature request is actually a reasonable scope for this library.

Since clients can receive fragmented data over a socket I had to implement a custom logic to handle framed messages that the server encodes using length-prefixes with the `google::protobuf::util::SerializeDelimitedToZeroCopyStream` method. Basically all packets sent over the wire receive a varint as a prefix that denotes the actual message length. My current prototype for handling this looks as follows:
```typescript
let client: Socket;
let buffer = Buffer.alloc(0);
let messageLength = Infinity;

client.on('data', data => {
  buffer = Buffer.concat([buffer, data]);
  if (messageLength === Infinity && buffer.length > 0) {
    try {
      messageLength = varint.decode(buffer);
      buffer = buffer.slice(varint.decode.bytes);
    } catch (e: unknown) {
      // RangeError from varint.decode indicated wrong encoding or incomplete data.
    }
  }
  if (buffer.length >= messageLength) {
    const encodedMessage = buffer.slice(0, messageLength);
    const message = WrappedPacket.decode(encodedMessage);
    // ...do something with message...
    buffer = buffer.slice(messageLength);
    messageLength = Infinity;
  }
});
```
It seems like the `protobufjs` code generator exposes methods for reading such delimited messages, but I cannot use the library since the generated Typescript typings include unsupported namespaces. Therefore I sticked to your library and was curious whether handling length-prefixed messages may be a good feature for it or should be an implementation detail that consumers define themselves.

**Comment by stephenh** [comment]
Hey, sure, good question.

As far as I understand, what you're describing is typically handled by higher-level protocols like grpc?

Assuming that's right, then, yeah, dunno like ts-proto does technically generate framework-specific code for say Twirp or GRPC or NestJS. So it's not out of the realm of possibility.

But given you're doing very low-level / custom / socket level stuff that I generally assume most users aren't/won't do, and instead use some existing higher-level protocol/library, yeah, seems unlikely to be a great fit for ts-proto.

Kinda depends on what you need though.

And, if anything, ts-proto I assert is pretty hackable, if you want to just maintain your own fork.

Just out of curiosity, is there a reason you're doing direct-socket-level handling? Disclaimer I'm not an expert on all of the approaches/solutions in the same other than the obvious ones like grpc (which I know have HTTP/2 couplings/complexities).

**Comment by ChristianIvicevic** [comment]
> Just out of curiosity, is there a reason you're doing direct-socket-level handling?

Yeah for some further clarification I can tell you what this is is about. My application server in written in C++ and communicating via TCP using protobuf for serialization. The client will be a browser application and since browsers don't have actual TCP socket connections I need a server in the middle that communicates via Websockets with the client and TCP sockets with the server.

At the moment I am still unsure where to handle framing (e.g. splitting packets in the middle server and send them unfragmented via HTTP or fragmented via the Websocket and reconcile it in the frontend), but no matter the details for my use case I need to handle delimiting messages anyway and thus I was curious whether it should be part of `ts-proto`.

**Comment by stephenh** [comment]
Hey, yeah, that seems pretty bespoke. I'm going to close for now, but will keep it in mind if more people ask for it.

**Comment by pauldraper** [comment]
This is a typical way of using protobufs, and these functions part of the C++ protobuf library:

```
parseDelimitedFrom
writeDelimitedTo
```

**Comment by stephenh** [comment]
@pauldraper ah interesting! As like per-message methods, i.e. `FooMessage.encodeDelimited(message)`? Or just general helper methods like a top-level `encodeDelimited(message)? Either way, happy to have a PR that adds with some sort of `delimitedMethods=true` option.

**Comment by pauldraper** [comment]
Yeah. In case it's useful to anyone here:

```ts
export async function* readFromStream<T>(
  iterator: AsyncIterable<ArrayBuffer>,
  messageType: MessageType<T>,
): AsyncIterable<T> {
  const it = iterator[Symbol.asyncIterator]();
  let buffer: ArrayBuffer = new Uint8Array(0);
  outer: while (true) {
    while (new Uint8Array(buffer).every((v) => 128 <= v)) {
      let next = await it.next();
      if (next.done) {
        if (buffer.byteLength) {
          throw new Error("Unexpected EOF");
        } else {
          break outer;
        }
      }
      buffer = concat([buffer, next.value]);
    }
    const reader = Reader.create(new Uint8Array(buffer));
    const length = reader.uint32();
    console.error(length);
    buffer = buffer.slice(reader.pos);
    while (buffer.byteLength < length) {
      let next = await it.next();
      if (next.done) {
        throw new Error("Unexpected EOF");
      }
      buffer = concat([buffer, next.value]);
    }
    yield messageType.decode(new Uint8Array(buffer), length);
    buffer = buffer.slice(length);
  }
}

export async function* writeToStream<T>(
  iterator: AsyncIterable<T>,
  messageType: MessageType<T>,
): AsyncIterable<ArrayBuffer> {
  for await (const message of iterator) {
    yield messageType.encode(message).ldelim().finish();
  }
}
```

**Comment by AlaaZorkane** [comment]
Any updates on this?

**Comment by AlaaZorkane** [comment]
Hey guys! Just letting you know that I opened a PR for this issue here: https://github.com/stephenh/ts-proto/pull/460
Please let me know if you have any feedback 🙏

**Comment by eba-ts** [comment]
Hi everyone. Feeling stupid a bit commenting in a closed task :) 
I tried three libraries and ts-proto ended up to be the most convenient one in my use case. 

However, we do use messages streaming https://developers.google.com/protocol-buffers/docs/techniques#streaming 

Thanks to this issue and the PR, it was quite easy to make it work - leveraging `protobufjs` though. Below is the pseudo-TS-code:
```
const reader = new protobufjs.Reader(data); //data is a response from API serving the protobuf stream
cycle with (reader.pos>= reader.len) is here {
    const length = reader.uint32();
    const decodedmessage : MyGeneratedType = MyGeneratedType.decode(reader, length);
}
```

**Comment by kmannislands** [comment]
I'm also interested in this feature. Happy to help push the PR along if there's interest.

In the meantime, I've grabbed some of the code from #460 to create a compatibility layer in my code base while switching from `protobufjs` class definitions to `ts-proto`. Perhaps it will be useful to readers in the interim.

```typescript
interface GeneratedProtoMessage<MsgType> {
    encode(message: MsgType, writer: Writer): Writer;

    decode(input: Reader | Uint8Array, length?: number): MsgType;
}

interface CompatibleProtoMessage<MsgType> extends GeneratedProtoMessage<MsgType> {
    encodeDelimited(message: MsgType, writer?: Writer): Writer;

    decodeDelimited(input: Reader | Uint8Array): MsgType;
}

/**
 * @see https://github.com/stephenh/ts-proto/pull/460
 */
export function addDelimitedMethods<MsgType>(
    messageDef: GeneratedProtoMessage<MsgType>
): CompatibleProtoMessage<MsgType> {
    return {
        ...messageDef,
        encodeDelimited(message: MsgType, writer: Writer = new Writer()): Writer {
            return messageDef.encode(message, writer.fork()).ldelim();
        },

        decodeDelimited(input: Reader | Uint8Array): MsgType {
            const reader = input instanceof Reader ? input : new Reader(input);
            const length = reader.uint32();
            return messageDef.decode(reader, length);
        },
    };
}
```

**Comment by stephenh** [comment]
Hi @kmannislands just glancing at the PR, I'm not sure why it stalled out--looks like tests were coming along, etc. :thinking: :shrug: But yep, if you'd like to pick it up, that'd be great! Thanks!
