### ISSUE TITLE
grpcStreamMethods empty so typescript complains and also won't compile.

### ISSUE THREAD

**Issue by iangregsondev** [stephenh/ts-proto#235]
Hi,

ERROR

```
TS7034: Variable 'grpcStreamMethods' implicitly has type 'any[]' in some locations where its type cannot be determined.
```

grpcStreamMethods in my case is empty as I don't have any. But the generated code outputs this information and the latest version of typescript complains. Adding an image (see below)

I could have course remove this info but its a generated file and will get re-generated again.

Is there anything available to stop this from happening? I have been AWOL on Golang :-) So returning I notice there are quite a few enhancements and maybe one I am missing to avoid the above problem.

Is there isn't anything at the moment I would think the easiest thing here would either to TYPE it as an array of strings OR not output the grpcStreamMethods.

I think typing it would be better and easier though.

![image](https://user-images.githubusercontent.com/2370364/110618065-a64be000-8196-11eb-86af-0d283455c93f.png)

here is the TYPE information added which seems to remove the issue.

![image](https://user-images.githubusercontent.com/2370364/110618735-502b6c80-8197-11eb-9be5-b0a98bd7cf34.png)

**Comment by stephenh** [comment]
Fixed in v1.73.0, thanks!
