### ISSUE TITLE
Snowpack / ESM module support

### ISSUE THREAD

**Issue by frederikhors** [stephenh/ts-proto#244]
I'm trying to use this amazing plugin with Snowpack (`npx create-snowpack-app svelte-snowpack --template @snowpack/app-template-minimal`).

I'm getting this error at runtime:

```
Uncaught SyntaxError: The requested module '../../_snowpack/pkg/protobufjs/minimal.js' does not provide an export named 'Reader'
```

Is there a way to fix this?

**Comment by stephenh** [comment]
Thanks for the report, I think this would need to be fixed in `protobufjs`:

https://github.com/protobufjs/protobuf.js/issues/1230

**Comment by jeremeevans** [comment]
> Thanks for the report, I think this would need to be fixed in `protobufjs`:
> 
> [protobufjs/protobuf.js#1230](https://github.com/protobufjs/protobuf.js/issues/1230)

I'm running into this, too. When I generate a client to use grpc/grpc-js:

`protoc --plugin=./node_modules/.bin/protoc-gen-ts_proto --ts_proto_opt=outputServices=grpc-js --ts_proto_out=./server/generated ./protos/*.proto -I./protos`

The generated ts has 

`import { util, configure, Writer, Reader } from "protobufjs/minimal";`

If it is imported as a whole, and de-structured, it works:

```
import pbm from "protobufjs/minimal";
const { util, configure, Writer, Reader } = pbm;
```

Maybe update the way it's imported?

**Comment by stephenh** [comment]
@jeremeevans huh, I was thinking "surely the code generation library we use (ts-poet) should have a cute way of dealing with this trivial rewrite", and turns out it does / I'd just forgotten about it:

https://github.com/stephenh/ts-poet/commit/8f4654c17eea546e80f7e19fe2090e35c5b7fd3e

And ts-proto already has a flag to enable it, i.e. `esModuleInterop`.

Can you try setting that to true? I.e. `--ts_proto_opt=esModuleInterop=true`.

**Comment by jeremeevans** [comment]
I found that option after digging around the issues some more. It does work for this. I'm thinking this should _maybe_ be the default behavior, as there are no guarantees that third-party libraries are exporting things in a way Node knows how to consume.

**Comment by stephenh** [comment]
Yeah, changing that default is on the todo list of breaking changes to make for a 2.0 release. I've added a note about ESM / snowpack / vite to the readme and will close this out. Thanks for confirming that worked.
