### ISSUE TITLE
grpc-node support

### ISSUE THREAD

**Issue by svsool** [stephenh/ts-proto#245]
Hi, thanks for this plugin!

Is there a plan to support [grpc-node](https://github.com/grpc/grpc-node) directly? It seems that grpc-web requires an additional web proxy and it would be great to avoid this complexity for our internal services.

Thank you!

**Comment by svsool** [comment]
Seems that repo tags also mention grpc-node support, but apparently it's not the case or requires additional setup than just grpc-node on its own.
 
![image](https://user-images.githubusercontent.com/1452141/111153171-468c7500-859a-11eb-8caf-78a476aaa5e0.png)

**Comment by stephenh** [comment]
@svsool hey, @aikoven just added supported for grpc-js clients and services; see the tests here:

https://github.com/stephenh/ts-proto/blob/main/integration/grpc-js/grpc-js-test.ts

And let us know how it goes. Thanks!

**Comment by svsool** [comment]
Thank you very much @stephenh! We will try it out!
