### ISSUE TITLE
using --ts_proto_opt=forceLong=string with google timestamp produces invalid Dates()

### ISSUE THREAD

**Issue by Psykar** [stephenh/ts-proto#248]
Generated code made this
```
function toTimestamp(date: Date): Timestamp {
  const seconds = (date.getTime() / 1_000).toString();
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}
```
followed by
```
Writer.prototype.uint64 = function write_uint64(value) {
    var bits = LongBits.from(value);
    return this._push(writeVarint64, bits.length(), bits);
};
```
the seconds = part keeps the fraction in the string.
but LongBits.From(...) expects sanitized input, so just deletes the decimal point, and you end up with a seconds that's (potentially MUCH) higher than it should be.

```
  let seconds: string | Code = 'date.getTime() / 1_000';
  let toNumberCode = 't.seconds';
  if (options.forceLong === LongOption.LONG) {
    toNumberCode = 't.seconds.toNumber()';
    seconds = code`${longs.numberToLong}(date.getTime() / 1_000)`;
  } else if (options.forceLong === LongOption.STRING) {
    toNumberCode = 'Number(t.seconds)';
    seconds = '(date.getTime() / 1_000).toString()';
  }
```

Needs to change to throw away the decimal part before calling .toString()

**Comment by stephenh** [comment]
Hey @Psykar thanks for the bug report; sounds like you understand the issue, can you submit a PR?

There is an integration test for forceLong=string here:

https://github.com/stephenh/ts-proto/tree/main/integration/simple-long-string

And you could copy/paste the Timestamp.proto from another test case into this one to make a repro for your fix.

Thanks!
