### ISSUE TITLE
Broken stringEnums option handling

### ISSUE THREAD

**Issue by ahumellihuk** [stephenh/ts-proto#249]
Commit https://github.com/stephenh/ts-proto/commit/7248f2768f1ce6c04800edabb0a2663eaf19cab0 breaks `stringEnums` option handling in that it will respect the option even in case when `outputEncodeMethods=true`, which should have been impossible as per the original implementation (https://github.com/stephenh/ts-proto/pull/146), resulting in invalid code generated: 
```
src/generated/api.ts:1620:31 - error TS2345: Argument of type 'import("/path/to/generated/code").Status' is not assignable to parameter of type 'number'.
  Type 'import("/path/to/generated/code").Status' is not assignable to type 'number'.

1620       writer.uint32(24).int32(message.status);
```

@stephenh you mention the same problem [here](https://github.com/stephenh/ts-proto/pull/38#pullrequestreview-374768413) I believe, in context of another PR.

**Comment by stephenh** [comment]
Thanks for the heads up @ahumellihuk ; rather than preventing this combination, I just went ahead and fixed #38. Thanks for the nudge!
