### ISSUE TITLE
Output for only-types test has unused runtime imports

### ISSUE THREAD

**Issue by eqyiel** [stephenh/ts-proto#256]
Here: 
- https://github.com/stephenh/ts-proto/blob/0380ea0bb82c8f1ab7734b9369bf96dd99a51bfe/integration/only-types/reservation.ts
- https://github.com/stephenh/ts-proto/commit/dd015292ba3dad93bbf96c0d479ab75e99bb615c

It seems to be since https://github.com/stephenh/ts-proto/pull/247, is it intentional?

**Comment by stephenh** [comment]
Thanks! You're right. This is fixed in the next release.
