### ISSUE TITLE
How to disable option addGrpcMetadata=true for grpc-web impl?

### ISSUE THREAD

**Issue by BatyrSeven** [stephenh/ts-proto#270]
I think there is no more possibility to disable `addGrpcMetadata=true` option if having option `outputClientImpl=grpc-web`. Probably, this issue was introduced in https://github.com/stephenh/ts-proto/pull/259

Reproduction:

ts-proto version: 1.79.1

proto:

```proto
service DemoService {
    rpc GetBasic (QueryById) returns (BasicInfo) {}
    rpc Insert (Demo) returns (Demo) {}
}
```

options:

```
protoc --plugin=node_modules/ts-proto/protoc-gen-ts_proto \
    --ts_proto_opt=outputClientImpl=grpc-web \
    --ts_proto_out=${OUT_DIR} \
    ./*.proto
```

output:

```ts
export interface DemoService {
  GetBasic(request: DeepPartial<QueryById>, metadata?: Metadata): Promise<BasicInfo>;
  Insert(request: DeepPartial<Demo>, metadata?: Metadata): Promise<Demo>;
}

export class DemoServiceClientImpl implements DemoService {
  private readonly rpc: Rpc;

  constructor(rpc: Rpc) {
    this.rpc = rpc;
  }

  GetBasic(request: DeepPartial<QueryById>, metadata?: grpc.Metadata): Promise<BasicInfo> {
    return this.rpc.unary(DemoServiceGetBasicDesc, QueryById.fromPartial(request), metadata);
  }

  Insert(request: DeepPartial<Demo>, metadata?: grpc.Metadata): Promise<Demo> {
    return this.rpc.unary(DemoServiceInsertDesc, Demo.fromPartial(request), metadata);
  }
}
```

The attempt to compile the output ts file results in the error:
`Type 'Metadata | undefined' is not assignable to type 'BrowserHeaders | undefined'.`

As you can see, we have `Metadata` from `grpc` in the `DemoService` interface and `grpc.Metadata` from `@improbable-eng/grpc-web` in the `DemoServiceClientImpl` class which causes compatibility issues.

Is there any way to disable option `addGrpcMetadata=true` for if the clientImpl is `grpc-web`?

**Comment by stephenh** [comment]
Can you just add `addGrpcMetadata=false` to the parameters, i.e. this test is passing:

```
  it('can disabled grpc metadata', () => {
    const options = optionsFromParameter('outputClientImpl=grpc-web,addGrpcMetadata=false');
    expect(options).toMatchObject({
      outputClientImpl: 'grpc-web',
      addGrpcMetadata: false,
    });
  });
```

It does sound like there is a larger issue here wrt a mismatch between `grpc` and `improbable-eng` types ... which, actually I do see that being reproduced locally, weird that didn't cause a test failure on release. I'll work on fixing that root issue as well.

**Comment by BatyrSeven** [comment]
@stephenh thank you for your quick response! However, adding `addGrpcMetadata=false` didn't work for me - it results in the same error.

**Comment by bryanmcgrane** [comment]
I'm experiencing the same issue on a fresh install.

**Comment by stephenh** [comment]
Ah okay, I found it; this bug was introduced accidentally during a refactored while fixing a related bug. :-) I've got a fix + test case in, and it will be out in the next release. Thanks!

**Comment by BatyrSeven** [comment]
Awesome, thanks!
