### ISSUE TITLE
Wrong generation when package not set

### ISSUE THREAD

**Issue by DK99** [stephenh/ts-proto#273]
The protobuf specs allow to not specify a package. Your generator assumes that a package is always defined.
e.g. there is this line of code in the grpc web generator `serviceName: "${fileDesc.package}.${serviceDesc.name}",` No matter the package it always puts a dot in front of the service name. This doen't work when dealing with an empty package name as the service name would be `.ExampleService`.

**Comment by stephenh** [comment]
Should be out in the next release, thanks!
