### ISSUE TITLE
Issues with decoding any buffers

### ISSUE THREAD

**Issue by iancharters** [stephenh/ts-proto#289]
We're trying to use the [Google error model](https://cloud.google.com/apis/design/errors) currently running into some issues. 
 In a status return, I'm struggling to decode the `details` field which is of type `repeated google.protobuf.Any`.

When I receive status in responses I get an error shape looking like this:
```
{
  code: 3,
  message: 'attestation errors',
  details: [
    {
      typeUrl: 'type.googleapis.com/google.rpc.BadRequest',
      value: <Buffer 0a 90 04 0a 12 63 6f 72 70 6f 72 61 74 65 53 74 72 75 63 74 75 72 65 12 f9 03 61 70 70 6c 69 63 61 74 69 6f 6e 20 2d 20 61 74 74 65 73 74 61 74 69 6f ... 82797 more bytes>
    }
  ]
}
```

When I attempt to decode this buffer, I get a mostly readable, but still slightly mangled string.  I'm expecting data in the shape of `google.rpc.BadRequest`.

I've tried using the generated toJSON and decode functions.  I've tried converting it manually.  It's always slightly mangled.  Is there something generated for me that I can use to correctly read these?

**Comment by stephenh** [comment]
Hey @iancharters , I've not really worked with `Any`s before, so am not surprised there are some kinks.

Fwiw I think @aikoven probably could be the most helpful here, iirc, b/c he's worked on a type registry feature that is related to handling `Any`s.

Other than that, I don't have any good suggestions other than working it down to a standalone repro in an `integration`/ test directory, maybe generate pbjs versions of the bindings (a few of our integration tests do that), and then compare/contract between ts-proto and pbjs to see where the decoding is going wrong.

**Comment by iancharters** [comment]
Got it.  Thanks.  I'll see if I can figure out a solution and share what I find.

**Comment by aikoven** [comment]
Do I understand correctly that `BadRequest.decode(details[0].value)` does not work? Does it throw? Or do you get corrupted data?

**Comment by iancharters** [comment]
🤦  I pull the protos from the service I'm talking to and generate ts in my service.  They weren't exposing error_details so I was trying to use `Status` and `Any` to decode.

This was very much a PEBKAC issue.  Resolved by adding error_details to that service so I can generate the correct decode functions on my end.  Thanks for your help, guys.

**Comment by stephenh** [comment]
@iancharters np, great you figured it out! Happy to another pleased ts-proto user. :-)
