### ISSUE TITLE
Generate source-file headers to disable linter issues with formatting, etc

### ISSUE THREAD

**Issue by n3rdyme** [stephenh/ts-proto#29]
Add the following headers to source file output:
```Javascript
// @ts-nocheck
/* eslint-disable */
```

This will prevent es-lint or tsc from generating unneeded warnings and build errors.

See the following PR change:
https://github.com/stephenh/ts-proto/pull/28/files#diff-9c712ef008f0c005b1e21d9c82dfa57bR13

**Comment by stephenh** [comment]
`ts-nocheck` disables type checking? That seems like a bad idea?

In theory the generated code is supposed to be clean enough to not have any warnings. What are you running in to?

**Comment by n3rdyme** [comment]
Issue resolved on master
