### ISSUE TITLE
Feature: Add an option to control the features of generated code

### ISSUE THREAD

**Issue by n3rdyme** [stephenh/ts-proto#30]
Specifically I need the ability to only generate the interfaces; however, it may be beneficial to only disable certain features. Adding the following options may be the easiest way to allow the flexibility:
```
export type Options = {
  ...
  serializers: boolean;
  toFromJson: boolean;
  serviceStub: boolean;
```

https://github.com/stephenh/ts-proto/pull/28/files#diff-8cfead41d88ad47d44509a8ab0a109adR52-R54

**Comment by stephenh** [comment]
Merged! Thanks!
