### ISSUE TITLE
a full example would be helpful

### ISSUE THREAD

**Issue by yoavmil** [stephenh/ts-proto#301]
It would be great if someone could post a full "hello, world!" client-server usage example, that consits of:
* protobuf files, including rpc service (both steam and non stream)
* node server
* node client
* the protoc command
* npm package, that shows which packages are needed

(right now I'm stuck on using the client service)

**Comment by dystopiandev** [comment]
That client part... I simply gave up at some point.

**Comment by viggin543** [comment]
https://github.com/stephenh/ts-proto/blob/main/integration/grpc-web/client-ts.ts

@yoavmil found this, kapara ;)
