### ISSUE TITLE
Unknown flag: --ts_proto_opt

### ISSUE THREAD

**Issue by ShubhamModi004** [stephenh/ts-proto#305]
Hi even after using a latest version of proto compiler, terminal throws an error.

**Comment by stephenh** [comment]
Please provide the full command line that you're running, and you're operating system, this is unlikely to be a bug and probably an error in your command.

**Comment by aniketbhatnagar** [comment]
@stephenh I am running into this as well with command:
```
protoc --plugin=./node_modules/.bin/protoc-gen-ts_proto --ts_proto_opt=esModuleInterop=true --ts_proto_out=src/generated ./spec/queue.proto
```

I am most likely doing something silly, but I dont know what!

Versions:
libprotoc 3.0.0
ts-proto 1.82.2

**Comment by stephenh** [comment]
@aniketbhatnagar As far as I can tell, your command looks right ... `protoc` can be annoyingly cryptic in getting the command set just right. Let us know if you figure it out? Sorry, and thanks!

**Comment by lucivaldoSnapcommerce** [comment]
I'm getting the same error with ts-proto 1.82.5 and libprotoc 3.17.3

My command  

```
protoc -I=proto/messages --plugin=protoc-gen-ts=./proto/node_modules/.bin/protoc-gen-ts_proto --ts_proto_opt=esModuleInterop=true,env=node --js_out=import_style=commonjs,binary:generated/js --ts_out=generated/ts ./proto/message.proto
```

**Comment by stephenh** [comment]
```
 --plugin=protoc-gen-ts=./proto/node_modules/.bin/protoc-gen-ts_proto 
```

You have `protoc-gen-ts=` intsead of `protoc-gen-ts_proto=`.

The part between `plugin=` and `=./proto...` determines the name of the "opt" flag that `protoc` will accept.

**Comment by lucivaldoSnapcommerce** [comment]
Yes, sorry about that. I noticed it and removed the plugin name and it worked, so now I have `--plugin=./proto/node_modules/.bin/protoc-gen-ts_proto` and it is working fine (with opts and all).

Thanks @stephenh!! For the help and the amazing plugin =)

**Comment by furstenheim-goodnotes** [comment]
If anybody stumbles into this, while using `plugin=protoc-gen-ts=..` then it works, but the name of the flag should be `ts_opt=` instead of `ts-proto_opt=`
