### ISSUE TITLE
lowerCaseServiceMethods option does not change client implementation

### ISSUE THREAD

**Issue by protango** [stephenh/ts-proto#310]
With the `--ts_proto_opt=lowerCaseServiceMethods=true` option set, the plugin will output the service interfaces with lower case method names, but the client implementations (which implement the interface) are not modified. This means the client implementation does not match the interface and it throws TypeScript errors.

For example:

Given this proto:
```proto
service MathService {
    rpc Add(MathServiceAddRequest) returns (MathServiceAddResponse) {}
    rpc Subtract(MathServiceSubtractRequest) returns (MathServiceSubtractResponse) {}
    rpc Multiply(MathServiceMultiplyRequest) returns (MathServiceMultiplyResponse) {}
    rpc Divide(MathServiceDivideRequest) returns (MathServiceDivideResponse) {}
}
```

`ts-proto` will generate:
```typescript
export interface MathService {
  add(request: MathServiceAddRequest): Promise<MathServiceAddResponse>;
  subtract(
    request: MathServiceSubtractRequest
  ): Promise<MathServiceSubtractResponse>;
  multiply(
    request: MathServiceMultiplyRequest
  ): Promise<MathServiceMultiplyResponse>;
  divide(request: MathServiceDivideRequest): Promise<MathServiceDivideResponse>;
}

export class MathServiceClientImpl implements MathService {
  private readonly rpc: Rpc;
  constructor(rpc: Rpc) {
    this.rpc = rpc;
    this.Add = this.Add.bind(this);
    this.Subtract = this.Subtract.bind(this);
    this.Multiply = this.Multiply.bind(this);
    this.Divide = this.Divide.bind(this);
  }
  Add(request: MathServiceAddRequest): Promise<MathServiceAddResponse> {
    const data = MathServiceAddRequest.encode(request).finish();
    const promise = this.rpc.request(
      "services.math.v1.MathService",
      "Add",
      data
    );
    return promise.then((data) =>
      MathServiceAddResponse.decode(new _m0.Reader(data))
    );
  }
  // Truncated ...
}
```

And you end up with typescript errors like this:
![Class 'MathServiceClientImpl' incorrectly implements interface 'MathService'.](https://user-images.githubusercontent.com/31492239/120725469-5d978f00-c519-11eb-9203-57f88ab2e6dc.png)

**Comment by stephenh** [comment]
Huh, I'm surprised that didn't get caught sooner. Although I think the PR that added the lower case support, the author wasn't using clients, so maybe that was it.

Would you like to submit a PR that adds the option checking logic around here:

https://github.com/stephenh/ts-proto/blob/84060e204d0e42688b8da85d434fe3d24788813b/src/generate-grpc-web.ts#L34

**Comment by protango** [comment]
Can do, a bit busy at the moment but will try and make a PR soonish :)

**Comment by doctorpangloss** [comment]
This is a nasty issue, you should just remove the option for now.

**Comment by protango** [comment]
Sorry for the delay guys, appears this is a more complex issue than it first seemed. There are **a lot** of references to the method name that don't consider the lower case option. Instead of trying to track them all down and replace them, I'm implementing a more general approach. Hopefully it will not require us to always check the lower case flag every time we want to use the method name. More to come...
