### ISSUE TITLE
Supporting standard "grpc" package

### ISSUE THREAD

**Issue by fenos** [stephenh/ts-proto#317]
This is a very nice beauty! Thanks a lot for making it!

However why not supporting the native `grpc` package for client and server stubs?
The use of a native C++ grpc implementation is a must for high volume node-js grpc based services.

Will it be something that you'd consider?

**Comment by stephenh** [comment]
@fenos sure, that'd be great to have!

I think ts-proto not having it is primarily an artifact of:

a) ts-proto is not really an out-of-the-box RPC framework, but instead more of a infra-level project for users to "do their own thing" with (i.e. grpc-web, nestjs, twirp, etc.). Although it should probably do some of that.
b) I don't think grpc was really out/very stable when I originally wrote ts-proto

But, those historical reasons aside, sure, that would be great to have.

Just to make sure I follow, would that be taking like this example from the integration tests:

https://github.com/stephenh/ts-proto/blob/main/integration/grpc-js/simple.ts

And keeping the `@grpc/grpc-js` imports but moving away from the `protobufjs/minimal` imports?

**Comment by stephenh** [comment]
Closing as stale
