### ISSUE TITLE
Possibility to remove number separator

### ISSUE THREAD

**Issue by aaroniker** [stephenh/ts-proto#319]
Is there any way to remove the _ (underscore) as a number separator?

Example:
```
| function toTimestamp(date) {
>   var seconds = date.getTime() / 1_000;
>   var nanos = date.getTime() % 1_000 * 1_000_000;
|   return {
```

Current params: `esModuleInterop=true,stringEnums=true,outputClientImpl=false,snakeToCamel=true`

**Comment by stephenh** [comment]
@aaroniker no, we don't currently have that option; this is not supported by the version of TypeScript you're using? I thought this had been around for awhile...

**Comment by aaroniker** [comment]
Thought the same :D 
Too bad .. just got an issue with Storybook (which not support that with the current stack out of the box) - so I guess I'll need to add an additional babel-loader for that

**Comment by stephenh** [comment]
Cool, fwiw going to close this as an issue, but I'd accept a PR that just removed the `_` out right; they are nice to have, but it's not really code users will actively read on a regular basis. Thanks!
