### ISSUE TITLE
Duplicated exports overwrite each other

### ISSUE THREAD

**Issue by dandean** [stephenh/ts-proto#324]
I have a small example service:

```protobuf
syntax = "proto3";

package foo.api.echo.v1;

service EchoService {
  rpc Hello(HelloRequest) returns (HelloResponse);
}

message HelloRequest {
  string message = 1;
}

message HelloResponse {
  string message = 1;
  bool test = 2;
}
```

This library generates code with duplicate exports, making the last export in the file "win", and making preceding exports of the same name inaccessible:

```ts
export interface HelloRequest {
  message: string;
}

export const HelloRequest = {
  encode(message: HelloRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    ...
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): HelloRequest {
    ...
  },

  fromJSON(object: any): HelloRequest {
    ...
  },

  toJSON(message: HelloRequest): unknown {
    ...
  },

  fromPartial(object: DeepPartial<HelloRequest>): HelloRequest {
    ...
  },
};
```

Expected behavior:

The generated file would contain a distinct export for each item:

- `interface HelloRequest` which describes the payload
- `const HelloRequestSerializer` which contains methods for serializing `HelloMessage` objects in both directions.

**Comment by stephenh** [comment]
This is allow in typescript; the namespace for types `interface HelloRequest` is different than the namespace for values `const HelloRequest` and they ~psuedo-unioned together.

I think this covers it: https://www.typescriptlang.org/docs/handbook/declaration-merging.html

**Comment by dandean** [comment]
Wow – that is super confusing to have an export which is both an interface or a value depending on how you use it. Thanks for clarifying.

**Comment by novascreen** [comment]
I am trying to generate JS + types from the generated typescript files and when I do that I'm not able to use the interface anymore 😞
