### ISSUE TITLE
Issues parsing options

### ISSUE THREAD

**Issue by andrewparmet** [stephenh/ts-proto#333]
I'm trying to pass options to the plugin and getting they don't seem to be getting picked up by the generator. I'm running the plugin through Gradle with the protobuf-gradle-plugin, version 1.82.0.

I took a very hacky approach to debugging and replaced the code generation line in `build/plugin.js` with:
```javascript
return { name: path, content: utils_1.prefixDisableLinter(spec) + request.parameter + "\n" + JSON.stringify(options) };
```

And I see in my files:
```
--ts_proto_opt=oneof=unions,--ts_proto_opt=forceLong=long,--ts_proto_opt=esModuleInterop=true
// (below is prettified)
{
  "context": false,
  "snakeToCamel": true,
  "forceLong": "number",
  "useOptionals": false,
  "useDate": "date",
  "oneof": "properties",
  "esModuleInterop": false,
  "lowerCaseServiceMethods": false,
  "outputEncodeMethods": true,
  "outputJsonMethods": true,
  "outputPartialMethods": true,
  "outputTypeRegistry": false,
  "stringEnums": false,
  "constEnums": false,
  "outputClientImpl": true,
  "outputServices": false,
  "returnObservable": false,
  "addGrpcMetadata": false,
  "addNestjsRestParameter": false,
  "nestJs": false,
  "env": "both",
  "unrecognizedEnum": true,
  "exportCommonSymbols": true,
  "outputSchema": false,
  "onlyTypes": false,
  "--ts_proto_opt": "esModuleInterop"
}
```

So I see my options are making it to the plugin, but the parsing seems to choke? What I don't understand is that when I run the plugin manually the options seem to be recognized just fine.

Clearly `forceLong` and `oneof` were not picked up, and `esModuleInterop` shows up unparsed at the end. Am I providing options incorrectly somehow?

**Comment by andrewparmet** [comment]
When I run the hacked plugin manually via protoc, I get `oneof=unions,esModuleInterop=true,forceLong=long` in the first line, which seems to be how the options parser intends to receive them.

**Comment by andrewparmet** [comment]
Ah, I was passing `ts_proto_opt=foo=bar` in the `option()` method on the Gradle plugin. I should have been passing just `foo=bar`.

**Comment by stephenh** [comment]
@andrewparmet thanks for self-diagnosis that! I used to have some code around for "here's how to invoke ts-proto via gradle", but don't anymore. Could you submit a PR to add an example of gradle usage to the readme? I remember it being tricky to figure out.

Thanks!
