### ISSUE TITLE
fromJSON doesn't work for Well-Known Types.

### ISSUE THREAD

**Issue by CatsMiaow** [stephenh/ts-proto#336]
```proto
import "google/protobuf/struct.proto";

message HelloRequest {
  string name = 1;

  google.protobuf.Struct param_struct = 2;
  google.protobuf.ListValue param_list_value = 3;
  google.protobuf.Value param_value = 4;
}
```

When using a WellKnownType of `google-protobuf`, can pass a value from the client to `fromJavaScript` as shown below.

```ts
import { ListValue, Struct, Value } from 'google-protobuf/google/protobuf/struct_pb';

Struct.fromJavaScript({ foo: 'bar', bar: 'foo' });
ListValue.fromJavaScript([{ foo: 'bar' }, { bar: 'foo' }]);
Value.fromJavaScript('Any Value');
```

Reference
- https://www.npmjs.com/package/google-protobuf
- https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/struct.proto
- https://github.com/protocolbuffers/protobuf/blob/master/js/proto3_test.js#L456-L478
- https://github.com/agreatfool/grpc_tools_node_protoc_ts/blob/master/src/lib/WellKnown.ts

In `ts-proto`, the code below doesn't pass values properly or throws an error.
The struct_pb in `google-protobuf` are not compatible because they have different types.
```ts
import { ListValue, Struct, Value } from "./google/protobuf/struct";

Struct.fromJSON({ foo: 'bar', bar: 'foo' });
ListValue.fromJSON([{ foo: 'bar' }, { bar: 'foo' }]);
Value.fromJSON('Any Value'); // Value.fromJSON({ stringValue: 'Any Value' }); This works.
```

https://github.com/stephenh/ts-proto#highlights
> fromJSON/toJSON support the canonical Protobuf JS format (i.e. timestamps are ISO strings)

https://developers.google.com/protocol-buffers/docs/proto3#json
|proto3|JSON|JSON example|Notes|
|-|-|-|-|
|Struct|object|{ … }|Any JSON object.|
|ListValue|array|[foo, bar, …]||
|Value|value||Any JSON value.|

Depending on proto3 json mapping, it looks like `fromJSON` will also work like `fromJavaScript` or a separate method needs to be added.

**Comment by stephenh** [comment]
@CatsMiaow yeah, you're right that Struct, ListValue, and Value aren't specifically handled by ts-proto, but should be.
