### ISSUE TITLE
document for ts_proto_opt is wrong

### ISSUE THREAD

**Issue by ruruiye** [stephenh/ts-proto#34]
should be `--ts_opt=xxx` and `--ts_out=xxx`, don't know why all the document is provide the wrong config options.

**Comment by ruruiye** [comment]
got it. the prefix is follow the plugin name.

and I use 
```
protoc --plugin="protoc-gen-ts=${SCRIPT_DIR}/../node_modules/.bin/protoc-gen-ts_proto" \
  --ts_out="${OUT_DIR}" \
  --ts_opt=outputEncodeMethods=false,outputClientImpl=false \
  --proto_path=xxx
```

**Comment by stephenh** [comment]
Yeah, that was not intuitive to me either at first. I'll make a note of that in the docs. Thanks!
