### ISSUE TITLE
More maintainers

### ISSUE THREAD

**Issue by stephenh** [stephenh/ts-proto#340]
It'd be great to have more maintainers, especially around the various framework-specific integrations (like twirp, NestJS, grpc.io, etc.).

Anyone who's interested, submitting/reviewing a few PRs around your area of interest would be a great way to start.

**Comment by stephenh** [comment]
@doochik per ^ I'd like to add you to the repo as a contributor/maintainer, so you can make your own releases, review/merge the PRs of others/etc; does that sound good to you?

**Comment by doochik** [comment]
Yeah! Thanks!
