### ISSUE TITLE
Common interface for proto messages

### ISSUE THREAD

**Issue by cprovatas** [stephenh/ts-proto#348]
I would like to be able use an interface to identify the protobuf messages ie:

```ts
interface ProtoMessage {
      decode(...)
      encode(...)
      fromJSON(...)
     ....
}
```

Then the code-generated interfaces would extend from this base interface.  Is there some way to do this?  To identify an object that has these methods?

**Comment by stephenh** [comment]
Messages in ts-proto are "just data", they aren't a class, and they don't have class methods, so you can't `instanceof` or detect them as anything other than "an object like any other object".

This is a specific design choice, b/c in JS/TS language features like object spread and structural type checking make creating & munging "just data" objects/object literals really easy and idiomatic.

That said, you can use the `--ts_proto_opt=outputTypeRegistry=true` flag to have a `$type` field added to messages for you, that you can do some runtime type detection/behavior against. Hopefully that works. Thanks!

**Comment by cprovatas** [comment]
Thanks!
