### ISSUE TITLE
Allow disabling of service definition generation

### ISSUE THREAD

**Issue by emil-e** [stephenh/ts-proto#349]
We're generating service definitions using our own custom generator and would like to disable the generation that ts-proto does. I could implement this myself and provide a PR but would like to know what is the preferred way of implementing the option itself. Would setting `--ts_proto_opt=outputServices=false` be appropriate?

**Comment by stephenh** [comment]
@emil-e sure, `outputServices=false` sounds like a good idea; a PR would be great. Thanks!
