### ISSUE TITLE
How can we send response with null type in protobuf?

### ISSUE THREAD

**Issue by GreedLine** [stephenh/ts-proto#350]
Hi, pals.
I wanna to send message in protobuf and return null type from protobuf. I create app on NestJS and my mssql server return to me empty response, if tables is empty.
My strong typization create error on this case.
I wanna to have strong typization on my project.
Undefined is not good to me, cause i cant catch some errors in runtime work.

I really want to know how i can send a type with null field.

I have generated this, for example:

```
message Message {
    oneof kind {
        google.protobuf.NullValue null = 1;
    }
}
```

And this has compiled in:

```
export interface Message{
  null: NullValue | undefined;
}
```

```
export enum NullValue {
  NULL_VALUE = 0,
  UNRECOGNIZED = -1,
}
```

An example of what I want to return from protobuf:
```
{
    data: Response | null
}
```

**Comment by lethanhan97** [comment]
+1 on this
