### ISSUE TITLE
We recommend using the oneof=unions option, how i should write my protobuf?

### ISSUE THREAD

**Issue by GreedLine** [stephenh/ts-proto#351]
https://github.com/stephenh/ts-proto#oneof-handling

I read this information, but i cant understand, how i should write my protobuf?

On this moment i write something like this:
```
message OneOfBootRecordWithTarget {
    oneof kind {
        google.protobuf.NullValue null = 1;
        BootRecordWithTarget record = 2;
    }
}
```

And my compiled interface:
```
export interface OneOfBootRecordWithTarget {
  null: NullValue;
  record: BootRecordWithTarget;
}
```

**Comment by jonaskello** [comment]
@GreedLine Did you resolve this? I'm also using `google.protobuf.NullValue` but in the latest version it generates code that does not compile.
