### ISSUE TITLE
addGrpcMetadata=true import Metadata object from deprecated "grpc" package not from "@grpc/grpc-js"

### ISSUE THREAD

**Issue by iMitaka** [stephenh/ts-proto#356]
When we generate a types using "addGrpcMetadata=true" flag, the imported Metadata class is imported from a "grpc" package that is deprecated. It can be imported from "@grpc/grpc-js" package to not need referencing deprecated dependencies to projects.

Have to change every  `imp('Metadata@grpc')` to `imp('Metadata@@grpc/grpc-js')`in project.

**Comment by stephenh** [comment]
Hi @iMitaka  (and @Prashvith from the discussion thread); I'm not that close to the grpc stuff, do you think we can really just change every `grpc` to `@grpc/grpc-js` or should it be a flag for users to choose which version to use?

If it's deprecated, maybe just always use `@grpc/grpc-js`, and users who don't want that either don't have to upgrade ts-proto, or could request a flag to keep the old import?

@iMitaka are you interested in submitting that does the replacement? You're right, that is the new `imp` to use.

Thanks!

**Comment by iMitaka** [comment]
Hi, yes it is completely save just to change the strings. There is no reason to extend feature to choose, because  'grpc' is deprecated, just replacing will do the job.

**Comment by stephenh** [comment]
Fixed in #362, which is merged and released. Thanks @iMitaka !
