### ISSUE TITLE
Proposal for improve GrpcWebImpl class generation

### ISSUE THREAD

**Issue by YannPerthuis** [stephenh/ts-proto#369]
Thank you first for this lib,

- Context:
I use ts-proto to make a web client lib for a front-end project and use this options: 
`ts_proto_opt=returnObservable=true,outputClientImpl=grpc-web,lowerCaseServiceMethods=true,addGrpcMetadata=true,useOptionals=true,exportCommonSymbols=false,emitImportedFiles=false`.
After generating my stubs, I use the `create-ts-index` library to automatically generate indexes and then transpile the whole generated ts files to produce a js library.

- Problem:
When I transpiling, typescript tells me "**Module './XXXX' has already exported a member named 'GrpcWebImpl'. Consider explicitly re-exporting to resolve the ambiguity**". This conflict is due to the `GrpcWebImpl` class which is present in every grpc service stub and is generated when I specify the `outputClientImpl=grpc-web` option.

- Actual workaround:
I edit with a script each file to remove the keyword `export` in front of the GrpcWebImpl class. On my side in my front-end project which imports the produced stub library, I created my own definition of the GrpcWebImpl class since I have no more access to it.

- Proposal:
1. Would it be possible to generate this GrpcWemImpl class only once (at the root of the output project for example) and that each service must import it to use it.
2. Or, add an option to disable the generation of this class while keeping the generation of proto service implementations for the web.

- Ps:
The generation of this class being identical in each file, a unique generation would make it possible to reduce a little the size of the library as it is intended for the Web and thus to be downloaded by navigators.

**Comment by stephenh** [comment]
Hey @YannPerthuis yeah, I get what you're saying.

I think putting `GrpcWebImpl` into like a single `grpc-web-impl.ts`; we do something similar here:

https://github.com/stephenh/ts-proto/blob/main/src/plugin.ts#L36

Where we push an extra file to the output.

If you'd like to work on a PR that moves `GrpcWebImpl` over to this approach, that'd be great.

Fwiw others have also wanted a single index file that re-exports all the symbols; I'd be up for a PR that adds that as well, granted there is a little wrinkle around avoiding conflicts for symbols that are defined in multiple files.
