### ISSUE TITLE
Windows build didn't work out of the box

### ISSUE THREAD

**Issue by yoavmil** [stephenh/ts-proto#37]
Got this error:
`--ts_proto_out: protoc-gen-ts_proto: %1 is not a valid Win32 application.`

found [this answer](https://github.com/improbable-eng/ts-protoc-gen/issues/15#issuecomment-317063814) in similar question. So I added `.cmd` to the `--plugin` directive, and it worked. For future users, please update readme, or fix this. Thanks.

**Comment by stephenh** [comment]
Great, thanks for the report. I was unsure of that since it seemed like some Windows people used that suffix and some didn't. I don't have Windows install handy to make sure myself, so rely on these bug reports to know. Updated in the readme. Thanks!
