### ISSUE TITLE
How to deal with extensions?

### ISSUE THREAD

**Issue by LazloN5** [stephenh/ts-proto#380]
Hi,

I've been looking around but I couldn't find any clear answer. I have this custom message:
`message CustomMessage {
  required uint32 conversationID = 1;
  extensions 2 to max;
  extend CustomMessage {
    optional Request request = 2;
    optional Response response = 2;
  }
}`

How do I add the Request to the message in typescript ?

**Comment by stephenh** [comment]
Hey @LazloN5 , ts-proto doesn't have any support for extensions at the moment; if you'd like to hack on it, that'd be great!

**Comment by davidzeng0** [comment]
Should hopefully be fixed by https://github.com/stephenh/ts-proto/pull/808
