### ISSUE TITLE
Wrapper Types should have "null" in its type?

### ISSUE THREAD

**Issue by matthewma7** [stephenh/ts-proto#386]
Thank you for this great library!

I could be wrong, but I am wondering why does 
```
message MyMessage {
    google.protobuf.BoolValue wrapperBoolean = 1;
}
```
Generates to this
```
export interface MyMessage {
  wrapperBoolean: boolean | undefined;
}
```
instead of this (see the  "null" there)
```
export interface MyMessage {
  wrapperBoolean: boolean | undefined | null;
}
```

**Comment by stephenh** [comment]
@matthewma7 IIRC there is not a strict reason why we don't include `| null`, other than probably just my own inclination that I try to use "only `undefined`" generally as much as possible / consider that to be more idiomatic, and only use `null` as a truly-special "unset this property" value.

Dunno, just b/c that seems cleaner than an admittedly more lenient approach that treats `undefined` and `null` as "basically the same thing", but then means you need to check for both, worry about "when do I use `undefined` and when do I use `null`?". Or "if this is set as `null` does that mean something different than `undefined`?".

With the ts-proto messages, there would be no difference between `undefined` and `null`, so just being opinionated about "always use `undefined`" leads to the simplest code, at least for the majority of the time.

**Comment by matthewma7** [comment]
Hi @stephenh, thank you for sharing the reasoning behind this. 
I see you what you mean. I'll follow up if I run into a situation where `null` could be useful. 🙂

**Comment by stephenh** [comment]
@matthewma7 np, sounds good!

**Comment by lucaslcode** [comment]
I have come across a use case where not having the option of using `null` in the wrappers necessitates a workaround: I'm using the message field names directly in a form with `react-hook-form`. The `Controller` component in that library doesn't support calling `onChange(undefined)`, so I can't easily set the field to null.

(More specifically, I have a BoolValue which is set with a dropdown "null", "true" or "false". When each is selected, I can call `onChange(true/false)` but `onChange(undefined)` for null doesn't work.)
 
A command-line option would be great, perhaps something like `--ts_proto_opt=outputServices=undefined|null|both`
