### ISSUE TITLE
imports in imported proto files fail to resolve.

### ISSUE THREAD

**Issue by hamiltop** [stephenh/ts-proto#4]
https://github.com/stephenh/ts-proto/pull/3 has the proto file that breaks things

Fails with:
```
    build/integration/import_dir/thing.ts:2:27 - error TS2307: Cannot find module './google/protobuf/timestamp'.

    2 import { Timestamp } from './google/protobuf/timestamp';
```

**Comment by stephenh** [comment]
...yep. :-) Did you or @a-morales want to take a crack at this?

I've struggled a few times with the lack of strong conventions in protobuf around package name maybe/maybe-not equals directory structure, and then how that should/should not map into the directory/module/package structure of each generated language/typescript.

The code that probably handles this is here:

https://github.com/stephenh/ts-proto/blob/master/src/types.ts#L190

That said, the repro is great in #3, so I can poke at it too at some point.

**Comment by hamiltop** [comment]
One solution is to use relative paths from the current file to the import. I think that would have to happen in ts-poet though?

Alternatively we do absolute paths somehow.

**Comment by stephenh** [comment]
I like the idea of relative paths...  ts-poet _should_ handle relative paths okay, it really doesn't do much logic around paths other than "recognize when I do/do not need to add an import for types that are defined in my own module":

https://github.com/stephenh/ts-poet/blob/058b923d6c12b765cccb50f4e914ef0b0a5a90ae/src/CodeWriter.ts#L154

That said, I wouldn't be surprised if there is some nuance missing either between the ts-proto/ts-poet hand-off or within ts-poet itself.

**Comment by stephenh** [comment]
You were right, it was in ts-poet. I pushed out a fix to ts-poet, bumped the revision here, so ts-proto 1.4.1 is on npm and should work, at least for your import_dir/thing test case. :-)

**Comment by hamiltop** [comment]
Thank you sir!
