### ISSUE TITLE
StateEnum Namespace and Enum VariableName is Suffering

### ISSUE THREAD

**Issue by hrb-bacigalupo-diego** [stephenh/ts-proto#40]
I have a proto file with Enum defined.
When I got to generate ts file from this proto file, Enum variable name and Namespace variable name is are just same.
So when I build this code babel shout this error.
``` Typescript
ERROR in ./src/proto/submodules/proto/shepherd/twirp/main.ts
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/diegobacigalupo/WebstormProjects/shepherd-front-temp/src/proto/submodules/proto/shepherd/twirp/main.ts: Namespace not marked type-only declare. Non-declarative namespaces are only supported experimentally in Babel. To enable and review caveats see: https://babeljs.io/docs/en/babel-plugin-transform-typescript
  620 | }
  621 | 
> 622 | export namespace StateTypeNum {
      |                  ^^^^^^^^^^^^
  623 |     export function fromJSON(object: any): StateTypeNum {
  624 |         switch (object) {
  625 |             case 0:

// Enum
export enum StateTypeNum {
   Unknown = 99
}

```
How do you avoid this error when using Enums in Proto?

**Comment by stephenh** [comment]
I haven't used ts-proto with babel before, but the compile error you gave links to babel docs which insinuate that turning on `allowNamespaces` should make this work. Can you try that?

**Comment by hrb-bacigalupo-diego** [comment]
Thanks for u r reply.

Yes I tried to add `allowNamespaces` but not work.
But when i change the namespace variable name to `StateType` make this work.

**Comment by stephenh** [comment]
Hm, yeah, not sure about that from a babel perspective. These enum static methods aren't really public anyway, so I'll change the namespace name, I don't think that would be considered a breaking change.

**Comment by stephenh** [comment]
I poked around at a quick fix for this, and there was a little more nuance than I expected. Should still be fixable, just still working on it.

**Comment by stephenh** [comment]
Okay, I've fixed this by not actually using the `enum` keyword, but instead using a `const` object literal that "looks like a enum" + can have the extra "static" `toJSON`/`fromJSON` methods. Version v.1.14.0 is published and has this fix. Thanks for reporting it!

**Comment by ByronComparisonTech** [comment]
@stephenh is it possible to have the enum type generation as an option?
I'm dynamically generating a form base off of these types and need to know when something is originally an enum

**Comment by stephenh** [comment]
@ByronComparisonTech hm. I think I get what you're trying to accomplish, but I don't think the old way with `enum` keywords would have worked either?

I.e. if you get something that is just:

```typescript
const message = Message.decode(...);
// message.state is either (enums) StateEnum.ENABLED i.e. `0` ... or now `0`
```

I.e. either way the `message.state` field is going to have the value `0` and I don't see how you could somehow derive that "this is an enum" / i.e. "what are the other valid enum values" without having the actual protobuf schema around.
