### ISSUE TITLE
How to get the name of the message 

### ISSUE THREAD

**Issue by ajaykarthikr** [stephenh/ts-proto#409]
Python protobuf library provides descriptors through which you can get name of the [protocol message type](https://googleapis.dev/python/protobuf/latest/google/protobuf/descriptor.html#google.protobuf.descriptor.Descriptor.name). Does this library provide something similar to this?

For example
user_details.proto
```
message UserDetails{
  string name = 1 [ json_name = "other_name" ];
}
```

index.js
```
console.log("Output: ", UserDetails.DESCRIPTOR.name)
// Output: UserDetails
```

I am using this library in WebSockets to parse json data, without knowing correct message type it would be difficult to correctly parse the message using correct interface. Right now I am mapping received message to correct interface by hard-coding. Descriptors would make this easy.

**Comment by stephenh** [comment]
@ajaykarthikr if you use the `--ts_proto_opt=outputTypeRegistry=true` option, then `fromJSON` / `fromPartial` will add a `$type` key to each message, which I think will be what you want. Going to go ahead and close this issue, but feel free to ask any clarifications / re-open if that doesn't work. Thanks!

**Comment by ajaykarthikr** [comment]
Thanks! This does the job for me.
