### ISSUE TITLE
Proposal: watch mode to generate .ts on any change in .proto file

### ISSUE THREAD

**Issue by juanlatorre** [stephenh/ts-proto#428]
It would be amazing to have some kind of watch mode to generate the TypeScript file on every change made to the .proto, this would be super awesome for faster prototyping.

**Comment by juanlatorre** [comment]
Gonna close this, realized that the feature itself must be implemented in `protoc`, not in this plugin.

They are not going to develop a watch mode tho 🥲 https://github.com/protocolbuffers/protobuf/issues/2731

**Comment by stephenh** [comment]
Hey @juanlatorre ! Yep, you're right, ideally this would be implemented in `protoc` proper.

FWIW you could probably put something together with one of these tools:

* https://github.com/open-cli-tools/chokidar-cli
* https://facebook.github.io/watchman/docs/watchman-make.html

But it also depends on how you're invoking `protoc`.

If you come up with a succinct approach and want to add a small section about it to the readme, that'd be great. Thanks!

**Comment by juanlatorre** [comment]
With chokidar I've been able to add watch mode to the protoc command, executing the whole thing as a script in package.json.

`npm i -D chokidar-cli`

and in the package.json add the following scripts (obviously, everyone has custom settings for the plugin, this is just an example):

```json
"proto:generate": "protoc --ts_proto_out=. ./<proto_path>/<proto_name>.proto --ts_proto_opt=esModuleInterop=true --ts_proto_opt=outputServices=generic-definitions --ts_proto_opt=outputPartialMethods=false --ts_proto_opt=useOptionals=true",
"proto:watch": "chokidar \"**/*.proto\" -c \"npm run proto:generate\""
```

Thanks for your guidance on this! if you could add this to the README it would be awesome.

**Comment by juanlatorre** [comment]
Hey @stephenh I've made a PR to help https://github.com/stephenh/ts-proto/pull/430
