### ISSUE TITLE
import of another .proto file is not supported

### ISSUE THREAD

**Issue by sevketufuk** [stephenh/ts-proto#441]
Hi all, 
I have the file `x.proto` which imports `y.proto` as `import "y.proto"` which is placed in the same folder, when I run ts-proto as `protoc --plugin=./node_modules/.bin/protoc-gen-ts_proto --ts_proto_out=. ./x.proto
`, I have the error `y.proto: File not found`. Any idea what is going on?

Thanks

**Comment by stephenh** [comment]
We have examples of imports here:

https://github.com/stephenh/ts-proto/blob/main/integration/simple/simple.proto

My guess is you probably need a `-I` parameter to `protoc`, like even `-I=.`.
