### ISSUE TITLE
Display names for enum values

### ISSUE THREAD

**Issue by shimonmagal** [stephenh/ts-proto#453]
Hi, I am using ts-proto for my frontend. Within my frontend I have the following use case:
I sometimes use enum values for a generic piece of code that gets rendered as HTML/React/etc...

I can't use the default enum values, since they are always in caps / don't support special chars.

I would like to support:
```
enum MyEnum {
  OPT1 = 0 [displayName = "This is option no. 1"]
  OPT2 = 0 [displayName = "2 is the number of this option"]
}
```

and on the TS side, to have some way to get that values, for example:
myObj.myEnum == 0
myObj.myEnum__displayName == "This is option #1"

I know you added enumAsString, but in my use case - I want to support an alternative string which is display-friendly.

If such a feature exists / if you can give me a general direction on how to add it myself - that'd be great!

Thx

**Comment by shimonmagal** [comment]
I added support for what I need based on #380 (Vilsol's pr). I didn't manage to make the pr work for me yet, but added the support I needed and tested with the generated protos inside the integration dir.
So waiting for that to be merged.

**Comment by stephenh** [comment]
Hey @shimonmagal ; nothing to add, but great to hear that #380 's approach works well for what you'd like to do.
