### ISSUE TITLE
Problems with Exact types

### ISSUE THREAD

**Issue by aikoven** [stephenh/ts-proto#454]
After the Exact types were introduced in #412, the [nice-grpc](https://github.com/deeplay-io/nice-grpc) integration with `ts-proto` stopped working.

The reason is that `nice-grpc` automatically wraps client requests with `fromPartial`, e.g.:

```protobuf
service TestService {
  rpc TestMethod(TestMessage) returns (TestMessage);
}

message TestMessage {
  string test_field = 1;
  string another_field = 2;
}
```

Before Exact types, the generated client would have a type roughly equal to:

```ts
type TestServiceClient = {
  testMethod(request: DeepPartial<TestMessage>): Promise<TestMessage>;
}
```

So instead of

```ts
client.testMethod(TestMessage.fromPartial({testField: ''}))
```

we could just write

```ts
client.testMethod({testField: ''})
```

The client type is produced using mapped types, and the request parameter is calculated as `Parameters<RequestMessageType['fromPartial']>[0]`. But with Exact types, this type resolves to

```ts
{ ... } & { ... } & Record<string | number | symbol, never>
```

which only matches empty object.

Ideally, the generated client type should do the Exact trick in its methods as well, i.e.:

```ts
type TestServiceClient = {
  testMethod<I extends Exact<DeepPartial<TestMessage>, I>>(request: I): Promise<TestMessage>;
}
```

Unfortunately, this [isn't currently possible](https://stackoverflow.com/questions/69855855/can-i-preserve-generics-in-conditional-types) to do with mapped types, since there's no support for higher-kinded types in TypeScript.
 
The one thing I came up with is a helper that can un-exact a type recursively:

```ts
type Unexact<T> = {
  [K in keyof T as string extends K ? never : number extends K ? never : K]: Unexact<T[K]>;
};
```

which takes us back to `DeepPartial<...>` so we can use `Unexact<Parameters<RequestMessageType['fromPartial']>[0]>` as the request parameter. It kinda works, but IDE hints and suggestions are now hardly readable.

If there's no other solution, should we maybe introduce an option to disable Exact types?

**Comment by stephenh** [comment]
Hey @aikoven hrm, yeah, that sounds tricky...

Just a naive question, but given you've already got the `RequestMessageType` to do `Parameters<RequestMessageType['fromPartial']>[0]`, can you just use `RequestMessageType` directly and not get the type out of the `fromPartial`?

Like make this:

```
export type TsProtoMessageIn<
  Type extends TsProtoMessageType<any>
> = Type['fromPartial'] extends Function
  ? Parameters<Type['fromPartial']>[0]
  : Type extends TsProtoMessageType<infer Message>
  ? Message
  : never;
```

Be just:

```
export type TsProtoMessageIn<
  Type extends TsProtoMessageType<any>
> = Type extends TsProtoMessageType<infer Message>
  ? Message
  : never;
```

And then re-wrap that `Message` in `Exact` / `DeepPartial` as/if needed when creating the service methods?

**Comment by aikoven** [comment]
I could use the `DeepPartial` type directly, but it would create coupling with exact `ts-proto` plugin parameters, since `DeepPartial` may look a bit different depending on parameters.

Regarding `Exact`, I'm not sure that it is currently possible to introduce it to `nice-grpc` while keeping the Protobuf implementation replaceable (I'm using mapped types to achieve it).
