### ISSUE TITLE
google.protobuf.NullValue in oneof

### ISSUE THREAD

**Issue by jonaskello** [stephenh/ts-proto#458]
We have quite a lot of code running with 1.49.0 and I tried to upgrade to 1.96.1 and ran into an issue that the generated code did no longer compile. I tracked it down to usage of `google.protobuf.NullValue` in `oneof`.  The options used are `ts_proto_opt=outputClientImpl=false,oneof=unions,snakeToCamel=false,esModuleInterop=true` and we have something like this in a .proto file:

```proto

import "google/protobuf/struct.proto";

// .. more omitted code

message ColumnValue {
  oneof value {
    google.protobuf.NullValue null = 1;
    ComponentNode node = 2;
    ComponentRelation relation = 3;
    string string = 4;
    int32 number = 5;
  }
}
```

By importing `google/protobuf/struct.proto` ts-proto 1.96.1 will generate this code in `struct.ts`:

```ts

export interface Value {
  kind?:
    | { $case: "null_value"; null_value: NullValue }
    | { $case: "number_value"; number_value: number }
    | { $case: "string_value"; string_value: string }
    | { $case: "bool_value"; bool_value: boolean }
    | { $case: "struct_value"; struct_value: { [key: string]: any } | undefined }
    | { $case: "list_value"; list_value: Array<any> | undefined };
}


export const Value = {

 // ..working code omitted

  unwrap(message: Value): string | number | boolean | Object | null | Array<any> | undefined {
    // COMPILE ERROR: Property 'stringValue' does not exist on type 'Value'.ts(2339)
    if (message?.stringValue !== undefined) {
      return message.stringValue;
    } else if (message?.numberValue !== undefined) {
      return message.numberValue;
    } else if (message?.boolValue !== undefined) {
      return message.boolValue;
    } else if (message?.structValue !== undefined) {
      return message.structValue;
    } else if (message?.listValue !== undefined) {
      return message.listValue;
    } else if (message?.nullValue !== undefined) {
      return null;
    }
    return undefined;
  },
};
```

It seems the `if (message?.stringValue !== undefined)` checks has been added between 1.49.0 and 1.96.1.

I am not sure if this is a bug or we are misusing `google.protobuf.NullValue` here and got away with it in the earlier version :-).

**Comment by stephenh** [comment]
Hm, @boukeversteegh I think you've done the most / are the expert on wrapper types these days :-), wdyt of ^?

...maybe we don't have a test that uses `struct.proto` with `oneof=unions`? Kinda guessing / not sure...

Thanks!

**Comment by boukeversteegh** [comment]
@jonaskello thanks for opening this issue with a clear description. It looks like the unwrap method for Value doesn't take into account union types, as @stephenh said. Should not be difficult to fix, it's in generateUnwrappers.
Probably the wrapper is also wrong then, but not sure. I wont have a lot of time this week but I'll try to have a look. You could also have a go yourself.

**Comment by jonaskello** [comment]
I was able to work around this issue by simply copying the definition of `google.protobuf.NullValue` into the proto file that was referencing it. It is a simple definition like this:

```proto
enum NullValue { NULL_VALUE = 0; }
```

I noticed ts-proto nog recogized some of the `google.protobuf.*` stuff. Not sure if `google.protobuf.NullValue` should be recognized as well. It is originally meant to be used in the `Value` type union that is defined in `struct.proto` but you can include it in your own union to represent explicit null.

**Comment by boukeversteegh** [comment]
@jonaskello glad you found a way to work around this issue.

I've looked into this and I'm working on a partial fix. The issue has two causes

- using NullValue separately from Value is not supported at the moment. This is regardless of whether it is in a oneof field. This means it is treated as a regular Enum. According to the google protobuf json spec, it should be treated specially, also when used standalone, so this is a missing feature now.
- the new support for parsing Value and Struct into native JSON does not take into account `oneof=unions`. For this see #462
