### ISSUE TITLE
issue: Import "google/api/annotations.proto" was not found or had errors

### ISSUE THREAD

**Issue by YinTokey** [stephenh/ts-proto#461]
This is my proto contents. My server side project(Golang) is using this kind proto to support http, but it can't work when I use ts-proto to generate typescript files.
```
syntax = "proto3";
import "google/api/annotations.proto";
package Video;

service Video {

  rpc GetVideo(GetVideoRequest) returns (GetVideoReply) {
    option (google.api.http) = {
      get: "/video"
    };
  }
}

message GetVideoRequest{}
message GetVideoReply{}
```

**Error message**
```
google/api/annotations.proto: File not found.
Import "google/api/annotations.proto" was not found or had errors.

```

**Comment by stephenh** [comment]
This looks like an error from `protoc` not being able to find `annotations.proto`, so is not an error in ts-proto itself; try the `-I` flags to `protoc` to tell it where to find `google/api/annotatoins.proto`.

**Comment by fultonm** [comment]
I think protoc is good at finding the well known built-in types such as `annotation` and `any` automatically, if they are installed on your machine. The import syntax is useful for custom types you make yourself.
In my case, I had to install `protobuf-devel` which puts them in my `/usr/include/google/protobuf` folder, then protoc was able to compile.

**Comment by stephenh** [comment]
Nice! Thanks @fultonm !

**Comment by YinTokey** [comment]
> This looks like an error from `protoc` not being able to find `annotations.proto`, so is not an error in ts-proto itself; try the `-I` flags to `protoc` to tell it where to find `google/api/annotatoins.proto`.

Thank you!
