### ISSUE TITLE
outputServices=grpc-js always generates client stub

### ISSUE THREAD

**Issue by alexeyten** [stephenh/ts-proto#471]
I've tried to use options `--ts_proto_opt=esModuleInterop=true,outputServices=grpc-js,outputClientImpl=false`, but `interface TestClient extends Client { ... }` and `const TestClient = makeGenericClientConstructor(...)` are always generated.

I guess it's because there is no options check in https://github.com/stephenh/ts-proto/blob/main/src/generate-grpc-js.ts#L41-L42

So far, I've found that `outputClientImpl` option has effect only for `outputServices=default`.

**Comment by stephenh** [comment]
Closing as fixed in #472 ; thanks!
