### ISSUE TITLE
Remove bin files

### ISSUE THREAD

**Issue by stephenh** [stephenh/ts-proto#475]
I think with @boukeversteegh 's amazing work around docker-izing the `.bin` generation, I kinda wonder if we could just remove the `*.bin` files all together, and just run `protoc` directly each time?

So like `proto2bin` --> `bin2ts` would become just `proto2ts`.

The original purpose of the `*.bin` files was to protect/decouple from invoking native `protoc` all the time; but now that we have a super-easy docker-ized `protoc`...I think they have outlived their usefulness.

The only catch would be if (although I doubt it) for some reason doing `proto2ts` was dramatically slower than `bin2ts`...

**Comment by stephenh** [comment]
@boukeversteegh wdyt re ^? Does it pique your interest? :-D

**Comment by boukeversteegh** [comment]
It would be great if we could avoid the bin step, yeah!

update-bins takes 5 seconds on my 4.5ghz machine, so it's not very fast, but it also runs completely sequential.

As long as we take care to batch the `protoc` commands within a single container run, the overhead should be no more than a few seconds, although building the container does take more time if it didn't happen before. So i'm not sure about the Github Actions, if they cache the builds..
In any case, it's probably worth it. It will simplify the flow; we can try to optimize it later if needed.
