### ISSUE TITLE
Snake to Camel unexpected result

### ISSUE THREAD

**Issue by mpx2m** [stephenh/ts-proto#478]
I have a proto file like this
```proto
syntax = "proto3";

package sso.v2;

message Client {
    string clientI_d = 1;
    string client_secret = 2;
}

message LoginRequest {
    string redirectUR_i = 12;
}
```

**after**:
```bash
protoc --plugin=./node_modules/.bin/protoc-gen-ts_proto --ts_proto_opt=nestJs=true --ts_proto_opt=env=node --ts_proto_opt=addGrpcMetadata=true --ts_proto_opt=useExactTypes=false --ts_proto_opt=useOptionals=messages --ts_proto_opt=forceLong=string --ts_proto_out=. *.proto
```
**produce**:
```typescript
/* eslint-disable */
import { util, configure } from "protobufjs/minimal";
import * as Long from "long";

export const protobufPackage = "sso.v2";

export interface Client {
  clientiD: string;
  clientSecret: string;
}

export interface LoginRequest {
  redirecturI: string;
}

export const SSO_V2_PACKAGE_NAME = "sso.v2";

// If you get a compile-error about 'Constructor<Long> and ... have no overlap',
// add '--ts_proto_opt=esModuleInterop=true' as a flag when calling 'protoc'.
if (util.Long !== Long) {
  util.Long = Long as any;
  configure();
}

```

the expected result should be `clientID` instead of `clientiD` and `redirectURI` instead of `redirecturI`

**Comment by stephenh** [comment]
Huh, `clientI_d` is...creative... :-D and I assume crafted solely to generate `clientID` in the generated code? But I can see how it achieves that goal.

And yeah I guess in theory there isn't a strong reason that we _have_ to lower case the rest of the chunk after splitting on `_`... 

If you'd like to submit a PR here:

https://github.com/stephenh/ts-proto/blob/5a1a6a1c6c7b0cea64b316afa86fd2103acd731d/src/case.ts#L10

And add your case to the tests here:

https://github.com/stephenh/ts-proto/blob/5a1a6a1c6c7b0cea64b316afa86fd2103acd731d/tests/case-test.ts

That'd be great. Assuming it doesn't break any existing tests; not sure/haven't looked that closely.

**Comment by alexeyten** [comment]
Shouldn't it be consistent with `--js_out`?

https://developers.google.com/protocol-buffers/docs/reference/javascript-generated#fields

**Comment by stephenh** [comment]
@alexeyten at a high-level, I'm personally not that tied to mimicking `protoc`s JS output / behavior, b/c "nicer than the built-in JS output" is ts-proto's primary rationale :-). That said, tactically for this specific issue, I think that sounds like a good idea, and AFAICT the casing behavior you linked to is also what @mpx2m is requesting, so that works out well. Thanks for pointing that out!

I haven't done a `git blame`, but if I was the one who wrote ts-proto's current `snakeToCamel`, then I'm sure I just made it up quickly, and am perfectly happy to change it.

**Comment by mpx2m** [comment]
@stephenh I checked the git blame. This is intended behavior of camelization and is added after #251 to match other situation need. So maybe just add a flag (option) to keep both camelization behavior.

**Comment by stephenh** [comment]
@mpx2m thank you for doing that checking; I should have remembered that. I had a hunch someone had asked to tweak this before, but it's been awhile...

Fwiw I'd be fine with trying to be smarter/cuter about detecting both styles of inputs, i.e. do something like `const isAllUpperCase = name.match(/^[A-Z_])` and then `isAllUpperCase ? part.toLowerCase() : part` sort of thing, where we detect the `FOO_BAR_ZAZ` from that PR and keep the current behavior, but if we detect mixed case camel, we assume the user knows what they are doing, and skip the `.toLowerCase()`.

**Comment by stephenh** [comment]
@mpx2m I went ahead and made `snakeToCamel` recognize when the user already has mixed case in their identifiers, and then skips the `.toLowerCase`. I think that should work for your case. It will be auto-released soon.

**Comment by mpx2m** [comment]
@stephenh after`1.102.2`, still encounter weird behavior though.
Suppose the proto (test.proto) file like this:
```proto
syntax = "proto3";
package baseinfo.v1;

message ClientDepartment {
    string display_nameI18n = 2;
}

message MenuCalendarRequest {
    int64 meal_planI_d = 1;
    int64 menu_calendarI_d = 2;
}

message QRCodeConfirmRequest {
    string qr_codeI_d = 1;
}
```

after:
```bash
"protoc --plugin=./node_modules/.bin/protoc-gen-ts_proto --ts_proto_opt=nestJs=true --ts_proto_opt=env=node --ts_proto_opt=addGrpcMetadata=true --ts_proto_opt=useExactTypes=false --ts_proto_opt=useOptionals=messages --ts_proto_opt=forceLong=string --ts_proto_opt=unrecognizedEnum=false --ts_proto_out=. test.proto"
```

produce (test.ts):
```ts
/* eslint-disable */
import { util, configure } from "protobufjs/minimal";
import * as Long from "long";

export const protobufPackage = "baseinfo.v1";

export interface ClientDepartment {
  displayNamei18n: string;
}

export interface MenuCalendarRequest {
  mealPlaniD: string;
  menuCalendariD: string;
}

export interface QRCodeConfirmRequest {
  qrCodeiD: string;
}

export const BASEINFO_V1_PACKAGE_NAME = "baseinfo.v1";

// If you get a compile-error about 'Constructor<Long> and ... have no overlap',
// add '--ts_proto_opt=esModuleInterop=true' as a flag when calling 'protoc'.
if (util.Long !== Long) {
  util.Long = Long as any;
  configure();
}

```
`display_nameI18n` --->  `displayNamei18n` (should be `displayNameI18n`?)
`meal_planI_d` --->  `mealPlaniD` (`mealPlanID`)
`menu_calendarI_d` --->  `menuCalendariD` (`menuCalendarID`)
`qr_codeI_d` --->  `qrCodeiD` (`qrCodeID`)

**Comment by stephenh** [comment]
@mpx2m afaict you're saying that the output you're seeing now (w/1.102.2) is the same as the output as before?

If so, my initial guess is that the `protoc` is not actually using 1.102.2.

**Comment by mpx2m** [comment]
@stephenh at version 1.103.0 (1.102.2), does fix `clientI_d` problem. If the proto likes this:
```proto
syntax = "proto3";
package baseinfo.v1;

message ClientDepartment {
    string clientI_d = 3;
}
```
after 
```bash
"ts-proto": "protoc --plugin=./node_modules/.bin/protoc-gen-ts_proto --ts_proto_opt=nestJs=true --ts_proto_opt=env=node --ts_proto_opt=addGrpcMetadata=true --ts_proto_opt=useExactTypes=false --ts_proto_opt=useOptionals=messages --ts_proto_opt=forceLong=string --ts_proto_opt=unrecognizedEnum=false --ts_proto_out=. test.proto"
```

produce
```ts
/* eslint-disable */
import { util, configure } from "protobufjs/minimal";
import * as Long from "long";

export const protobufPackage = "baseinfo.v1";

export interface ClientDepartment {
  clientID: string;
}

export const BASEINFO_V1_PACKAGE_NAME = "baseinfo.v1";

// If you get a compile-error about 'Constructor<Long> and ... have no overlap',
// add '--ts_proto_opt=esModuleInterop=true' as a flag when calling 'protoc'.
if (util.Long !== Long) {
  util.Long = Long as any;
  configure();
}
```

**but still facing**

`display_nameI18n` --->  `displayNamei18n` (should be `displayNameI18n`?)
`meal_planI_d` --->  `mealPlaniD` (`mealPlanID`)
`menu_calendarI_d` --->  `menuCalendariD` (`menuCalendarID`)
`qr_codeI_d` --->  `qrCodeiD` (`qrCodeID`)

if proto likes this
```proto
syntax = "proto3";
package baseinfo.v1;

message ClientDepartment {
    string display_nameI18n = 1;
    int64 meal_planI_d = 2;
    int64 menu_calendarI_d = 3;
    string qr_codeI_d = 4;
}
```
produce
```ts
/* eslint-disable */
import { util, configure } from "protobufjs/minimal";
import * as Long from "long";

export const protobufPackage = "baseinfo.v1";

export interface ClientDepartment {
  displayNamei18n: string;
  mealPlaniD: string;
  menuCalendariD: string;
  qrCodeiD: string;
}

export const BASEINFO_V1_PACKAGE_NAME = "baseinfo.v1";

// If you get a compile-error about 'Constructor<Long> and ... have no overlap',
// add '--ts_proto_opt=esModuleInterop=true' as a flag when calling 'protoc'.
if (util.Long !== Long) {
  util.Long = Long as any;
  configure();
}

```

**Comment by stephenh** [comment]
@mpx2m ah okay, yeah I'd only fixed the first word. All words should now have the updated behavior.
