### ISSUE TITLE
map type attempts to allow undefined keys

### ISSUE THREAD

**Issue by bradurani** [stephenh/ts-proto#483]
ts-proto version: 1.102.0
node version: 16.1.0
protoc version: 3.19.0
typescript version: 4.4.4

Hi, I have a simple proto with a map such as:
```
syntax = "proto3";
package foo;

message Foo {
  string id = 1;
  string email = 2;
  string company_name = 3;
  map<string,string> form_data = 5;
  string time_iso = 6;
}
```

When I generate the classes, then try to compile them with TypeScript, I get:
```
messages/foo.ts(11,16): error TS1268: An index signature parameter type must be 'string', 'number', 'symbol', or a template literal type.
messages/foo.ts(25,5): error TS2322: Type 'undefined' is not assignable to type '{ [key: string]: string; }'.
messages/foo.ts(72,30): error TS2538: Type 'undefined' cannot be used as an index type.
messages/foo.ts(95,14): error TS1268: An index signature parameter type must be 'string', 'number', 'symbol', or a template literal type.
messages/foo.ts(127,8): error TS1268: An index signature parameter type must be 'string', 'number', 'symbol', or a template literal type.
```

This comes from code such as:
```
     export interface Foo {
        id: string | undefined;
        email: string | undefined;
        companyName: string | undefined;
        formData: { [key: string | undefined]: string };
        timeIso: string | undefined;
      }
```
This is because `undefined` is not a valid key for an object indexer. (I think it actually attempts to look-up `foo["undefined"]`)!
At least that's true with TypeScript's `strictNullChecks: true`. If I change that to `false` it doesn't error, but that seems wrong.

I've set-up a demo project to demonstrate this. You just need Docker. It uses all the versions of everything I'm using in my project. 

Just clone:
https://github.com/bradurani/type_error

and run
```
docker build -t type_error . && docker run type_error
```

I'm curious now! Thanks

**Comment by stephenh** [comment]
@bradurani huh, that's odd... We have tests for that here:

https://github.com/stephenh/ts-proto/blob/main/integration/simple/simple.proto#L95

And the output here:

https://github.com/stephenh/ts-proto/blob/main/integration/simple/simple.ts#L192

And so far it has worked just fine.

And the code that does this calculation is here:

https://github.com/stephenh/ts-proto/blob/main/src/types.ts#L624

Kinda weird, there is an in-source comment about "we don't need `| undefined`" for the _value_ type, but for some reason the code doesn't think it needs the same "use basicTypeName" for the _key_ type.

There is this code:

```
  if (
    (!isWithinOneOf(field) &&
      isMessage(field) &&
      (options.useOptionals === false || options.useOptionals === 'none')) ||
    (isWithinOneOf(field) && options.oneof === OneofOption.PROPERTIES) ||
    (isWithinOneOf(field) && field.proto3Optional)
  ) {
    return code`${type} | undefined`;
  }
```

But it only runs if `field` (in this case the `key` of the map message) passes `isMessage`, which should be false for `string` keys...

My initial poking around hasn't found anything obvious; if you could keep investigate some more that'd be great. Thanks!

**Comment by boukeversteegh** [comment]
Strange, but when I run the commands, I do not get the invalid output.

```bash
docker run type_error

# ...
     7  export interface Foo {
     8    id: string;
     9    email: string;
    10    companyName: string;
    11    formData: { [key: string]: string };
    12    timeIso: string;
    13  }
# ...
```

Also in version 1.108.0, the output is correct, without `| undefined` in the key map.

**Comment by stephenh** [comment]
@boukeversteegh thanks for looking at this as well! @bradurani given that it seems like your repro is not reproing anymore, going to close this out. Feel free to re-open if there is something we're missing. Thanks!
