### ISSUE TITLE
Implement FieldMask Well-Known type

### ISSUE THREAD

**Issue by alexeyten** [stephenh/ts-proto#497]
https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#fieldmask

This should serialize to JSON as a comma-separated string.
And probably in JS this should be represented as an array of string. E.g. this
```proto
syntax = "proto3";

package dummy;

import "google/protobuf/field_mask.proto";

message GetFields {
  uint32 id = 1;
  google.protobuf.FieldMask fields = 2;
}
```
should be represented as an object `{ id: 1, fields: ['foo', 'bar', 'baz.quux'] }`.
Now it is represented as `{ id: 1, fields: { paths: ['foo', 'bar', 'baz.quux'] }`.

**Comment by stephenh** [comment]
Closing this out thanks to @buyology 's PR; thanks Robin!

(@alexeyten fwiw I'm open to a follow up issue to represent FieldMask as a `string[]` directly in the message as well; currently it's a `string[]` in the JSON, but still a `FieldMask` message type.)
