### ISSUE TITLE
Feature Request: post process fields to remove proto formatting

### ISSUE THREAD

**Issue by dustinbyershax** [stephenh/ts-proto#502]
Hello!

I'm currently using `Buf`, and have decided to keep the linting strict. This means that my enums look like
```
// enum names must be prefixed by enum name
enum SupportedStates {
  SUPPORTED_STATES_UNSPECIFIED = 0;
  SUPPORTED_STATES_AL = 1;
  SUPPORTED_STATES_AK = 2;
....
```

I was curious if anyone had mentioned a feature to allow for the output to be as though the lint rule was not required, like
```
enum SupportedStates {
  AL = 1;
  AK = 2;
....
```

I've figured that I want to keep the proto files as the source of truth, and keep to the recommended patterns, but would like to have my cake and eat it too by being able to stick to preferred conventions :-P

**Comment by stephenh** [comment]
@dustinbyershax hey, this is a dup of #228 , which _almost_ has a PR landing soon...
