### ISSUE TITLE
Module protobufjs/minimal has no default export

### ISSUE THREAD

**Issue by davidzhao** [stephenh/ts-proto#536]
First of all, thanks for the fantastic work on this library. We found it to generate the cleanest set of typescript definitions and use it throughout [livekit](https://github.com/livekit).

A few of our users have reported seeing the following when running generated scripts with Angular and Firebase:

```
Error: node_modules/livekit-client/dist/proto/livekit_models.d.ts:1:8 - error TS1192: Module '"projects/livekit/angular-issue/issue/node_modules/protobufjs/minimal"' has no default export.

1 import _m0 from "protobufjs/minimal";
```

One could workaround this issue with [allowSyntheticDefaultImports](https://www.typescriptlang.org/tsconfig#allowSyntheticDefaultImports), but it seems cleaner to generate the following instead

```
import * as _m0 from "protobufjs/minimal";
```

**Comment by stephenh** [comment]
@davidzhao Ah nice! Great to hear that ts-proto is working well for you; Livekit looks super impressive.

...per your suggestion, that sounds like a really good idea. I'm not sure why we didn't think of that before, b/c we've/I've been fighting the silly `protobuf/minimal` thing for awhile now, i.e. ts-proto has a flag to like conditionally change the `protobufjs/minimal` export based on whether the user is using the `esModuleInterop` flag...

Do you know if your suggestion of:

```
import * as _m0 from "protobufjs/minimal";
```

Would basically always work, regardless of the user's specific tsconfig? If so, that's pretty amazing. I'm currently futzing with the underlying ts-poet library to get it to generate this style of import (which it can do, but just needs a little polish), and so will plan on trying this out soon...

Thanks!

**Comment by davidzhao** [comment]
Reading [a bit](https://javascript.plainenglish.io/how-to-correctly-use-typescript-module-import-syntax-and-settings-in-various-circumstances-e98bfa87f70f) [more](https://blog.jdriven.com/2017/06/typescript-and-es6-import-syntax/) on this, I think this format is "more" compatible?

```
import _m0 = require("protobufjs/minimal")
```

I've tested within our set up and it appears to work well.

**Comment by stephenh** [comment]
@davidzhao huh! I'd never seen that import-equal syntax before. I'm tempted to still go with the namespace-import; I've got a PR open in #540 and AFAICT it's working for both non-`esModuleInterop` (what the tests use by default) + the one test that does specifically use `esModuleInterop`.

Does that look good to you?

(I was kinda hoping this could kill off ts-proto's `esModuleInterop` flag all together, but it looks like `long` still needs it, although granted they've had an ESM-compliant release recently that we need to upgrade to...)

**Comment by davidzhao** [comment]
@stephenh neither have I! I was skeptical if mixing require is allowed. Testing showed that it is a valid syntax.

`import *` sounds good to me!

**Comment by stephenh** [comment]
@davidzhao great! Let's see how this goes, I merged #540 and the release should be up soon. Thanks!

**Comment by davidzhao** [comment]
awesome!! thank you for the quick fix. appreciate your work on this library!

**Comment by Vincz** [comment]
Hey guys! Actually, version 1.110.1 breaks my config with the following error:

```
if (_m0.util.Long !== Long) {
             ^
TypeError: Cannot read properties of undefined (reading 'Long')
```

I'm using esbuild to build my typescript project.

Here is my tsconfig:

```json
{
    "compilerOptions": {
      "module": "es2015",
      "target": "esnext",
      "moduleResolution": "node",
      "sourceMap": true,
      "outDir": "dist",
    },
    "lib": ["es2015"]
  }
```

Here is my build script:
```js
const { argv } = require('process');

require('esbuild')
    .build({
        entryPoints: ['./src/index.ts'],
        outdir: './dist',
        bundle: true,
        format: 'esm',
        platform: 'node',
        external: ['./node_modules/*'],
        ...(argv.includes('--watch')
            ? {
                  watch: {
                      onRebuild: () => console.log('Rebuilding...'),
                  },
              }
            : {}),
    })
    .catch(() => {
        process.exit(1);
    });
```

and here is how I generate my protobuff file:
```
protoc --plugin=./node_modules/.bin/protoc-gen-ts_proto --ts_proto_out=./src ./protocol/*.proto --ts_proto_opt=env=node --ts_proto_opt=esModuleInterop=true --ts_proto_opt=forceLong=long
```

It's working if I revert back to 1.110.0.
Any idea?

**Comment by jonaskello** [comment]
Upgraded from `1.97.0` to `1.115.4` and our codebase is now broken in the way described by @Vincz. So we need to downgrade again. If this is working for anyone else could you please provide some info how to make it work?

**Comment by stephenh** [comment]
Fwiw I poked around in the esModuleInterop integration test:

https://github.com/stephenh/ts-proto/tree/main/integration/simple-esmodule-interop

And can't get it to fail on the `_m.util.Long` line. Note that, for this integration test, I'm specifically compiling the `simple.test.ts` to `.js` and then running the test from the `build/` to ensure its the emitted JS / `__importStar` / etc. code that's being exercised.

@jonaskello / @leppaott / @Vincz  can you poke around at that test and try to reproduce the failure that you're seeing? If we can at least get it reproduced then we should be able to think through/evaluate fixes. Thanks!

**Comment by aabluedragon** [comment]
Bug still exists on version "1.121.0"
```
if (_m0.util.Long !== Long) {
        ^
TypeError: Cannot read properties of undefined (reading 'util')
```

**Comment by Hellomik2002** [comment]
> Fwiw I poked around in the esModuleInterop integration test:
> 
> https://github.com/stephenh/ts-proto/tree/main/integration/simple-esmodule-interop
> 
> And can't get it to fail on the `_m.util.Long` line. Note that, for this integration test, I'm specifically compiling the `simple.test.ts` to `.js` and then running the test from the `build/` to ensure its the emitted JS / `__importStar` / etc. code that's being exercised.
> 
> @jonaskello / @leppaott / @Vincz can you poke around at that test and try to reproduce the failure that you're seeing? If we can at least get it reproduced then we should be able to think through/evaluate fixes. Thanks!

try run ```npm run start:debug```
