### ISSUE TITLE
Nestjs does not transform dates

### ISSUE THREAD

**Issue by alexvallecit** [stephenh/ts-proto#550]
When using the `--ts_proto_opt=nestJs=true` option it does not create the functionality to switch from `Timestamp` to `Date`.

**Comment by alex-w0** [comment]
Another approach is to convert date fields to ISO strings, if it helps you.
`new Date().toISOString()`

**Comment by stephenh** [comment]
Hi @alexvallecit ; yeah, you're right; this is a known issue with the NestJS infra and is discussed in #69.

Note that #69 has been open for awhile, but ~a month ago someone did finally figure out how to tell the protobufjs runtime to use ts-proto's custom encode/decode methods for things like dates, but unfortunately that insight has not been turned into a PR that works for all types yet.

If you're interesting in helping fix that, check that issue out.

Thanks!
