### ISSUE TITLE
Falsy values not encoded

### ISSUE THREAD

**Issue by moony-chen** [stephenh/ts-proto#563]
Hello there,

I have a proto file:
```
message Light {
    optional bool IsEnabled = 6;
    optional uint32 Brightness = 7;
}
```
the generated ts file:
```ts
export interface Light {
  IsEnabled: boolean;
  Brightness: number;
}

export const Light = {
  encode(message: Light, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
      if (message.IsEnabled === true) {
        writer.uint32(48).bool(message.IsEnabled);
      }
      if (message.Brightness !== 0) {
        writer.uint32(56).uint32(message.Brightness);
      }
      return writer;
    },
```

if I set the `IsEnabled` to `false`, the field is not encoded and the message is ignored by the light, if I manually remove the if check, it starts to work

**Comment by stephenh** [comment]
Hi @moony-chen s this on purpose; the protobuf spec says that default values (i.e. 0 for ints, false for booleans) should not be put on the wire, b/c the on the other side, the caller will treat "a missing int" as 0 anyway, so it saves space on the wire. Thanks!
