### ISSUE TITLE
use pnpm v7 install dependencies bug

### ISSUE THREAD

**Issue by LastKing** [stephenh/ts-proto#564]
issue repository: https://github.com/LastKing/ts-proto-pnpm-issue

<img width="807" alt="image" src="https://user-images.githubusercontent.com/8540374/167069469-732333b8-d4aa-46cd-a800-f685ec9330dc.png">

**Comment by stephenh** [comment]
@LastKing  I'm not really following; I see your screenshot, but the code looks fine, and I'm not following why pnpm would matter. Makes me think someone else is wrong.

**Comment by LastKing** [comment]
I just like use pnpm, i find the question and submitted this issue.

This may not be the problem of ts-proto.

 I'll pnpm ask...
 
Thank you for reply.

**Comment by stephenh** [comment]
Okay, let us know if you find anything out, but I'm going to close this for now. Thanks!
