### ISSUE TITLE
Official Buf plugin

### ISSUE THREAD

**Issue by Jake-RoundrockIO** [stephenh/ts-proto#569]
It would be awesome if you could also publish an official Buf registry plugin for users that utilize Buf's remote plugin and generation options with `ts-proto`.

Here's a Dockerfile that could potentially be used:

```Dockerfile
FROM node:16-alpine as builder

RUN npm install -g ts-proto

ENTRYPOINT ["protoc-gen-ts_proto"]
```

**Comment by stephenh** [comment]
@Jake-RoundrockIO that sounds great; my disclaimer is that I'm not personally a Buf user, and also anymore I heavily lean on ts-proto users/contributors themselves to scratch their own itches.

If you'd like to put a PR together that does this, that'd be amazing!

**Comment by Jake-RoundrockIO** [comment]
I'll look into it!

**Comment by Jake-RoundrockIO** [comment]
Bear with me as I'm for more used to GitLab CI/CD rather than GitHub Actions.

So I've created another job in the `.github/workflows/build.yml` file to build the Buf Plugin and push it to the Buf Registry. One question I have is how would I determine the current release version? Do you do that entirely through tags or does the `yarn semantic-release` command completely handle that? Any advice would be appreciated so I can correctly tag the plugin.

**Comment by evalsocket** [comment]
@Jake-RoundrockIO You can trigger your workflow on Tag/Release creation
```yaml
  release:
    types: [published]
``` 
or 
```yaml
  push:
    tags:        
      - v*.*.*
```
