### ISSUE TITLE
Protobufs won't decode because no pos on BufferWriter

### ISSUE THREAD

**Issue by yazfaz** [stephenh/ts-proto#57]
When trying to `decode` I never make it into the `while (reader.pos < end)` because `reader.pos` is `undefined`. 

It seems like the `encode` function is working. This is the encode call:
```
const message = MyProtbuf.encode({
  id: '123',
  url: 'test.com',
  params: { userId: '567' },
});
```
This the reader that is being created: 
```
BufferWriter {
  len: 22,
  head: Op {
    fn: [Function: noop],
    len: 0,
    next: Op { len: 1, next: [Op], val: 10 },
    val: 0
  },
  tail: Op {
    fn: [Function: writeStringBuffer],
    len: 3,
    next: undefined,
    val: '567'
  },
  states: null
}
```

Is there anything else I need to do to encode, so that the BufferWriter has a pos prop?

**Comment by stephenh** [comment]
`encode` returns a `Writer`, which you can call `.finish()` on to a get a buffer.

Then you can use that to create a `Reader` to decode.

I.e.

```
const message = MyProto.encode({ ... }).finish();
const decode = MyProto.decode(Reader.create(message));
```

In retrospect / looking at this with fresh eyes, `encode` should probably return the result of `.finish()` directly but it's getting late in the game to make a breaking change.

**Comment by yazfaz** [comment]
Ah, thank you! I do see that in the docs, but I didn't realize that was needed in all cases.
