### ISSUE TITLE
Support JSON wire format for well-known types

### ISSUE THREAD

**Issue by oyvindwe** [stephenh/ts-proto#571]
We have a webapp for a gRPC backend with a lot of types. In our scenario, using `fromPartial` is not desired, as this would add thousands of lines to our webapp client. Instead we are maintaining a fork of `ts-proto` that generates types that can be sent and received directly over HTTP, but over time several of the changes we have made in our fork have been included as various options, so we are now trying to move to vanilla `ts-proto`. The support is 90% in place using the following options:
`forceLong=string,env=browser,useOptionals=all,outputEncodeMethods=false,outputJsonMethods=false,outputClientImpl=false,onlyTypes=true,stringEnums=true,useDate=string`

However, we struggle with support for some well known types, e.g.:

- [`google.protobuf.FieldMask`](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#fieldmask) is a comma separated string in JSON, not a string array
- [`google.protobuf.Duration`](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#duration) is a special formatted string in JSON

We considered supporting `Duration` by adding `string` as a type alias, but for `FieldMask` the original type is lost.

For us it would make sense to add an option to generate types that are directly compatible with the JSON representation of well-known types. We are happy to provide a PR for this, but we would like some feedback on the idea before putting in the effort.

**Comment by stephenh** [comment]
@oyvindwe ah sure, that sounds like a good idea. I was initially a little hesitant b/c our well-known types support is good but also pretty complicated, but I think what you're asking only touch the "types only" output, so hopefully not too be too bad. A PR would be great!

**Comment by oyvindwe** [comment]
> I think what you're asking only touch the "types only" output, so hopefully not too be too bad.

That was s good point, so I made the new option requiring `onlyTypes=true`, which made the change very simple.

> A PR would be great!

Done! :)
