### ISSUE TITLE
optional map?

### ISSUE THREAD

**Issue by cprovatas** [stephenh/ts-proto#574]
First, thanks for all the work you are doing to maintain this project.  It's definitely the most powerful TS protobuf framework out there! 🙏 

Maybe it's a newb question, but is there a way to declare an optional map?  I didn't see any kind of wrapper type for that. Any possible alternatives aside from using struct?

**Comment by stephenh** [comment]
Hey @cprovatas , honestly I'm not sure if optional maps are allowed in proto3 or not. Feel free to try it, and report back if it does/does not work.

**Comment by cprovatas** [comment]
It's doesn't convert to optional unfortunately.  Perhaps this could be addressed by something  like https://github.com/stephenh/ts-proto/issues/397#issue-1059251202

**Comment by stephenh** [comment]
Ah yeah, @cprovatas that #397 should have been closed as fixed, b/c we have `useOptionals=all` now; you could try that.

**Comment by cprovatas** [comment]
nice, thanks!
