### ISSUE TITLE
Barrel + exportCommonSymbols + NestJS import conflict

### ISSUE THREAD

**Issue by arustamyansv** [stephenh/ts-proto#580]
Hello,

I have the following file structure for proto files
`/VENDOR/MICROSERVICE/MODULE/VERSION/*.proto`

Here is a list of proto files for CRUDL
```
entity.proto
create.proto
update.proto
delete.proto
list.proto
get.proto
service.proto
```

And as a result, I'd love to have a barrel or something similar assembled to have a single import point.

I'm utilizing NestJS as a framework for microservice so there is `*_PACKAGE_NAME` generated in each file. 
As a result, barrel fails cause of conflicts.

So the question is - by any chance is it possible to get `*_PACKAGE_NAME` only inside the file service is defined?

If not and it looks like it's not, do you think it's a good idea to add? 
Or probably just add barrel generation from within the ts-proto?

**Comment by stephenh** [comment]
Hi @arustamyansv , yeah that makes sense, we have an existing issue #212 that tracks this ask, but haven't had anyone put together a PR yet. Thanks!
