### ISSUE TITLE
Job failure: push to buf registry

### ISSUE THREAD

**Issue by paralin** [stephenh/ts-proto#608]
Latest commit failed one of the GitHub actions: https://github.com/stephenh/ts-proto/runs/7157132641?check_suite_focus=true

```
name invalid: invalid plugin version: invalid_argument: "v-0" is not a valid semantic version
```

Maybe related to dc1fb7e766ed4115d026e7ff0e9a9480c1e42380

**Comment by stephenh** [comment]
Thanks for the report! Fixed by teaching the buf workflow to skip chore/non-release builds:

https://github.com/stephenh/ts-proto/commit/92143dfca0c980bee3d2802c6987bf13199c00c5
