### ISSUE TITLE
import "base.proto" to from "./base.js"

### ISSUE THREAD

**Issue by eyouyou** [stephenh/ts-proto#611]
window cmd: 
`protoc  --plugin=protoc-gen-ts_proto=%PLUGIN% --ts_proto_out=%OUTDIR% --ts_proto_opt=esModuleInterop=true,outputClientImpl=grpc-web,env=browser ./*.proto 
`

proto files:
`base.proto` and `other.proto`

in other.proto:
`import "base.proto" `

👇
generates `base.ts` / `other.ts` 

in other.ts:
` import {} from "./base.js"`

should be ` import {} from "./base"`？

**Comment by zsmatrix62** [comment]
I encounters this probem today as well beacause of the latest update [#602](https://github.com/stephenh/ts-proto/pull/602).
downgrade `ts-proto` to [v1.115.5](https://github.com/stephenh/ts-proto/releases/tag/v1.115.5) then works.

**Comment by stephenh** [comment]
Hey @eyouyou , @zsmatrix62 thanks for filing the issue! We're working on a fix.

**Comment by paralin** [comment]
If you were to upgrade to TypeScript 4.7.x it would work :)

But I understand that's not an option for everyone.

**Comment by stephenh** [comment]
This should be fixed in 1.117.0; thanks @paralin !

**Comment by zsmatrix62** [comment]
thank you guys.
