### ISSUE TITLE
importSuffix doesn't work

### ISSUE THREAD

**Issue by hiromaily** [stephenh/ts-proto#613]
I waited for this functionality `importSuffix` then tried, but generated files were not changed at all.

I'm using script to generate proto files
```
 proto_dirs=$(find $COSMOS_PROTO_DIR -path -prune -o -name '*.proto' -print0 | xargs -0 -n1 dirname | sort | uniq)
 for dir in $proto_dirs; do
   $PROTOC \
   --plugin="$(yarn bin protoc-gen-ts_proto)" \
   --ts_proto_out="$OUT_DIR" \
   --proto_path="$COSMOS_PROTO_DIR" \
   --proto_path="$THIRD_PARTY_PROTO_DIR" \
   --ts_proto_opt="esModuleInterop=true,forceLong=long,useOptionals=all,outputTypeRegistry=true,importSuffix=.js" \
   $(find "${dir}" -maxdepth 1 -name '*.proto')
 done
```

package.json
```
  "devDependencies": {
    "grpc_tools_node_protoc_ts": "^5.3.2",
    "grpc-tools": "^1.11.2",
    "ts-proto": "^1.117.0",
    "typescript": "^4.7.4"
  }
```

**Comment by stephenh** [comment]
@hiromaily I'm not sure why that wouldn't work; your `ts_proto_opt` looks fine. @paralin any ideas on ^? Otherwise @hiromaily let us know if you find out why it's not working.

**Comment by paralin** [comment]
It certainly does work, and there are integration tests to confirm that + I'm using the feature: https://github.com/aperturerobotics/protobuf-project/blob/starpc/Makefile#L119

@hiromaily what did you expect to happen vs. what happened?

The option controls the .js import suffix when importing other Protobuf .ts files.

**Comment by stephenh** [comment]
Going to close this out for now @hiromaily , but let us know if there is something we're missing.

**Comment by hiromaily** [comment]
@paralin 
I expect that generated file must import package files with extension `.js`, but it didn't

**Comment by paralin** [comment]
@hiromaily It will only import other files generated by ts-proto with the .js suffix

Which imports were you expecting to have the .js suffix that did not?

Please double-check you're on the latest ts-proto as well, this was only just added.
