### ISSUE TITLE
[question] promise based client for node + grpc-js ?

### ISSUE THREAD

**Issue by jkristia** [stephenh/ts-proto#614]
I'm trying to create a node / typescript gRPC client. I am not familiar with gRPC, so I found an example that uses grpc-js.
When I generate the .proto with the `--ts_proto_opt=outputServices=grpc-js` then the generated client's methods have a callback. 
```typescript
export interface GreeterClient extends Client {
  /** Sends a greeting */
  sayHello(
    request: HelloRequest,
    callback: (error: ServiceError | null, response: HelloReply) => void
  ): ClientUnaryCall;

```
Is it possible to instead generate something like
```typescript
export interface GreeterClient extends Client {
  /** Sends a greeting */
  sayHello(
    request: HelloRequest,
  ): Promise<{error: ServiceError | null, response: HelloReply}>;
```

Which makes for a cleaner `async/await` implementation ?
I think I looked through all the many options and didn't find any flag for this

**Comment by paralin** [comment]
> I'm trying to create a node / typescript gRPC client

You probably want to use `--ts_proto_opt=outputServices=default,outputServices=generic-definitions`

This uses the Promises like you describe.

If you want AsyncIterable for the streaming use `--ts_proto_opt=useAsyncIterable=true`

See: https://github.com/aperturerobotics/starpc which is an implementation using the AsyncIterable for an example.

**Comment by jkristia** [comment]
I apologize is this as a noob question, but I have never looked at gRPC before.

If I don't add the `grpc-js` option, then the generated code expects a `rpc` passed in the constructor, and I was not able to find any working examples where this is used.

```typescript
export class GreeterClientImpl implements Greeter {
  private readonly rpc: Rpc;
  constructor(rpc: Rpc) {
    this.rpc = rpc;
    this.sayHello = this.sayHello.bind(this);
  }
  sayHello(request: HelloRequest): Promise<HelloReply> {
```
The example given in the readme leaves out the connection part
```typescript
    // Using passThrough as the serialize and deserialize functions
    conn.makeUnaryRequest(path, passThrough, passThrough, data, resultCallback); <-- how to define conn
  });

```

**Comment by paralin** [comment]
@jkristia The "Rpc" interface is what protobuf-ts expects your RPC library to implement.

By "I'm trying to create a node GPRC client" I assumed you meant you're building it yourself from scratch?

If you're just trying to use grpc-js, then the grpc-js interfaces are as they are according to how grpc-js is designed.

If you were looking for an implementation of `Rpc` check out starpc or grpc-js or any of the other supported RPC libs.

**Comment by jkristia** [comment]
I understand the `rpc` interface is what is expected, I just have still not been able to find a single example of how to use `grpc-js` (or [starpc](https://github.com/aperturerobotics/starpc) ) to be used as the `rpc` input for the generated client class. I will keep digging

**Comment by paralin** [comment]
For `starpc` there are two examples:

 - https://github.com/aperturerobotics/starpc/blob/main/integration/integration.ts
 - https://github.com/aperturerobotics/starpc/blob/main/e2e/e2e.ts

**Comment by siendoricardo** [comment]
If you don't find any solution, I did a work out with this: https://github.com/siendoricardo/ddd/blob/7e94cfd744144e5b7a26a0ca446fbfe4998a2944/src/utilities/GUtils.ts#L25

```typescript
        const operation = await GUtils.extract<PointsLeaderboard>(res => GRPCService.getP2ePointsService().getLeaderboard(
            new LeaderboardRequest()
                .setClientId(clientId)
                .setSkip(skip)
                .setLimit(limit),
            res
        ));
```

**Comment by stephenh** [comment]
Thanks for the help here @paralin ! For now I'm closing to this out.

Fwiw I added a disclaimer to ts-proto's readme that it's not an out-of-the-box rpc framework, and linked to starpc and nice-grpc as examples.

Thanks @jkristia !
