### ISSUE TITLE
ESM packages still not working because of protobufjs/minimal

### ISSUE THREAD

**Issue by siendoricardo** [stephenh/ts-proto#615]
The package `protobufjs/minimal` is being import as `import * as _m0 from "protobufjs/minimal";`
(Produced the following error):

```
/home/.../WebstormProjects/.../node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:366
    throw new ERR_MODULE_NOT_FOUND(
          ^
```
And it is required to be imported as follows: `import _m0 from "protobufjs/minimal.js";`

**Comment by paralin** [comment]
Good to go in #616  :)
