### ISSUE TITLE
eslint: empty interface

### ISSUE THREAD

**Issue by tetra12** [stephenh/ts-proto#622]
Hello I've started to use your project and so far am happy :smiley: with it.

However, when I generate an empty interface like this `message Empty {}`, I'm getting the following ts: 

```typescript
// eslint-disable-next-line @typescript-eslint/no-empty-interface
export interface Empty {}
```

`ESLint` in VSCode complains on that and I need to manually add the commented line to work around the error.

Not sure if its a bug or a feature, but certainly would be happy NOT to make hand :hand: changes in the generated code

**Comment by stephenh** [comment]
All of the ts-proto-generated files should have an `eslint-disable` at the top of them:

https://github.com/stephenh/ts-proto/blob/81187488edbbe7b1c8e7028e0bc8f3a8005a97c8/integration/avoid-import-conflicts-types-only/simple2.ts

Which should solve this?

**Comment by tetra12** [comment]
> All of the ts-proto-generated files should have an `eslint-disable` at the top of them:

Nah, this is not the case. I'm getting the following 
```bash
// @generated by protobuf-ts 2.7.0
// @generated from protobuf file "common.proto" (package "pocket.v1", syntax proto3)
// tslint:disable
```
Es-Lint complains about this an I have to manually change every generated file with the `message Empty {}` code

**Comment by stephenh** [comment]
@tetra12 wrong project: https://github.com/timostamm/protobuf-ts :-)
