### ISSUE TITLE
Protobuf wire format

### ISSUE THREAD

**Issue by khi195** [stephenh/ts-proto#626]
Hey, I'm migrating from grpc-web, and i've been using the protobuf wire format in my JS code, 

proto.com.foo.bar.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setAddress(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};

is there a command or flag which will output to this type of format.

**Comment by paralin** [comment]
@khi195 the `encode` functions encode to protobuf.

**Comment by paralin** [comment]
Closing, but feel free to msg here if this didn't answer your question.
