### ISSUE TITLE
Recent change broke client-streaming methods

### ISSUE THREAD

**Issue by paralin** [stephenh/ts-proto#628]
After upgrading ts-proto something causes client->server streams to return AsyncIterable instead of Promise:

```
diff --git a/echo/echo.pb.ts b/echo/echo.pb.ts
index 406004f..2a7e00d 100644
--- a/echo/echo.pb.ts
+++ b/echo/echo.pb.ts
@@ -103,7 +103,7 @@ export interface Echoer {
   /** EchoServerStream is an example of a server -> client one-way stream. */
   EchoServerStream(request: EchoMsg): AsyncIterable<EchoMsg>
   /** EchoClientStream is an example of client->server one-way stream. */
-  EchoClientStream(request: AsyncIterable<EchoMsg>): Promise<EchoMsg>
+  EchoClientStream(request: AsyncIterable<EchoMsg>): AsyncIterable<EchoMsg>
   /** EchoBidiStream is an example of a two-way stream. */
   EchoBidiStream(request: AsyncIterable<EchoMsg>): AsyncIterable<EchoMsg>
   /** RpcStream opens a nested rpc call stream. */
@@ -138,7 +138,7 @@ export class EchoerClientImpl implements Echoer {
     return EchoMsg.decodeTransform(result)
   }
 
-  EchoClientStream(request: AsyncIterable<EchoMsg>): Promise<EchoMsg> {
+  EchoClientStream(request: AsyncIterable<EchoMsg>): AsyncIterable<EchoMsg> {
     const data = EchoMsg.encodeTransform(request)
     const promise = this.rpc.clientStreamingRequest(
       'echo.Echoer',
diff --git a/package.json b/package.json
index a838df4..2810cf2 100644
--- a/package.json
+++ b/package.json
@@ -68,7 +68,7 @@
     "eslint-config-prettier": "^8.5.0",
     "prettier": "^2.7.1",
     "rimraf": "^3.0.2",
-    "ts-proto": "^1.117.0",
+    "ts-proto": "^1.121.0",
     "typescript": "^4.7.4",
     "utf-8-validate": "^5.0.9"
   },
```

```
		--ts_proto_opt=esModuleInterop=true \
		--ts_proto_opt=fileSuffix=.pb \
		--ts_proto_opt=importSuffix=.js \
		--ts_proto_opt=forceLong=long \
		--ts_proto_opt=oneof=unions \
		--ts_proto_opt=outputServices=default,outputServices=generic-definitions \
		--ts_proto_opt=useAsyncIterable=true \
		--ts_proto_opt=useDate=true \
```

I'll try to figure out which commit did it.

**Comment by paralin** [comment]
Reverting commit  d3e7f1f4aac12db87c54d6357e557a351c96a2ca fixes it

cc @luhuaei

**Comment by paralin** [comment]
Found the issue; why was it changed to return an Observable if clientStreaming? The response is the server->client component, it doesn't matter if the client is streaming or not.

https://github.com/stephenh/ts-proto/commit/d3e7f1f4aac12db87c54d6357e557a351c96a2ca#r79607248

**Comment by luhuaei** [comment]
> The response is the server->client component, it doesn't matter if the client is streaming or not.

You are right, Return Observable as client steaming reponse type, because
-  current ts-proto generate grpc-web stream only support Observable type #337
- last pull request only support bidirectional stream. #617 
- but client streaming like bidirectional stream, so I reuse relative function.

I make #631 to ts-proto support Promise, so that don't mix Observable and Promise.

**Comment by paralin** [comment]
"current ts-proto generate grpc-web stream only support Observable type" - I don't see how that's relevant

"last pull request only support bidirectional stream." - Then why are client->server streams in the tests? And why was it changed so that it returns Observable for the response unconditionally if the client is streaming??

"but client streaming like bidirectional stream, so I reuse relative function." I have no idea what this sentence means

Just for reference doing that completely broke a lot of stuff in downstream projects.

**Comment by stephenh** [comment]
Yeah, @paralin really appreciate jumping in here; @luhuaei are you fine with @paralin 's proposal ^?

Fwiw I think it makes sense, to restore `main` to working behavior, granted will be a little more work on your side.

**Comment by paralin** [comment]
I'm happy to help rebase things so that @luhuaei WIP branch is back to the way it currently is post-revert on the PR branch
