### ISSUE TITLE
How to generate camel_case with json_name option?

### ISSUE THREAD

**Issue by kanziw** [stephenh/ts-proto#635]
I tried 4 different options in `snakeToCamel`, but I cound not found for my requirement.
- camel case
- use json_name if exist.
- It works at `fromJSON` & `toJSON`

with below [proto](https://github.com/kanziw/ts-proto/blob/f3c64f2fcfd4ee9c3d8e3b307461771dd84742ad/services/echo/v1/echo.proto),
```proto
message EchoRequest {
  string msg = 1;
  string long_message = 2 [json_name = "long"];
}

message EchoResponse {
  string want_to_camel_case = 1;
}
```

with [buf](https://github.com/kanziw/ts-proto/blob/f3c64f2fcf/buf.gen.yaml),

### 1. `snakeToCamel=false`

Use camel_case (in proto), I expected. [sample](https://github.com/kanziw/ts-proto/blob/f3c64f2fcfd4ee9c3d8e3b307461771dd84742ad/gen/snake-case-false/echo/v1/echo.ts)

### 2. `snakeToCamel=json`

Use json_name, but also use camelCase too. [sample](https://github.com/kanziw/ts-proto/blob/f3c64f2fcf/gen/snake-case-json/echo/v1/echo.ts)

### 3. `snakeToCamel=keys`

Use snakeCase (with json_name), I expected. [sample](https://github.com/kanziw/ts-proto/blob/f3c64f2fcf/gen/snake-case-keys/echo/v1/echo.ts)

### 4. `snakeToCamel=json,keys`

It equals `snakeToCamel=json` option?! [sample](https://github.com/kanziw/ts-proto/blob/f3c64f2fcf/gen/snake-case-json-keys/echo/v1/echo.ts)

---

I think there is a bug in situation 2.

**Comment by stephenh** [comment]
Hi @kanziw ; sorry I'm not 100% following how ts-proto doesn't support what you're looking for; if anything "camel case", "use json_name if available", sounds like the default behavior, i.e. if you just don't set `snakeToCamel` at all, does that do what you want?

While looking in to this, I did discover a bug in `snakeToCamel`, which is that `,` cannot be used as a separator, b/c it's already used as a separate between different flags.

So, I'm making a change to use `_` as a separate (kinda ugly but :shrug: ... cc @paralin for any good ideas?):

https://github.com/stephenh/ts-proto/pull/648

So, I think that will fix your option 4 output. Maybe let the ^ PR land and you can re-do your test/examples with the updated code, and then let us know if there is still something missing.

I'm hoping that what you're really asking for is the default ts-proto output, which is effectively `snakeToCamel=json,keys` (if the user doesn't set anything), but b/c you were _trying_ to set `snakeToCamel=json,keys` but there was a bug in the `,` parsing, that the behavior ended up being weird/undefined.

**Comment by kanziw** [comment]
(I can't English well, sorry 🙏)

Thanks for you reply. @stephenh 

I bumped ts-proto version up to v1.121.5 and use `keys_json` as option. :) https://github.com/kanziw/ts-proto/commit/4a78e35baf833cdc9195929e44dea95c2759bfb0

---

You said,
> if anything "camel case", "use json_name if available", sounds like the default behavior

But, I couldn't find any options in snakeToCamel.

I want.. with below message,
```proto
message EchoRequest {
  string msg = 1;
  string long_message = 2 [json_name = "long"]; // Important! json_name attribute is here!
  string want_to_camel_case = 3;
}
```

`EchoRequets.fromJSON` should work from
```json
{
  "msg": "msg",
  "long": "long",
  "want_to_camel_case": "want_to_camel_case"
}
```

to
```js
{
  msg: "msg",
  long_message: "long",
  want_to_camel_case: "want_to_camel_case",
}
```

AND `EchoRequets.toJSON` should work from
```js
{
  msg: "msg",
  long_message: "long",
  want_to_camel_case: "want_to_camel_case",
}
```

to
```json
{
  "msg": "msg",
  "long": "long",
  "want_to_camel_case": "want_to_camel_case"
}
```

---

at #648 , you said
> Note that to use the `json_name` attribute, you'll have to use the `json`.

So, I expected that `snakeToCamel=json` option satisfied me.

This is generated stubs with `json` option. https://github.com/kanziw/ts-proto/blob/a28b543f6980331c05e7e4ce9d199caa7fcbd278/gen/snake-case-json/echo/v1/echo.ts#L16:L35
```ts
export const EchoRequest = {
  fromJSON(object: any): EchoRequest {
    return {
      msg: isSet(object.msg) ? String(object.msg) : "",
      long_message: isSet(object.long) ? String(object.long) : "",
      want_to_camel_case: isSet(object.wantToCamelCase)
        ? String(object.wantToCamelCase)
        : "",
    };
  },

  toJSON(message: EchoRequest): unknown {
    const obj: any = {};
    message.msg !== undefined && (obj.msg = message.msg);
    message.long_message !== undefined && (obj.long = message.long_message);
    message.want_to_camel_case !== undefined &&
      (obj.wantToCamelCase = message.want_to_camel_case);
    return obj;
  },
};
```

I want use stubs like,
```diff
export const EchoRequest = {
  fromJSON(object: any): EchoRequest {
    return {
      msg: isSet(object.msg) ? String(object.msg) : "",
      long_message: isSet(object.long) ? String(object.long) : "",
-      want_to_camel_case: isSet(object.wantToCamelCase)
-        ? String(object.wantToCamelCase)
+      want_to_camel_case: isSet(object.want_to_camel_case)
+        ? String(object.want_to_camel_case)
        : "",
    };
  },

  toJSON(message: EchoRequest): unknown {
    const obj: any = {};
    message.msg !== undefined && (obj.msg = message.msg);
    message.long_message !== undefined && (obj.long = message.long_message);
-    message.want_to_camel_case !== undefined &&
-      (obj.want_to_camel_case = message.want_to_camel_case);
+    message.want_to_camel_case !== undefined &&
+      (obj.want_to_camel_case = message.want_to_camel_case);
    return obj;
  },
};
```

I hope to show this codes with integration test, but It's hard to me. 😢

**Comment by stephenh** [comment]
Hi @kanziw , yeah I believe what you're asking for is:

a) have toJSON/fromJSON use snake case, _unless_
b) jsonName is set

Per above, we historically have not done this b/c protobuf doesn't give an easy way to tell "did the user set jsonName?", b/c it _always_ sets `jsonName`.

That said, I put in a hueristic in #653 that tries to detect "did the user _really_ set `jsonName` or is protoc just defaulting it (to something camel cased) for us?", and based on that, will use `jsonName` even with `snakeToCamel=false`, which I believe is what you want.
