### ISSUE TITLE
update buf.build/stephenh/plugins/ts-proto plugin

### ISSUE THREAD

**Issue by TonyPapousekLC** [stephenh/ts-proto#645]
Howdy,

Could you please update <https://buf.build/stephenh/plugins/ts-proto> to match the current production release?

Looks like the "Push Docker image to Buf Registry" is being skipped:
<https://github.com/stephenh/ts-proto/runs/7680401769?check_suite_focus=true>

**Comment by TonyPapousekLC** [comment]
Looks like the "Push Docker image to Buf Registry" is being skipped:
<https://github.com/stephenh/ts-proto/runs/7680401769?check_suite_focus=true>

**Comment by stephenh** [comment]
Thanks for pointing this out; the auto-publish step had a typo in it. This should be fixed. Thanks!

**Comment by TonyPapousekLC** [comment]
Thanks for the quick turnaround!
