### ISSUE TITLE
Support bytes as Buffer (optimal under node)

### ISSUE THREAD

**Issue by dolsup** [stephenh/ts-proto#65]
https://github.com/protobufjs/protobuf.js#usage

protobufjs parses protobuf `bytes` as `Buffer` on Node.js on default behavior.
So there is some incompatibility between imported ts interface created by `protoc-gen-ts_proto` and actual type parsed by protobufjs on node runtime.

I think that we need a option like `--env=node|browser`.

**Comment by stephenh** [comment]
Yep @dolsup I agree that makes sense. Do you want to take a crack at adding the option/PR? I can point around to some things to change.

**Comment by dolsup** [comment]
@stephenh Yes I do. I've setup the project and now reading some codes.

**Comment by stephenh** [comment]
So @jcarver989 submitted a PR recently that reminded/taught me that in Node the `Buffer` type extends `Uint8Array`. ...given that, are the `Uint8Array`s still okay (i.e. for return values)? Maybe/maybe not? Just thought I'd ask / double check before you get too far on it.

**Comment by dolsup** [comment]
Yes, that is right. `Buffer` extends `Uint8Array` so the casting itself gets no error but still we cannot use Uint8Array type directly. We have to manually cast every single Uint8Array type to Buffer in codes because Uint8Array has a different interface from Buffer's one.

**Comment by stephenh** [comment]
@dolsup cool, makes sense. I think where you'd want to introduce a conditional is here:

https://github.com/stephenh/ts-proto/blob/master/src/types.ts#L86

We already have some lines there that branch on "if config option" for the long behavior.

**Comment by stephenh** [comment]
I merged #72 and released this as v1.22.0. Thanks!
