### ISSUE TITLE
Would it be possible to generate union type from protobuf via ts-proto?

### ISSUE THREAD

**Issue by magician-margatroid** [stephenh/ts-proto#652]
Hi, I'm modeling with protobuf and ts-proto, they are nice and so far so good, but I was stuck with an issue to generate a union type, and wasn't able to find a hint from doc/issues:
```TypeScript
// E.g., for this interface EventRequest
interface EventRequest {
  uuid: string;
  pathSegments: (string | number)[];
}
// There could be plain JS objects like:
{
  uuid: "691a805d-a409-4b08-9674-726e8534064b",
  pathSegments: [1, 2, 3, 4, 5],
};
{
  uuid: "247ae0cf-4a45-48b7-afd8-09910e04cccb",
  pathSegments: ["request", "payload", "option", "type"],
};
```
But I wasn't sure whether or how it would be possible to generate from protobuf to deal with `pathSegments` property as union type `(string | number)[]`.
```protobuf
message EventRequest {
  string uuid = 0;
  repeated string pathSegments = 1; // appearantly, here it's only string type.
}
```

Thanks
Best Regards

**Comment by stephenh** [comment]
Hi @magician-margatroid ; fwiw it sounds like you're trying to "work backwards" by having an ideal TypeScript type that you want, and then figuring out what the protobuf schema for that would be.

That is probably going to be difficult, b/c the TS type system is just so much more expressive than protobuf. Both probably b/c of age (i.e. protobuf is 20 years old at this point) and also valid constraints, i.e. protobuf has to put everything on the wire in an efficient/deterministic manner, which `tsc` doesn't have to worry about it.

Anyway, you'll probably run into these sort of things a lot, i.e. right, protobuf does not support union types. The closest thing afaiu is one ofs:

https://developers.google.com/protocol-buffers/docs/proto3#oneof

I don't think there is much for ts-proto to do here; a more restrictive type system is just one of the pros/cons of using protobuf as a wire format.

**Comment by magician-margatroid** [comment]
Thx @stephenh, really good to know the great insights and I got it. I'll continue to pursue with what you've suggested, and think with the mental model in protobuf perspective.

Best Regards
