### ISSUE TITLE
Is it possible to output classes instead of interfaces for Message?

### ISSUE THREAD

**Issue by xiaoyu-tamu** [stephenh/ts-proto#655]
I'm using nest.js and it would be nice to output class instead of interface so i can reused them in DTO and swagger definition

```
export interface SignInRequest {
  email: string;
  password: string;
}

export interface SignInResponse {
  token: string;
}
```

```
export class SignInRequest {
  email: string;
  password: string;
}

export class SignInResponse {
  token: string;
}
```

**Comment by stephenh** [comment]
@xiaoyu-tamu hey! I mean, "anything is possible" :-) but no there are no flags for that today.

Fwiw I'm pretty sure we have people using ts-proto with Nest.JS output and it doesn't have to be classes? Not sure.

I'm not 100% opposed to a new `useClasses=true` flag, but in theory one of ts-proto's main selling points was that it didn't use classes. 

If you want to try a PR to see how easy/hard it is to do, that'd be cool.

**Comment by paralin** [comment]
Why do you want classes? They have no benefit in Typescript over basic interfaces.

If you want to add some custom behavior you can always make a class implementing the message interfaces.

**Comment by xiaoyu-tamu** [comment]
Hi @paralin,

My usecase is Dependency Injection with nestjs.

I can't use interface here because TypeScript does not store metadata about interfaces

<img width="843" alt="image" src="https://user-images.githubusercontent.com/33362998/185276160-ebb1addc-1d89-4b4c-9b9e-0576abccfbb4.png">

if `SignInResponse` is a class, I can pass it to `ApiCreatedResponse` without a class wrapper

**Comment by xiaoyu-tamu** [comment]
Thanks @stephenh I ended up patched this package with `pnpm patch` since it just a simple feature. I don't want to break the goal of this project. XD

> Interfaces over classes

**Comment by paralin** [comment]
@xiaoyu-tamu If it's an easy enough compiler option to add i don't see why it would be a problem to allow ts-proto to emit classes.
