### ISSUE TITLE
Feature Request: make child messages not undefinedable

### ISSUE THREAD

**Issue by TasukuUno** [stephenh/ts-proto#670]
I like ts-proto because all fields are not optional by default. I understand that they must be treated as optional in proto3 but it is hard not to be able to express in the proto file whether a field will be undefined or not.
So, I would be happier if child messages were also not undefinedable!!

## example proto

```proto
syntax = "proto3";

package example;

message Root {
  string requiredString = 1;
  Child requiredChild = 2;
}

message Child {
  string requiredString = 1;
}
```

## now

```ts
const root: Root = someApi();

root.requiredString; // required
root?.requiredChild.requiredString;  // requiredChild is Child | undefined
    ^^^
```

## expected

```ts
const root: Root = someApi();

root.requiredString; // required
root.requiredChild.requiredString;  // required
```

## how?

Is it possible to do like this...?

```ts
export interface Root {
  requiredString: string;
  requiredChild: Child;
                 ^^^^^
}

export interface Child {
  requiredString: string;
}

function createBaseRoot(): Root {
  return { requiredString: "", requiredChild: createBaseChild() };
                                             ^^^^^^^^^^^^^^^^^^^^^^^
}
```

What do you think about this feature? Should we add an option to not make it breaking change?

**Comment by stephenh** [comment]
A wrinkle would be cycles, i.e.:

```
message Author {
  Book favoriteBook = 1;
}

message Book {
  Author parentAuthor = 1;
}
```

I believe that the Java bindings might handle this (avoiding cycles) by having immutable "null objects", i.e.:

```
const nullAuthor = createBaseAuthor();
const nullBook = createbaseBook();

function createBaseAuthor(): Author {
  return { favoriteBook: nullBook };
}

function createBaseBook(): Book {
  return { parentAuthor: nullAuthor }
}
```

However:

a) that requires the types to be immutable, i.e. the `nullAuthor` is now shared and any mutations would be global (iirc the Java code handled this by requiring mutations through builders, i.e. `author.toBuilder().set(...).build()`, and

b) even then the order that `nullAuthor` and `nullBook` are instantiated in seems like a complexity.

So, dunno, between not being immutable and cycle issues, I'm not sure the null object approach that the Java protobuf code used (to my recollection; it's been awhile) will work for ts-proto.

...another approach would be to cache, i.e.:

```
function createBaseAuthor(cache? = {}): Author {
  return cache["Book"] ??= { favoriteBook: cache["Book"] || createBaseBook(cache) };
}

function createBaseBook(cache? = {}): Book {
  return cache["Author"] ??= { parentAuthor: cache["Author"] || createBaseAuthor(cache) }
}
```

...but that would mean you'd have something like:

```
const b = Book.fromPartial({});
b.author.favoriteBook === b
```

Which will probably infinite loop/cycle when serializing `b` to the wire.

...

So, dunno, maybe this approach would only work on schemas that don't have cycles, and we somehow tell/warn the user about it.

Also, even more fundamentally proto3's `optional` keyboard (which was introduced in 3.15) AFAIU only applies to scalars, so it's not clear to me that having:

```
message Root {
  optional Child optionalChild = 1;
  Child requiredChild = 2;
}
```

Would even be a valid schema; maybe your suggestion is to not bother with the `optional Child optionalChild`  and just assume all messages are required, but that doesn't seem right.

Dunno, thinking about it, currently it seems unlikely this is something we should implement.

**Comment by TasukuUno** [comment]
@stephenh Thanks for your detailed explanation.
Oh, is it possible to express circular dependencies between messages? Sorry, I didn't know that...!! Then I completely understand that it is difficult.

> Would even be a valid schema; maybe your suggestion is to not bother with the optional Child optionalChild and just assume all messages are required, but that doesn't seem right.

Yes, another thing I didn't understand was the purpose of the proto3's `optional` keyword. It is not so important to know a value is `""` or `undefined` at least for a TypeScripter like me. But I think it is more important to share required/optional specs between sender and receiver... But it is off-topic.

I also think this should not be implemented and will close this! Thank you!
