### ISSUE TITLE
grpc-js generated client constructor missing some allowed options

### ISSUE THREAD

**Issue by thomasboyt** [stephenh/ts-proto#693]
Small type generation bug (I hope to contribute a fix, but wanted to make sure to open an issue in case I forget!). For grpc-js generated clients, the following constructor [is used](https://github.com/stephenh/ts-proto/blob/main/src/generate-grpc-js.ts#L239):

```
new (
  address: string,
  credentials: ${ChannelCredentials},
  options?: Partial<${ChannelOptions}>,
): ${serviceDesc.name}Client;
```

However, `options` here is not correct: it should use the `ClientOptions` type (exported from grpc-js) instead, which is `Partial<ChannelOptions>` plus some extra fields that you can pass to a client constructor (see https://grpc.github.io/grpc/node/grpc.Client.html).

Very minor bug in the grand scheme of things and easy to work around since it's just a type bug, but I think an easy fix unless I'm missing something.

**Comment by stephenh** [comment]
@thomasboyt hey! Sorry for the late reply, I can only triage ts-proto issues every other week or so...

It'd great if you could submit a PR for this!

I think the fix would be around here:

https://github.com/stephenh/ts-proto/blob/main/src/generate-grpc-js.ts#L239

Thanks!
