### ISSUE TITLE
provide a method to retrieve the protobuf.Any compatible type id

### ISSUE THREAD

**Issue by mikonse** [stephenh/ts-proto#696]
Currently the method to implement protobuf.Any serialization and deserialization using ts-proto is a bit cumbersome as only the top level package name is exported under `protobufPackage`. This means one has to manually construct the correct type url when serializing and checking whether the protobuf Any is wrapping a specific message type.

I'd propose adding a new method to the generated message Objects:
`getTypeUrl: (typeUrlPrefix?: string) => string`
Similar to the generated code of protobufjs.

E.g. for a message `Message` we'd add the method like
```typescript
getTypeUrl(typeUrlPrefix?: string): string {
  if (typeUrlPrefix === undefined) {
    typeUrlPrefix = "type.googleapis.com";
  }
  return typeUrlPrefix + `/${protobufPackage}.Message`;
};
```

This feature would make it easier to write custom protobuf Any serializing utilities and make it easier to check whether an Any wrapper contains a specific type (comparable to how the official protoc generates code for C++ where we can do something like `anyMessage.Is<SomeMessageType>()`).

If this feature is something that would be appreciated and useful I'd be happy to try and write some code for it.

Edit:
After discovering the `--ts_proto_opt=outputTypeRegistry=true` option this feature is obsolete, I'll close this issue.

**Comment by stephenh** [comment]
Hey @mikonse ! I only get a chance to catch up on ts-proto issues every other week or so, but glad you found `outputTypeRegistry` and that it will work for you. Thanks for coming back and self-closing the issue. :-)
