### ISSUE TITLE
Lowercasing does not lowercase "API" of FindAPIKeys, for example.

### ISSUE THREAD

**Issue by iangregsondev** [stephenh/ts-proto#698]
Hi,

I have a GRPC endpoint like so

```
 rpc FindAPIKeys(FindAPIKeysRequest) returns (FindAPIKeysResponse) {}
```

The type that is creates is the following (notice the upper case API)

```
  findAPIKeys(request: FindAPIKeysRequest, metadata?: Metadata): Observable<FindAPIKeysResponse>;
```

This actually fails because of the grpc Options are set to lowercase see https://github.com/grpc/grpc-node/blob/master/packages/proto-loader/README.md

The valid types is (if I change it manually it works :-) )

```
  findApiKeys(request: FindAPIKeysRequest, metadata?: Metadata): Observable<FindAPIKeysResponse>;
```

Anybody know if there is a way around this ?

Thanks in advance

Ian

**Comment by iangregsondev** [comment]
I would like to know if the change i make would break anything, I doubt it, as this is controlled on the grpc options end.

I am just assuming nobody has grpc endpoints(proto) like the one mentioned above, which is why it's not been mentioned previously.

**Comment by stephenh** [comment]
Hey @iangregsondev ! Sorry for the late reply, just catching up...

Makes sense, "does camel case mean 'API' or 'Api'?" is a common disagreement between different `camelCase` implementations.

If you wanted to submit a PR to fix this, that'd be great. If I'm following, it would be around here:

https://github.com/stephenh/ts-proto/blob/main/src/utils.ts#L166

To your point of it being a breaking change, I think the `camelCase` method is used for quite a few things in ts-proto (other than just the GRPC method names), so maybe we could make a new/dedicated `camelCaseGrpc` function that mimics their `Api-vs-API` output, and use that specifically/only for that `formatName` method?

Thanks!

**Comment by iangregsondev** [comment]
Hi @stephenh , sorry for the long delay; busy with other work stuff. Going to take this, this morning/afternoon. Looks pretty easy to fix and I will get over a PR.

Cheers.

**Comment by iangregsondev** [comment]
@stephenh Initial PR made, let me know your thoughts over there.

https://github.com/stephenh/ts-proto/pull/721

There is a failing check, not sure what that is.

Thanks!
