### ISSUE TITLE
TS2304: Cannot find name 'global'

### ISSUE THREAD

**Issue by SazhinDima** [stephenh/ts-proto#70]
I generated typescript file and try to import it.
But i have error "TS2304: Cannot find name 'global'" on line throw new global.Error("Value is larger than Number.MAX_SAFE_INTEGER");

Help me please.

**Comment by stephenh** [comment]
@SazhinDima are you trying to run the `ts-proto` output in Node on the backend or in a browser on the frontend?

**Comment by stephenh** [comment]
@SazhinDima I'm guessing that you're trying to run in the browser, where `globalThis` needs to be used instead of `global`. Can you try version 1.21.2? If you're still having issues, let me know more details about what environment you're trying to run in and what your `tsconfig` looks like.

**Comment by SazhinDima** [comment]
@stephenh i'm runing in the Node.js (react project)

tscinfig:

{
    "compilerOptions": {
        "module": "commonjs",
        "moduleResolution": "node",
        "sourceMap": true,
        "jsx": "react",
        "target": "es2018",
        "baseUrl": ".",
        "experimentalDecorators": true,
        "skipLibCheck": true,
        "typeRoots": [
            "./node_modules/@types"
        ]
    },
    "include": [
        "src/**/*",
        "globalCss.d.ts"
    ],
    "exclude": [
        "node_modules",
        "dist"
    ]
}

**Comment by SazhinDima** [comment]
If i put in top:
declare var global: any;

evethig works correct. But i don't know is it ok.

**Comment by stephenh** [comment]
You probably need to do `npm install @types/node` because `global` comes from node. This is not a ts-proto issue but just a TypeScript/node issue, so please use SO/etc. to resolve from here on out.

**Comment by oleic** [comment]
I think I have a similar error. If I have a message that is contains a property with `bytes` I get following error on executing the app.

```
/Users/tuananhbui/Code/morenergy/masterarbeit/local-backend/dist/src/protobuf/device.js:752
const windowBase64 = globalThis;
                     ^

ReferenceError: globalThis is not defined
    at Object.<anonymous> (/Users/tuananhbui/Code/morenergy/masterarbeit/local-backend/dist/src/protobuf/device.js:752:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/tuananhbui/Code/morenergy/masterarbeit/local-backend/dist/shared/models/signal.entity.js:15:18)
```

Example message with bytes type:


```
message Chunk {
  bytes Content = 1;
}
```

**Comment by JeViCo** [comment]
If someone still have this issue, try using `globalThis` instead

**Comment by stephenh** [comment]
Hi @JeViCo , thanks for the note; per `globalThis`, yes, at this point we have a pretty elaborate function to get the right global object:

```
const tsProtoGlobalThis: any = (() => {
  if (typeof globalThis !== "undefined") {
    return globalThis;
  }
  if (typeof self !== "undefined") {
    return self;
  }
  if (typeof window !== "undefined") {
    return window;
  }
  if (typeof global !== "undefined") {
    return global;
  }
  throw "Unable to locate global object";
})();
```

And then we do `throw new tsProtoGlobalThis.Errror(...)`
