### ISSUE TITLE
camelcase to snakecase

### ISSUE THREAD

**Issue by 117sparta** [stephenh/ts-proto#71]
Is there a possible way to remain the name as it is defined in a proto file? I want a snakecase method or variable instead of camelcase.

**Comment by stephenh** [comment]
Hey, I assume you found the `snakeToCamel=false` option?

**Comment by stephenh** [comment]
`--ts_proto_opt=snakeToCamel=false` should work. Note that `protoc` can be finicky with command line settings, but it does work (see the `integration/simple-snake` directory).
