### ISSUE TITLE
How to deal with `null` in optional types

### ISSUE THREAD

**Issue by brunobely** [stephenh/ts-proto#713]
Is there a recommended approach to dealing with optional types when interacting with libraries that either use `T | null` or `T | null | undefined` to represent optional fields? I'm trying to create an object from a generated proto like:

```proto
message User {
  optional int32 id = 1;
}
```

```ts
const user = User.fromPartial({
  id: fetchedUser.id, // fetchedUser.id is of type `number | null | undefined`, so I get an error.
});
```

and instead I have to write the code like

```ts
const user = User.fromPartial({
  id: fetchedUser.id || undefined,
});
```

Could an option be added to generate types that use `T | null | undefined`, maybe?

**Comment by stephenh** [comment]
Hey @brunobely ; yeah, adding that `|| undefined` everywhere does sound annoying.

Trying to think, I don't think we have a good reason why `fromPartial` should not just _always_ allow passing `null`, but then treating it just like `undefined`...

If you wanted to submit a PR, it might be as easy as:

```
export type DeepPartial<T> = T extends Builtin ? T
  : T extends Array<infer U> ? Array<DeepPartial<U>> : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;
```

Adding a `| null` to the `[K in keyof T]?:` value.

And if that works/doesn't break anything, it seems like a good idea to me.

Thanks!
