### ISSUE TITLE
Why oneof is optional

### ISSUE THREAD

**Issue by EthianWong** [stephenh/ts-proto#715]
In readme
```typescript
interface YourMessage {
  eitherField: { $case: 'field_a'; field_a: string } | { $case: 'field_b'; field_b: string };
}
```
In fact,`eitherField` will alway be optional... 
```typescript
interface YourMessage {
  eitherField?: { $case: 'field_a'; field_a: string } | { $case: 'field_b'; field_b: string };
}
```
so it's readme has wrong? or i miss something?

**Comment by stephenh** [comment]
Hey @EthianWong ; ah yeah, the readme is wrong.

`eitherField` is optional b/c `oneof` in protobuf means "at most one" but not "must have at least one", i.e. it's valid for none of the fields to be set.

Thanks for pointing this out! I'll update the readme.
