### ISSUE TITLE
ts-proto never retrieves globalThis

### ISSUE THREAD

**Issue by andykais** [stephenh/ts-proto#732]
Hi, I noticed that your library has this code in it:
```ts
var globalThis = (() => {
    if (typeof globalThis !== 'undefined') {
        return globalThis;
    }
    if (typeof self !== 'undefined') {
        return self;
    }
    if (typeof window !== 'undefined') {
        return window;
    }
    if (typeof global !== 'undefined') {
        return global;
    }
    throw 'Unable to locate global object';
})();
```

I was seeing failures when only `globalThis` was available in the js program. When I reduce that code down to this:
```ts
var globalThis = (() => {
    if (typeof globalThis !== 'undefined') {
        return globalThis;
    }
    throw 'Unable to locate global object';
})();
```

it always fails. Tested on node `v12.19.0`, `v19.2.0` and deno `1.28.3`.

This looks to be a problem with `var` declared variable hoisting. `var globalThis` will declare globalThis as undefined before the code block executes, so it is always undefined. If you renamed the outer variable to something other than globalThis, the code will function.

```ts
var tsProtoGlobalThis = (() => {
    if (typeof globalThis !== 'undefined') {
        return globalThis;
    }
    throw 'Unable to locate global object';
})();
console.log(tsProtoGlobalThis)
```

**Comment by stephenh** [comment]
Huh! Good catch @andykais ! 

Are you interested in submitting a PR to fix this? That'd be great if so!

Otherwise yeah I'll get around to fixing this at some point; kinda surprised no one had noticed this was broken, but I guess maybe it was just always hitting one of the non-`globalThis` fallbacks.

**Comment by andykais** [comment]
so unfortunately getting approval to contribute to existing open source projects is something fairly difficult to do through my job 😞. It can take months. The best I can do is give some advice on what a good change would be

**Comment by stephenh** [comment]
Ah sure @andykais , that makes sense wrt getting approval. Given your great diagnosis/articulation of the problem, this was a pretty simple quick fix, so I went ahead and pushed it out. Thank you!

**Comment by andykais** [comment]
nice! Thanks @stephenh
