### ISSUE TITLE
TS2345 error when using exactly the right request object

### ISSUE THREAD

**Issue by roboslone** [stephenh/ts-proto#741]
So here's a code sample:
```typescript
const request = Graph_Filter.fromPartial({ id, excludeHistory: true })
return await GraphAPI.client.get(request)
```

`get` accepts `Graph_Filter`, as specified in service definition:
```typescript
get: {
  name: "Get",
  requestType: Graph_Filter,
  requestStream: false,
  responseType: Graph,
  responseStream: false,
  options: {},
},
```

I'm getting a TS error:
```
TS2345: Argument of type '{ id?: string | undefined; excludeNodes?: boolean | undefined; excludeHistory?: boolean | undefined; }' is not assignable to parameter of type '{ id?: string | undefined; excludeNodes?: boolean | undefined; excludeHistory?: boolean | undefined; } & { id?: string | undefined; excludeNodes?: boolean | undefined; excludeHistory?: boolean | undefined; } & { ...; }'.   Type '{ id?: string | undefined; excludeNodes?: boolean | undefined; excludeHistory?: boolean | undefined; }' is not assignable to type '{ [x: string]: never; [x: number]: never; [x: symbol]: never; }'.
     Property 'id' is incompatible with index signature.
       Type 'string' is not assignable to type 'never'.
```

Here's my gen options:
```
- enumsAsLiterals=true
- env=browser
- forceLong=string
- oneof=unions
- outputServices=nice-grpc,outputServices=generic-definitions
- unrecognizedEnum=false
- useDate=false
```

What am I doing wrong here?

**Comment by roboslone** [comment]
To clarify, this is happening with any methods, except ones accepting empty requests.

**Comment by stephenh** [comment]
@roboslone you can try turning off exact types with `--ts_proto_opt=useExactTypes=false` and see if that works.

**Comment by roboslone** [comment]
Yes, turning `useExactTypes` off does fix this error.

**Comment by roboslone** [comment]
However, I want to point out that exact types is a very nice feature to have. And furthermore, since it's the default option, I think this should be fixed.

**Comment by stephenh** [comment]
@roboslone really late reply, but personally I'm just waiting for Exact Types to be officially supported in TS:

https://github.com/microsoft/TypeScript/issues/12936

That said, if you can fix ts-proto's currently copy/pasted-from-that-issue attempt at userland `Exact` to avoid the error you're getting, that'd be great! :-)

**Comment by stephenh** [comment]
Per ^, we're waiting on TS exact types to provide non-janky/robust exact types.
