### ISSUE TITLE
Please provide clear instructions on how to add tests to the test suite

### ISSUE THREAD

**Issue by azizghuloum** [stephenh/ts-proto#752]
I added a fix but honestly I'm not sure how to add a new test to the test suite.  The contribution section in README kinda hints to how to commit it but how do you properly generate it in the first place?

**Comment by stephenh** [comment]
Hey @azizghuloum sure, that is a fair ask; I've updated the "Workflow" section of the readme. Can you take a look and see if that's better? Feel free to point out anything that is still unclear and I'll update it/clarify. Thanks!
