### ISSUE TITLE
NestJS Controller decorators affecting Validation Pipes

### ISSUE THREAD

**Issue by ZimGil** [stephenh/ts-proto#764]
When using a global `ValidationPipe` in NestJS - it's required to have any decorator on the controller methods in for TypeScript to do it's thing and add the `design:paramtypes` metadata that the `ValidationPipe` use for it's validation.

In REST APIs in NestJS you always have some decorators but in gRPC we only use the `@GrpcMethod()` that is redundant with the controller methods decorator.

There's the workaround of using any decorator on all controller methods, as I have no other needed decorator to use, I'm using the `@GrpcMethod()` decorator with no parameters as it does not break the NestJS gRPC implementation and does decorate the methods in a way which save the `design:paramtypes` in the metadata.

Some code snippets:

### `GrpcMethod()` only
TypeScript:
```ts
@Controller()
export class HeroController implements HeroServiceController {
	constructor(private readonly heroService: HeroService) {}

	@GrpcMethod('HeroService', 'getHeros')
	async getHeros(data: HerosRequestDto): Promise<IHerosResponse> {
```
Compiled JS:
> This is similar to the case of using both decorator
```js
__decorate([
    (0, microservices_1.GrpcMethod)(),
    __metadata("design:type", Function),
    __metadata("design:paramtypes", [HerosRequest_dto_1.HerosRequestDto]),
    __metadata("design:returntype", Promise)
], HeroController.prototype, "getHeros", null);
HeroController = __decorate([
    (0, common_1.Controller)(),
//  (0, FiRate_1.HeroServiceControllerMethods)(), // => this is added if using both decorators
    __metadata("design:paramtypes", [Hero_service_1.HeroService])
], HeroController);
exports.HeroController = HeroController;
```

### Controller Methods Decorator
TypeScript:
```ts
@Controller()
@HeroServiceControllerMethods()
export class HeroController implements HeroServiceController {
	constructor(private readonly heroService: HeroService) {}

	async getRates(data: HerosRequestDto): Promise<IHeroResponse> {
```
Compiled JS:
```js
HeroController = __decorate([
    (0, common_1.Controller)(),
    (0, FiRate_1.HeroServiceControllerMethods)(),
    __metadata("design:paramtypes", [Hero_service_1.HeroService])
], HeroController);
exports.HeroController = HeroController;
```

**Comment by stephenh** [comment]
Hi @ZimGil ; honestly since I'm not a NestJS user I'm not completely following the issue; like I don't even know if the code snippets you have are what ts-proto _does today_ or is what you _want it to do instead_. :-)

That said, I'm _pretty sure_ what you're saying is that today ts-proto puts some NestJS annotations only on the top-level `class HeroController` (like this `@HeroServiceControllerMethods`), and you're saying we need to instead put `@GrpcMethods` on each method because that would a) make the reflect stuff work, and b) not break anything anyway.

If my interpretation is correct, then, yeah I have no problem moving the annotations around in the NestJS output to be "the most correct" / most useful.

If you'd like to submit a PR, that'd be great. Thanks!

**Comment by ZimGil** [comment]
The `@HeroServiceControllerMethods()` decorator basically using the `@GrpcMethod()` decorator on all methods of the class. but because now there is no real decorator on the methods the reflection never happen.

This is not something `ts-proto` can actually solve as what you suggest is actually the current behavior of NestJS.

The solution should be on the NestJS side to make the usage of `GrpcService()` and `GrpcMethod()` decorators more user friendly for actual `gRPC`. I have a plan to commit a PR on the NestJS repo to fix it on their end but it's actually a breaking change so it may only hit at the next major release.

Once it hits there's no actual usage for this decorator anyway :) 

I just post this here so if anyone else run to this issue they'll know why and how to solve.

**Comment by stephenh** [comment]
Ah okay! So if I'm following you're basically saying that the way NestJS wrote their GRPC implementation fundamentally does not work with their own NestJS validation feature?

If so, that does seem unfortunate, and makes sense that it needs to be fixed on the NestJS side.

Since there is nothing for ts-proto to do, I think I'll go ahead and close the issue, but right hopefully it can be useful to others searching for issues with NestJS validation.

Once your fixes on the NestJS side land, would be great to have you submit any follow up PRs to adjust ts-proto output appropriately/if necessary; thanks!

**Comment by sychovoleh-nowsta** [comment]
@ZimGil If you decide to open a GitHub issue on the NestJS side, it would be useful to put reference here to see a progress.

**Comment by ZimGil** [comment]
I plan to do that - need to find some time.
Will post it here when I do.

**Comment by OjeshManandhar** [comment]
Utilize the `@Payload` and `@Ctx` decorators provided by `@nestjs/microservices` in the controller methods when applying the controller method decorator. This ensures proper denotation of data and metadata, enabling the validation pipe to operate on the payload.


```ts
import { Metadata } from '@grpc/grpc-js';
import { Ctx, Payload } from '@nestjs/microservices';

@Controller()
@HeroServiceControllerMethods()
export class HeroController implements HeroServiceController {
  constructor(private readonly heroService: HeroService) {}

  async getRates(
    @Payload() data: HerosRequestDto,
    @Ctx() metadata: Metadata,
  ): Promise<IHeroResponse> {
    // ...
  }

  // ...
}
```

**Comment by stephenh** [comment]
@OjeshManandhar do you think the `Payload` and `Ctx` annotations are something that should always be included in the ts-proto output?

Do all NestJS projects (that use protobuf) have `@nestjs/microservices` available as an import? If so, we could just always add it...

**Comment by OjeshManandhar** [comment]
@stephenh Yes, I think it will be better if the controller decorator also decorated the method parameters with `Payload` and `Ctx`.

Regarding the dependency on `@nestjs/microservices`, we have to install it to build microservices in NestJS, so it's reasonable to assume that `@nestjs/microservices` will be available.

**Comment by ZimGil** [comment]
By doing this you might affect you consumer ability to inject their own property decorators in a case where they'd want to change some things around. I would avoid this. 

Again, with avoiding the decorators on the consumer side you'll be missing the metadata on compile time and lose the validation capabilities

**Comment by stephenh** [comment]
@ZimGil per "affecting the ability to inject their own decorators", currently ts-proto doesn't really offer that ability anyway, afaiu? Like we make a `hero.ts` output file with the `HeroController.ts` in it, and we over-write every single time, so users adding their own decorators is already unsupported/would be over-written every time they reran the build?

> with avoiding the decorators on the consumer side you'll be missing the metadata on
> compile time and lose the validation capabilities

Which sounds like a bad thing, that afaiu adding the `Context` and `Payload` decorators fixes both?

**Comment by ZimGil** [comment]
I'm sorry, I've misunderstood the message before

**Comment by stephenh** [comment]
Er, shoot @ZimGil , I was looking at "just always add Ctx & Payload" to the ts-proto output, but ts-proto only generates the `HeroServiceController` _interface_ (which cannot have decorators on the parameters) and then the service class that _implements_ the interface can use `Ctx` and `Payload` annotations as/if needed.

If I was writing a ton of NestJS code, I'd probably find a way to scaffold that out, but for now I don't think there is really anything for ts-proto to do here.

Sound right @ZimGil , @OjeshManandhar ?

**Comment by OjeshManandhar** [comment]
@stephenh, I agree. While creating a scaffold for extensive NestJS code may be a future consideration, it seems there's no immediate action required from `ts-proto`. It would be best to update the `ts-protoc` documentation on using `Ctx` and `Payload` decorators to clarify other developers.
