### ISSUE TITLE
camelCase for a single proto message

### ISSUE THREAD

**Issue by rovolution** [stephenh/ts-proto#765]
Hello!

If I wanted to just generate a camel-cased TS definition for a single proto message in my file, but have my other messages in my proto file generate as snake-cased TS definitions, is there an easy way to configure this besides manually setting the `json_name` setting on the model i want as camel-cased? Thanks!

**Comment by stephenh** [comment]
Hi @rovolution ! No, we don't have a way to do per-message-type configuration options right now.

If you really do have only a single message that needs to be different, personally I'd probably just write the camel-cased one by hand.

If you had to do it a lot, or there are a lot of fields, you could explore something like a [fancy mapped type](https://javascript.plainenglish.io/transform-mapped-types-from-snake-to-camelcase-in-typescript-472a2a4843b9).

Or run your own fork of ts-proto that just hardcodes your special message type into

https://github.com/stephenh/ts-proto/blob/main/src/case.ts#L6

:-)
