### ISSUE TITLE
repeated google.protobuf.FoobarValue fields should translate to Foobar[], not Array<Foobar | undefined>

### ISSUE THREAD

**Issue by philikon** [stephenh/ts-proto#80]
As discussed in https://github.com/stephenh/ts-proto/issues/74, `repeated` fields can never have nullish values. This includes non-scalar fields, which are currently translated to `Array<Field | undefined>`, but should be `Field[]`.

**Comment by stephenh** [comment]
@philikon nice find; I know I'm behind on feedback on issues/etc., but this one looks pretty clear cut; kind of a lazy ask on my part, but you could make your "repeated fields" commit a dedicated PR and I can merge that on its own? Then I'll get to reading/thinking your other changes.

**Comment by philikon** [comment]
sure thing

**Comment by stephenh** [comment]
Released as 1.21.4. Thanks!

**Comment by philikon** [comment]
Woo thanks! I'll continue to work on #74. Let me know if you have any thoughts there, otherwise you may get a PR in the next few days or so...
