### ISSUE TITLE
[Bug] generate code error

### ISSUE THREAD

**Issue by LastKing** [stephenh/ts-proto#805]
I find a bug .. Why genereate  different code? use different way...

1. environment
   *  os: windows
   *  protoc:  libprotoc 22.1
   *  ts-proto: 1.143.0、1.142.1、1.142.0
   *  make: GNU Make 3.82.90( Built for i686-pc-mingw32)     --- use  mingw install
2. generate code two way:
   1. use makefile script:  `meke generate` 
       ![image](https://user-images.githubusercontent.com/8540374/226590837-23409536-f275-4cc5-a3c7-a8527d6b349b.png)
   2. use npm script: `npm run generate`
       ![image](https://user-images.githubusercontent.com/8540374/226590932-61db2829-fd83-4953-9cc2-ad44561e687f.png)

demo:
https://github.com/toonew-issue/ts-proto-issue

**Downgrading to version 1.141.1 returns to normal**

**Comment by paralin** [comment]
Not a bug.

You have a typo in your makefile:

protocc-gen-ts_proto

should be protoc-gen-ts_proto

**Comment by davidzeng0** [comment]
Code generation for decoding was updated in 1.143 I believe, which is why it's different

**Comment by LastKing** [comment]
Sorray. This is my mistask.

`npm run generate`  will **adds node_modules/.bin to the PATH provided to scripts.**,it use local node_modules/ts-proto

but `make genereate` don't add the path, it use gloabl ts-proto.

@paralin  Thank for your help.
