### ISSUE TITLE
Import Observable as type

### ISSUE THREAD

**Issue by spheenik** [stephenh/ts-proto#825]
Hi,

first of all, great project, using it with a lot of joy.

I have a small feature request. I am using the generated code in a svelte project, where the `tsconfig.js` does have

`"importsNotUsedAsValues": "error"`

This gives me a tslint error in the generated api.ts, because it imports `Observable` as

`import { Observable } from "rxjs";`

instead of

`import type { Observable } from "rxjs";`

I was trying to come up with a pull request, but I can't seem to find where it happens. I saw in `tspoet` that it supports importing as type, so maybe it'll take you only a minute. Not really a big deal though, I can simply add it everytime after compiling the API.

**Comment by stephenh** [comment]
Fixed by #826 , thanks @spheenik !

**Comment by spheenik** [comment]
My pleasure!
