### ISSUE TITLE
Option outputTypeAnnotations Makes Types Difficult to Use

### ISSUE THREAD

**Issue by blorgon1** [stephenh/ts-proto#827]
When generating TS with the `outputTypeAnnotations` option enabled, the generated type contains a `$type` field as expected:
```typescript
export interface MyMsg {
  $type: "package.MyMsg";
  value: string,
}

export const MyMsg = {
  $type: "package.MyMsg" as const,

  encode(message: MyMsg, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    ...
  },
  ...
}
```

But this makes constructing `MyMsg` objects more difficult/tedious:
```typescript
// Doesn't work:
// Property '$type' is missing in type '{ value: "hello" }' but required in type 'MyMsg'.
const myMsg: MyMsg = {
  value: 'hello',
};

// Works:
const myMsg: MyMsg = {
  $type: MyMsg.$type,
  value: 'hello',
};
```

This means that for established projects, in order to start generating the `$type` field on messages, it needs to be added everywhere one of those is being constructed.

**Suggestion:** Could the type be added to a method on the message? For example `MyMsg.getType()`, then it would still be accessible (although it wouldn't be present on instances of the message) without interfering with ergonomics.

**Comment by stephenh** [comment]
Afaict `MyMsg.getType()` would look like:

```
const myMsg: MyMsg = {
  $type: MyMsg.getType(),
  value: 'hello',
};
```

Which doesn't seem that much of a difference in terms of ergnomoics?

Fwiw I agree "setting $type every where" is a down of using the type annotation; have you see the `fromPartial` methods? Iirc that will handle setting `$type` for you, albeit you'll loose the strictness checking of requiring every field to be fine, as `fromPartial` will also default other fields, so its a tradeoff of which you care about more.

**Comment by stephenh** [comment]
> I was imagining that $type would be removed altogether, and only the getType method
> would be present. Is there a reason/use-case that demands having $type?

At least historically, the use-case of the `$type` field was to know a message type dynamically.

Like in code like:

```
function someMiddlewareInfra(message: object): void {
  // what type of object is this?
  if (message.$type === 'MyMsg') { ... }
};
```

So `outputTypeAnnotations` was for exactly this--let me look at a message and ask it's `$type`.

In your example, your code doing `MyMsg.getType()` already/statically "this is MyMsg", so I agree you don't need the `$type` field, but then I guess why turn on `outputTypeAnnotations` in the first place? 

Going to close this for now with the recommendation for either a) don't use `outputTypeAnnotations`, or b) use `fromPartial` as @davidzeng0 suggested.
