### ISSUE TITLE
Can't run protoc-gen-ts_proto when installing from git

### ISSUE THREAD

**Issue by bouk** [stephenh/ts-proto#829]
I installed ts-proto through git by doing `yarn install github:stephenh/ts-proto`, but then the 'build' directory is missing so I can't run protoc-gen-ts_proto

**Comment by stephenh** [comment]
Huh. I've not tried yarn installing packages through git before, so don't really know how it works. Let me know if you figure it out!

**Comment by paralin** [comment]
That's the same for all packages unfortunately. You can't install from git with the release build included. I'd recommend just downloading from git, build, then npm link

**Comment by stephenh** [comment]
Ah yeah, @paralin 's assertion is what I'd thought as well; @bouk let us know if you find a way for npm packages to tell `yarn install` what their post-install build step should be (...although I think those are kind of frowned upon now?...iirc...), but otherwise going to close this out for now.
