### ISSUE TITLE
Update to protobufjs 7

### ISSUE THREAD

**Issue by dbrgn** [stephenh/ts-proto#834]
protobufjs 7 has been out for almost a year now: https://github.com/protobufjs/protobuf.js/blob/master/CHANGELOG.md#700-2022-07-08 It contains quite a few bugfixes.

Are there any plans to upgrade to protobufjs 7.x? (I'm working in a project that uses both ts-proto and protobufjs, so this is currently an upgrade-blocker for me 🙂)

**Comment by stephenh** [comment]
@dbrgn I'd love to see an upgrade to protobuf 7, but personally am more in "stewardship mode" for ts-proto that actively making changes; would be great if you wanted to take this on, and I'd be happy to help out on the PR.

Can you tell how big of an upgrade it will be? Scanning the release notes, it doesn't seem too bad?

**Comment by vriesk** [comment]
Upping this.

There have been recent security issues with `protobufjs`, fixed in 7.2.4 release.

**Comment by ping-localhost** [comment]
Please update to protobufjs 7, the old versions contain a Prototype Pollution vulnerability. 

See https://github.com/advisories/GHSA-h755-8qp9-cq85 for more information

**Comment by dbrgn** [comment]
Sorry for not following up on this, @stephenh. I did intend to prepare a pull request, but never got around to it.

With #867 being open: How thorough is the test suite? Is it sufficient that the tests pass with the new dependency, or are further verifications necessary?

**Comment by stephenh** [comment]
Np @dbrgn ! The #867 is just for the `/protos` subdirectory; I think the primary dependabot for protobuf 7 PR is this one:

https://github.com/stephenh/ts-proto/pull/866

Which is failing at the `pbjs` part of the build, which seems kinda surprising:

```
Run ./integration/pbjs.sh
Usage Error: Couldn't find a script named "pbjs".
```

Although the pbjs output is provided by the protobuf.js project, so perhaps they changed something in how that is published/invoked.

**Comment by threema-lenny** [comment]
I'm on it.
