### ISSUE TITLE
fromPartial method returns an error,'Argument type {} is not assignable to parameter type I'

### ISSUE THREAD

**Issue by zsp419** [stephenh/ts-proto#838]
With the tool's automatically generated code, the fromPartial method returns an error, as shown below:
![image](https://github.com/stephenh/ts-proto/assets/27196467/f7ba4d91-9e42-4511-952e-cd432ebb0510)
here is my protofile code:
![image](https://github.com/stephenh/ts-proto/assets/27196467/5f1d7e0e-1146-4a00-8538-3d24e8d6c54a)
please help me!

**Comment by stephenh** [comment]
Hi @zsp419 , that code has not caused issues in the past; out of curiosity, what version of TypeScript are you using? I'm wondering if it's a TS 5.x behavior.

**Comment by Truman55** [comment]
<img width="905" alt="image" src="https://github.com/stephenh/ts-proto/assets/16853683/4b782ae1-05dd-46bc-aa2d-05e99edb772a">

same problem. TS 5.0.4

**Comment by zsp419** [comment]
what ide do you use,I had problems with IntelliJ IDEA before, but vscode is fine

**Comment by stephenh** [comment]
Fwiw I've bumped ts-proto's integration tests to TypeScript 5.1 and am not getting any errors from the `?? {}` lines. And I'm using Webstorm.

We have a `useExactTypes=false` flag that might avoid this error, but also would be great to find out what specifically is causing this. Like a tsconfig setting?

Granted we could always add a `{} as any` to get around it, but would be nice to know more about why this is not working.

**Comment by TennyZhuang** [comment]
Same error on ts 5.1.6

**Comment by stephenh** [comment]
I pushed a fix that adds an `as any` on that line. Fwiw my guess is that non-trivial protobuf schemas cause issues with our `useExactTypes` flag, so I recommend turning it off if you see these issues.
