### ISSUE TITLE
Handling well known type: google.protobuf.duration?

### ISSUE THREAD

**Issue by SonofNun15** [stephenh/ts-proto#840]
We're using google.protobuf.duration in our proto file to represent timespans / durations. 

In the generated output from ts-proto for a proto file that imports from `import "google/protobuf/duration.proto";`, we get a javascript file with this import:
```typescript
import { Duration } from "../google/protobuf/duration";
```
This tries to import from a file that does not exist and results in an error.

Do you have any recommendations on the best way to handle this? I am aware that javascript does not have a data type for representing time spans out of the box. Is there a library that can be used for this? Has anyone tried to handle this before?

We're seeing similar behavior when using google.protobuf.empty. This one we could get around by just defining an empty message in our proto file instead, but it is nice to avoid spamming empty message declarations in multiple places.

Additional details. The arguments that we are passing to ts-proto are as follows:
```
useOptionals=messages, lowerCaseServiceMethods=true, esModuleInterop=true, env=browser, outputClientImpl=grpc-web
```

We're using the `namely/protoc-all` docker image to generate the typescript files via ts-proto with the following command:
```
docker run --rm -v /$PROTO_PROJECT_ROOT:/defs namely/protoc-all \
    -f "Protos/*.proto" \
    -l typescript \
    -o ts_build \
    --ts_opt "useOptionals=messages,lowerCaseServiceMethods=true,esModuleInterop=true,env=browser,outputClientImpl=grpc-web"
```

**Comment by stephenh** [comment]
This should work, in that there should be a `duration.ts` file somewhere in your output. Maybe the import is just broken?

I.e. in our tests, we have examples of using `timestamp.proto`:

https://github.com/stephenh/ts-proto/blob/main/integration/simple/simple.proto#L7

Which generates this file:

https://github.com/stephenh/ts-proto/blob/main/integration/simple/google/protobuf/timestamp.ts

Which is imported correctly from here:

https://github.com/stephenh/ts-proto/blob/main/integration/simple/simple.ts#L4

I don't think we have any specific handling of `timestamp.proto` that would not apply to `duration.proto`.

If you can confirm whether there is a `duration.ts` being output somewhere, and it's just a broken import, that would be great. Maybe your `.proto` files are organized in a way we don't anticipate.

**Comment by SonofNun15** [comment]
Thanks for the quick follow up! I’ll take a look at those links and inspect
to see if a duration file is getting generated somewhere unexpected
tomorrow and let you know what I find!

**Comment by SonofNun15** [comment]
You are 100% correct! The duration.ts file is getting generated. The issue was with our build process which appears to not be copying the sub folder into the UI project. It's only copying the generated *.ts files in the root of the folder or something. Thanks for the help!
