### ISSUE TITLE
outputIndex does not respect importSuffix

### ISSUE THREAD

**Issue by val-o** [stephenh/ts-proto#845]
when --importSuffix=.js the index file generated by outputIndex doesn't not add .js suffix to imports, which leads to TypeScript error when targeting node>16

ts-node version: 1.148.2

**Comment by stephenh** [comment]
Hi @val-o , really late follow-up (I only have time to triage issues on ts-proto every few weeks), but if you'd like to submit a PR for this fix, that'd be great! The issue is probably around here:

https://github.com/stephenh/ts-proto/blob/1f73bad91fe33c497d5168b9f0847ad596ffec39/src/utils.ts#L24
