### ISSUE TITLE
Convert Bash Scripts to Nodejs to work cross-platform

### ISSUE THREAD

**Issue by cliedeman** [stephenh/ts-proto#85]
More a note to myself.

bash in mac is still on v3 for most people unless your install a newer version for brew.

To get the codegen and update-bins scripts to work you need to comment out these lines.

```
!/usr/bin/env zsh
shopt -s globstar
```

Easiest solution would probably be to re-write these 2 scripts in nodejs

**Comment by philikon** [comment]
All that's required is a bash version that's slightly more modern than the iPhone... The scripts work on Mac if you `brew install bash`. (Note how the shebang refers to `/usr/bin/env bash` and doesn't hardcode `/bin/bash`.)

**Comment by timostamm** [comment]
Macos comes with zsh for some time now. 
If you don't care to install bash, you can run the scripts with `zsh update-bins.sh` for example.
This will print an error message because zsh does not now `shopt`, but the globbing and rest of the script work fine.

**Comment by cliedeman** [comment]
so the scripts actually do work on mac.
The globbing seems to work as expected even though its on bash 3. because there is no `set -e` it prints a confusing error but does complete.

And re-writing the scripts in nodejs will make the project more friendly to windows users so I believe there is still merit in doing this.

**Comment by timostamm** [comment]
> And re-writing the scripts in nodejs will make the project more friendly to windows users so I believe there is still merit in doing this.

Absolutely agree, also for mac users. Having to run the scripts explicitly with zsh and ignoring the error is not intuitive.

**Comment by miaozasanynoe** [comment]
臣复议，不能把生成命令放在npm script里面太难受了
