### ISSUE TITLE
object: any is not okay

### ISSUE THREAD

**Issue by f0rmat1k** [stephenh/ts-proto#856]
ts-proto generates fromJSON in style like:
```ts
fromJSON(object: any): ObjectId {
    return { value: isSet(object.value) ? String(object.value) : "" };
}
```

the problem is `any` may be anything, e.g. undefined, null, number etc. But `fromJSON` tries  to read `object.value` so it expects `object` as `Object` in fact. According types i don'e see it outside and may pass `undefined` as argument and get runtime error
`TypeError: Cannot read properties of undefined (reading 'Field')
    at Object.fromJSON (`

Im my opinion true way is to choose `object` instead of `any`. And check `isSet('value' in object ? object.value : undefined)`. 

and right code will be like
```ts
fromJSON(object: object): ObjectId {
    return { value: isSet('value' in object ? object.value : undefined) ? String('value' in object ? object.value : '') : "" };
  }
```

Another way is to add default like `object = object || {}` inside of every `fromJSON`:
```ts
fromJSON(object: any): ObjectId {
    object = object || {};
    return { value: isSet(object.value) ? String(object.value) : "" };
  }
```

What do you think? If you agree, i can send PR.

**Comment by stephenh** [comment]
Hi @f0rmat1k , I agree `any` seems too loose...

If we changed it, I'd prefer to avoid the `isSet` checks...just b/c imo the contract of `fromJSON` is that users really should pass the expected shapes, or get an error/undefined behavior (i.e. if the json is untrusted off the wire, that's fine, it will error out with an NPE/something).

So the current behavior of throwing a "`value` does not exist on `object`" runtime error is imo preferable to returning "an empty object" that ignores that the shape of the input was incorrect.

Also, if `fromJSON` became `fromJSON(o: object)`, then we'd need to do `(object as any).value` casts within the method at all the various lookups. Which kinda highlights that it's not actually type-safe anyway.

If you want a "from" method that is more type-safe, fwiw that is what `fromPartial` is for, but `fromJSON` is fundamentally "you don't really know what came off the wire, but if it's valid JSON you'll get a `ObjectId`, and if not, you'll get a runtime error".

So, after thinking through it, I'd like to keep it `object: any`. Thanks for the issue!
