### ISSUE TITLE
Missing "./build/plugin" on v1.152.0

### ISSUE THREAD

**Issue by guybenda** [stephenh/ts-proto#871]
Required in the main script:
![image](https://github.com/stephenh/ts-proto/assets/43969637/3ba3ed90-3aab-4a2f-bba3-fe7cf1fbbc7f)

Actual directory on version:
![image](https://github.com/stephenh/ts-proto/assets/43969637/d65f3825-a87c-4f46-a692-c2f6bdc3faca)

**Comment by tomerBZ** [comment]
@stephenh same here
Looks like v1.152.1 is not available or I'm missing something...?

**Comment by stephenh** [comment]
@tomerBZ hrm...afaict v1.152.1 should fix it, I did an `npm i` in a new project and am getting back the original layout:

```
$ ls node_modules/ts-proto/build/plugin.js 
node_modules/ts-proto/build/plugin.js
```

And running `./node_modules/ts-proto/protoc-gen-ts_proto` does not error out.

**Comment by guybenda** [comment]
Works on 1.152.1, thanks!
