### ISSUE TITLE
Drop dependency to protobufjs?

### ISSUE THREAD

**Issue by threema-lenny** [stephenh/ts-proto#873]
There are a couple of issues with protobufjs:

- it drags a lot of dependencies with it that we don't actually need
- protobufjs has a global configuration for utilities which can (and in practice do) break, especially with bundlers (ping me for a story)
- it blocks resolving a lot of other issues posted here, e.g. bigint handling

Furthermore, the actual dependencies to protobufjs we have are tiny. So, I think it would be great if we could shed off the dependency to protobufjs.

Is there something I have missed? Would such an effort be appreciated?

**Comment by stephenh** [comment]
Hi @threema-lenny ; do you mean drop the `package.json` dependency on protobufjs, and then a) still use its methods to encode/decode bytes (meaning the user would have to have their own dependency on protobufjs, but in theory it could be any version that ts-proto-generated code was compatible with), or b) ts-proto-generated output wouldn't use the protobufjs runtime at all, and instead some other runtime library like @grpc/grpc-js or @bufbuild/protobuf?

Honestly I'd be fine with either, the latter is just a lot more ambitious (I assume) than the former, and wasn't sure what you had in mind.

**Comment by stephenh** [comment]
Fwiw I am generally nervous about getting into the game of low-level packed vs. unpacked vs. whatever binary encodings/decodings, just in terms of being a long-term maintenance responsibility.

Granted, protobufjs got us going very quickly, but also has really lagged on things like longjs/BigInt/ESM/etc support. Seems like they are finally catching up though.

I would probably be most supportive of moving from `protobufjs` to `@bufbuild/protobuf` if possible, as they just very recently built that library (within the last 6-9 months), so it should be pretty modern/idiomatic/etc. And they also have full-time engineers + a very robust test suite behind it.

The unknown wrinkle would be how many assumptions/couplings it makes about how messages are presented in memory/at runtime.

protobufjs has its own assumptions as well, but they matched what ts-proto's messages wanted "close enough" to not be an issue (sans for that `wrappers` escape hatch, i.e. would `@bufbuild/protobuf` have the same thing for our preferential handling of structs/well known types?). I.e. I know they have a "base `Message` class" for all their codegen-d types, so perhaps that is baked into their `@bufbuild/protobuf` low-level encoding/decoding logic? Not sure...

Excited to have you explore the possibilities though.

**Comment by stephenh** [comment]
Fwiw @threema-lenny closing this for housing keeping, but happy to have you explore this if you'd like.
