### ISSUE TITLE
bug: incorrect long import syntax when uint64 used

### ISSUE THREAD

**Issue by TeemuKoivisto** [stephenh/ts-proto#887]
Hey, so I noticed that using uint64s are bit harder with protobuf. Seems you need an additional library to handle them with JS. While I'm sure the `long` library works fine, it seems there's something wrong with the import syntax.

As of now, when I compile my proto files it produces a `.ts` file with `import Long = require("long");` statement that my `tsc` fails to compile throwing:

```ts
error TS1202: Import assignment cannot be used when targeting ECMAScript modules. Consider using 'import * as ns from "mod"', 'import {a} from "mod"', 'import d from "mod"', or another module format instead.

4 import Long = require("long");
```

In the PR which adds this https://github.com/stephenh/ts-proto/pull/882 it says it should use `import Long from "long"` when `"esModuleInterop": true` which should work. But even though I have it enabled, it uses the incorrect import syntax.

I can add a reproduction if necessary. I am using "ts-proto": "1.155.1" and "typescript": "4.9.4"

**Comment by davidzeng0** [comment]
Try passing `--ts_proto_opt=esModuleInterop=true` to protoc

**Comment by TeemuKoivisto** [comment]
> Try passing `--ts_proto_opt=esModuleInterop=true` to protoc

Nice, thanks! Works 👍
