### ISSUE TITLE
Two files in same package unable to import correctly

### ISSUE THREAD

**Issue by lexdevelop** [stephenh/ts-proto#890]
Hello, I'm trying to build following protos, they are in same directory:
Filename: example_proto.proto
```
syntax = "proto3";
package example_proto.v1;

enum MyCustomEnum {
    MY_CUSTOM_ENUM_UNSPECIFIED = 0;
    MY_CUSTOM_ENUM_VALUE_ONE = 1;
    MY_CUSTOM_ENUM_VALUE_TWO = 2;
}
```
Filename: example_proto_grpc.proto
```
syntax = "proto3";
package example_proto.v1;

import "pb/example_proto/v1/example_proto.proto";

message ExampleProtoRequest {
    MyCustomEnum custom_enum = 1;
    int64 id = 2;
}

message Empty {
}

service ExampleProtoService {
    rpc SyncCandles(ExampleProtoRequest) returns(Empty){}
}
```
This build correctly into:
example_proto.proto -> https://pastebin.com/VqTJVn5t
example_proto_grpc.proto -> https://pastebin.com/3QSAA43w

Usage:
```
import { Metadata } from '@grpc/grpc-js';
import {
    type ExampleProtoServiceController,
    type ExampleProtoRequest, Empty
} from 'xxxxxxx/proto/nestjs/pb/example_proto/v1/example_proto_grpc';
import { MyCustomEnum } from xxxxxxx/proto/nestjs/pb/example_proto/v1/example_proto';
import {Observable} from "rxjs";

export class WorkerController implements ExampleProtoServiceController {
    syncCandles(request: ExampleProtoRequest, metadata?: Metadata): Promise<Empty> | Observable<Empty> | Empty {
        console.log(request, metadata)
        switch (request.customEnum) {
            case MyCustomEnum.MY_CUSTOM_ENUM_VALUE_ONE: {
                console.log("Value one")
                break;
            }
            case MyCustomEnum.MY_CUSTOM_ENUM_VALUE_TWO: {
                console.log("Value two")
                break;
            }
            default: {
                console.log(request.customEnum.toString() + ' is not supported')
                break;
            }
        }
        return {}
    }
}
```
All other proto works fine in my project, but when I try such case I'm getting error:
.\node_modules\.bin\ts-node .\src\index.ts
C:\Users\xxxxxxxx\Desktop\node\node_modules\xxxxxxx\proto\nestjs\pb\example_proto\v1\example_proto.ts:3
export enum MyCustomEnum {
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1119:15)
    at Module._compile (node:internal/modules/cjs/loader:1155:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\Stefan\Desktop\node\node_modules\ts-node\src\index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1069:32)
    at Function.Module._load (node:internal/modules/cjs/loader:904:12)
    at Module.require (node:internal/modules/cjs/loader:1093:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (C:\Users\Stefan\Desktop\node\src\index.ts:6:1)
    
 Any idea what I'm doing wrong?
 This is compile command:
```
 protoc --plugin=/usr/local/lib/node_modules/ts-proto/protoc-gen-ts_proto \
    --proto_path=proto/ \
    --ts_proto_out=/output/nestjs \
    --ts_proto_opt=nestJs=true \
    --ts_proto_opt=addGrpcMetadata=true \
    --ts_proto_opt=addNestjsRestParameter=false \
    --ts_proto_opt=outputJsonMethods=true \
    --ts_proto_opt=outputEncodeMethods=true \
    --ts_proto_opt=unrecognizedEnum=false \
    --ts_proto_opt=exportCommonSymbols=false \
    $(find ./proto/pb -iname "*.proto")
```

**Comment by lexdevelop** [comment]
When I run same example in NestJS I'm getting error:
Error: Cannot find module 'xxxxxxx/proto/nestjs/pb/example_proto/v1/example_proto'

Other proto built together with example_proto and example_proto_grpc works fine.

**Comment by stephenh** [comment]
`SyntaxError: Unexpected token 'export'` looks like Node is in CommonJS mode, and not expecting the `export` keyword. It is expecting something like `tsc` or `tsx` to have compile the TypeScript to CommonJS.

Seems like just a project setup/you need a transpiler issue, and nothing related to ts-proto nor multiple files in the same package.

Going to close this out; lmk if you figure it out, or have more/better indication it is actually a ts-proto issue.
