### ISSUE TITLE
Converting to CamelCase for the interfaces and serialize to snake case

### ISSUE THREAD

**Issue by Frabat** [stephenh/ts-proto#899]
Hi, more than an issue this is just a question.
Is possible to enable the camelCase conversion and then serializing using .toJSON methods that will use snake_case_keys instead of camelCase ones?

**Comment by stephenh** [comment]
Hi @Frabat ; I think you can achieve what you want by setting `--ts_proto_opt=snakeToCamel=keys`, which doesn't include `json`, so should put snake case into the JSON.

From the readme:

```
snakeToCamel can also be set as a _-delimited list of strings (comma is reserved as the flag delimited), i.e. --ts_proto_opt=snakeToCamel=keys_json, where including keys will make message keys be camel case and including json will make JSON keys be camel case.
```
