### ISSUE TITLE
dependency calculation optimization

### ISSUE THREAD

**Issue by davidzeng0** [stephenh/ts-proto#900]
In plugin.ts, there should probably be a check that exits if the file is already in the fileSet.
![image](https://github.com/stephenh/ts-proto/assets/40158558/97c0c038-0296-4d17-968c-adf4fc4026cf)

**Comment by stephenh** [comment]
Hi @davidzeng0 ; sure, I can add that--out of curiosity, do you have a sufficient number of `request.fileToGenerate`s / `file.dependency`s that this check would demonstrably change the runtime?

**Comment by davidzeng0** [comment]
Yes, I have ~7k files to generate and the difference is 3 seconds of runtime vs DNF

**Comment by stephenh** [comment]
Wow. That's a lot of files. :-)

**Comment by davidzeng0** [comment]
Thanks!
