### ISSUE TITLE
Option to log numbers when the value is 0

### ISSUE THREAD

**Issue by Frabat** [stephenh/ts-proto#907]
Hi! 
I'm facing an issue. I'm trying to serialize an object which has a property equal to 0.

Unluckily, when I call the .toJSON()/.encode() methods, that value gets skipped. 
This results in: 

`
        "event_type": {
            "seek_ended": {
            }
        }
`
instead of 

`
        "event_type": {
            "seek_ended": {
                "position": 0
            }
        }
`

Could we try to enable the latter instead of the former?

Thanks.

**Comment by stephenh** [comment]
Hi @Frabat ; this is canonical protobuf behavior, to omit the default values when encoding to the wire.

We originally did always omit `0`, but then a contributor made the upgrade for us to follow the spec, and not put default values on the wire.

I could have swore we had an "emit default values" flag to restore the prior behavior, but I guess not.

The code to change would be around in here:

https://github.com/stephenh/ts-proto/blob/be5c22e4b7f8ee81d0ae7c50d433d768b8da66f5/src/main.ts#L1428

If you wanted to work on a PR. Thanks!

**Comment by wgottschalk** [comment]
I'm running into the same issue where we want to display a json formatted version to an end user for editing and want to include the numbers. I can get a PR to add support for just to toJSON methods for now since I might not have time to handle all of the encoding changes

**Comment by stephenh** [comment]
This should be fixed in #919 ; thanks @wgottschalk !
