### ISSUE TITLE
Error TS2306 (not a module) for empty files

### ISSUE THREAD

**Issue by jk-apple** [stephenh/ts-proto#908]
**NOT A CONTRIBUTION**

With `esModuleInterop=true` and `outputIndex=true` ts-proto sometimes produces empty files which are then exported from an index file which leads to error TS2306 (not a module). 

When running `protoc --plugin=./node_modules/.bin/protoc-gen-ts_proto --ts_proto_opt=esModuleInterop=true --ts_proto_opt=outputIndex=true --ts_proto_out=out/ empty.proto` on
```proto
// empty.proto
syntax = "proto2";
package empty;
```
we get
```
$ head out/{empty.ts,index.empty.ts}
==> out/empty.ts <==
/* eslint-disable */

==> out/index.empty.ts <==
/* eslint-disable */

export * from "./empty";
```
See https://github.com/microsoft/TypeScript/issues/46343 for a discussion of why this causes a compiler error when importing ``index.empty.ts``.

Empty protobuf files like shown are just one example of how to trigger that error.
More commonly, this also happens with protobuf files that purely consist of ``extend`` declarations.

**Comment by stephenh** [comment]
Ah yeah, that makes sense...thanks for the report @jk-apple . If you'd like to submit a PR to fix this, that'd be great. Thanks!
