### ISSUE TITLE
Enum JSON decoding/encoding methods

### ISSUE THREAD

**Issue by Frabat** [stephenh/ts-proto#909]
Hi,
when using the toJSON/fromJSON only encoding feature, I've noticed that the ts-proto outputs the serializing methods for both of them regardless which one we're using. 

I wanted to track this, even though I'm already taking care and provide the PR

**Comment by Frabat** [comment]
Example: 

PROTO FILE: 
`
message Test {
  enum TestType {
    TEST_TYPE_UNSPECIFIED = 0;
    TEST_TYPE_EVENT = 1;
    TEST_TYPE_METRIC = 2;
    TEST_TYPE_DERIVED = 3;
  }

}
`

exported TS file: 

`
export interface Test {
}

export enum Test_TestType {
  TEST_TYPE_UNSPECIFIED = 0,
  TEST_TYPE_EVENT = 1,
  TEST_TYPE_METRIC = 2,
  TEST_TYPE_DERIVED = 3,
  UNRECOGNIZED = -1,
}

export function test_TestTypeFromJSON(object: any): Test_TestType {
  switch (object) {
    case 0:
    case "TEST_TYPE_UNSPECIFIED":
      return Test_TestType.TEST_TYPE_UNSPECIFIED;
    case 1:
    case "TEST_TYPE_EVENT":
      return Test_TestType.TEST_TYPE_EVENT;
    case 2:
    case "TEST_TYPE_METRIC":
      return Test_TestType.TEST_TYPE_METRIC;
    case 3:
    case "TEST_TYPE_DERIVED":
      return Test_TestType.TEST_TYPE_DERIVED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Test_TestType.UNRECOGNIZED;
  }
}

export function test_TestTypeToJSON(object: Test_TestType): string {
  switch (object) {
    case Test_TestType.TEST_TYPE_UNSPECIFIED:
      return "TEST_TYPE_UNSPECIFIED";
    case Test_TestType.TEST_TYPE_EVENT:
      return "TEST_TYPE_EVENT";
    case Test_TestType.TEST_TYPE_METRIC:
      return "TEST_TYPE_METRIC";
    case Test_TestType.TEST_TYPE_DERIVED:
      return "TEST_TYPE_DERIVED";
    case Test_TestType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export const Test = {
  toJSON(_: Test): unknown {
    const obj: any = {};
    return obj;
  },
};

`

**Comment by stephenh** [comment]
Fixed in #910 , thanks @Frabat !
