### ISSUE TITLE
*_PACKAGE_NAME duplication

### ISSUE THREAD

**Issue by eladhaim** [stephenh/ts-proto#911]
We are trying to generate code from multiple .proto files with the nests=true flag.
Using this flag every file includes the package_name which make it impossible to export from the same index.ts.

Can we add a flag to generate the package_name export on a separate file and exclude it from all the files?

**Comment by paralin** [comment]
Can't you do: 

export { foo as bar } from './js1.js'
export { foo as baz } from './js2.js'

**Comment by eladhaim** [comment]
We can but it will add "namespace" within the same package.
We want to achieve:
export * from "./foo";
export * from "./bar";

**Comment by eladhaim** [comment]
i can create pr if it is necessary

**Comment by stephenh** [comment]
Hi @eladhaim , I believe `exportCommonSymbols=false` will fix this for you, as it was added to enable the `export *`/barrel export use case that you mention. Going to close for now/with that assumption.

**Comment by eladhaim** [comment]
it doesn't work, i have an example:

2 proto files:

bar.proto
`syntax = "proto3";

package com.services;

service Bar {
    rpc Service (BarRequest) returns (BarResponse) {}
}

message BarRequest {
    string id = 1;
}

message BarResponse { 
    string id = 1;
}`

foo.proto
`syntax = "proto3";

package com.services;

service Foo {
    rpc Service (FooRequest) returns (FooResponse) {}
}

message FooRequest {
    string id = 1;
}

message FooResponse { 
    string id = 1;
}`

Output:

bar.ts
`/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { messageTypeRegistry } from "./typeRegistry";

export interface BarRequest {
  $type: "BarRequest";
  id: string;
}

export interface BarResponse {
  $type: "BarResponse";
  id: string;
}

export const COM_SERVICES_PACKAGE_NAME = "com.services";

export const BarRequest = { $type: "BarRequest" as const };

messageTypeRegistry.set(BarRequest.$type, BarRequest);

export const BarResponse = { $type: "BarResponse" as const };

messageTypeRegistry.set(BarResponse.$type, BarResponse);

export interface BarClient {
  service(request: BarRequest): Observable<BarResponse>;
}

export interface BarController {
  service(request: BarRequest): Promise<BarResponse> | Observable<BarResponse> | BarResponse;
}

export function BarControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["service"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("Bar", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("Bar", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const BAR_SERVICE_NAME = "Bar";
`

foo.ts
`
/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { messageTypeRegistry } from "./typeRegistry";

export interface FooRequest {
  $type: "com.services.FooRequest";
  id: string;
}

export interface FooResponse {
  $type: "com.services.FooResponse";
  id: string;
}

export const COM_SERVICES_PACKAGE_NAME = "com.services";

export const FooRequest = { $type: "com.services.FooRequest" as const };

messageTypeRegistry.set(FooRequest.$type, FooRequest);

export const FooResponse = { $type: "com.services.FooResponse" as const };

messageTypeRegistry.set(FooResponse.$type, FooResponse);

export interface FooClient {
  service(request: FooRequest): Observable<FooResponse>;
}

export interface FooController {
  service(request: FooRequest): Promise<FooResponse> | Observable<FooResponse> | FooResponse;
}

export function FooControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["service"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("Foo", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("Foo", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const FOO_SERVICE_NAME = "Foo";
`

has you see both of them exports the "COM_SERVICES_PACKAGE_NAME" which make it impossible import both of the files to the same index.ts
