### ISSUE TITLE
static fields list

### ISSUE THREAD

**Issue by sefaphlvn** [stephenh/ts-proto#912]
I need something. Is there a way to get all interface field names in the array?

Like this
`[“healthy_panic_threshold”, “zone_aware_lb_config”, “locality_weighted_lb_config” ...]`

I can do it myself but I need to create an object from the interface and then also create nested interfaces.

When I use the protobuf-es plugin it gives me these fields static. I’m extracting the list from these fields.

Is there a way to get this with the ts-proto plugin?
```
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "healthy_panic_threshold", kind: "message", T: Percent },
    { no: 2, name: "zone_aware_lb_config", kind: "message", T: Cluster_CommonLbConfig_ZoneAwareLbConfig, oneof: "locality_config_specifier" },
    { no: 3, name: "locality_weighted_lb_config", kind: "message", T: Cluster_CommonLbConfig_LocalityWeightedLbConfig, oneof: "locality_config_specifier" },
    { no: 4, name: "update_merge_window", kind: "message", T: Duration },
    { no: 5, name: "ignore_new_hosts_until_first_hc", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 6, name: "close_connections_on_host_set_change", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 7, name: "consistent_hashing_lb_config", kind: "message", T: Cluster_CommonLbConfig_ConsistentHashingLbConfig },
    { no: 8, name: "override_host_status", kind: "message", T: HealthStatusSet },
  ]);
```

**Comment by stephenh** [comment]
Hi @sefaphlvn , we don't have that capability today. We have `outputTypeRegistry`, which emits some metadata to enable looking up the messages themselves, but nothing about the fields within each message.

It makes sense that `protobuf-es` uses this approach, b/c their encode/decode library is much more metadata-driven that ts-protos, which uses the "old school" protobuf approach of just codegen-ing out all of the encode/decode methods.

If you'd like to submit a PR for this, that'd be great.

**Comment by sefaphlvn** [comment]
I'm sorry, I don't have enough experience for this. Maybe once I gain more experience
