### ISSUE TITLE
google.protobuf.Timestamp compiled localy

### ISSUE THREAD

**Issue by lexdevelop** [stephenh/ts-proto#918]
I'm having the problem with using google.protobuf.Timestamp. The problem is that protoc compiler with protoc-gen-ts_proto plugin compile imported google dependency in the output.
Here is my proto:
```
syntax = "proto3";

import "google/protobuf/timestamp.proto";

package bot.v1;

message Bot {
  ----some fields here ----
  optional google.protobuf.Timestamp created = 24;
  optional google.protobuf.Timestamp updated = 25;
}
```

Compile proto  command:
```
protoc --plugin=/usr/local/lib/node_modules/ts-proto/protoc-gen-ts_proto \
    --proto_path=proto/ \
    --ts_proto_out=/compile/nestjs \
    --ts_proto_opt=nestJs=true \
    --ts_proto_opt=addGrpcMetadata=true \
    --ts_proto_opt=addNestjsRestParameter=true \
    --ts_proto_opt=outputJsonMethods=true \
    --ts_proto_opt=outputEncodeMethods=true \
    --ts_proto_opt=unrecognizedEnum=false \
    --ts_proto_opt=exportCommonSymbols=false \
    --ts_proto_opt=forceLong=bigint \
    --ts_proto_opt=useDate=true \
    $(find ./proto -iname "*.proto")
```

What will happen is compiler will compile google package imported and output it with the rest of my protos.
Then we can see relative import from compiled google package
```
import { wrappers } from "protobufjs";
import * as _m0 from "protobufjs/minimal";
import { Timestamp } from "../../google/protobuf/timestamp";
import Long = require("long");

export interface Bot {
  created?: Date | undefined;
  updated?: Date | undefined;
}
```
Expected behavior is to not compile google dependency in output and not to use local import

**Comment by stephenh** [comment]
Hi @lexdevelop , you can try some of ts-proto's options like `emitImportedFiles` or mappings like `--ts_proto_opt=Mgoogle/protobuf/empty.proto=./google3/protobuf/empty`.

In general the protobuf system is very agnostic/fragmented on how protobuf "packages" map to each language's modules/dependencies/etc, that there is not a canonical, "most correct" approach for ts-proto to follow.

**Comment by lexdevelop** [comment]
Thanks you for explaining @stephenh.
