### ISSUE TITLE
TypeScript option `verbatimModuleSyntax` not supported

### ISSUE THREAD

**Issue by Zeswen** [stephenh/ts-proto#920]
TypeScript has an option [`verbatimModuleSyntax`](https://www.typescriptlang.org/tsconfig#verbatimModuleSyntax) to always import types using the `type` prefix.

`tsc` fails to pass the checks.
```ts
import {
  CallOptions, // 'CallOptions' is a type and must be imported using a type-only import when 'verbatimModuleSyntax' is enabled.ts(1484)
  ChannelCredentials,
  Client,
  ClientOptions, // 'ClientOptions' is a type and must be imported using a type-only import when 'verbatimModuleSyntax' is enabled.ts(1484)
  ClientUnaryCall // 'ClientUnaryCall ' is a type and must be imported using a type-only import when 'verbatimModuleSyntax' is enabled.ts(1484)
  handleUnaryCall, // 'handleUnaryCall' is a type and must be imported using a type-only import when 'verbatimModuleSyntax' is enabled.ts(1484)
  makeGenericClientConstructor,
  Metadata,
  ServiceError, // 'ServiceError' is a type and must be imported using a type-only import when 'verbatimModuleSyntax' is enabled.ts(1484)
  UntypedServiceImplementation, // 'UntypedServiceImplementation' is a type and must be imported using a type-only import when 'verbatimModuleSyntax' is enabled.ts(1484)
} from "@grpc/grpc-js";
```

Including the `type` prefix to the previous variables will fix the issue.

**Comment by stephenh** [comment]
Hi @Zeswen , the codegen library that we use, ts-poet, has support for type imports by just adding a `t:` prefix, so changing like `imp("CallOptions@@grpc/grpc-js")` to `imp("t:CallOptions@@grpc/grpc-js")`.

(The double `@@` are weird, but the ts-poet import syntax came from awhile ago, before using `@` as an org prefix was popular :shrug: )

But, anyway, this should be a pretty easy fix; if you'd like to work on a PR that just adds `t:` to the various `imp`s you want changed, that'd be great. Thanks!

**Comment by Zeswen** [comment]
Thanks @stephenh for the insightful explanation! I've created #921 to address this 🙂

Amazing work on both `ts-poet` and `ts-proto` ❤️
