### ISSUE TITLE
What is a modern protoc?

### ISSUE THREAD

**Issue by ws-gregm** [stephenh/ts-proto#922]
as per README...

```
Ensure you're using a modern protoc, i.e. the original protoc 3.0.0 doesn't support the _opt flag
```

What's a modern protoc? yarn add protoc@latest installs protoc@1.x.x

**Comment by stephenh** [comment]
Ah yeah, you'll need to install `protoc` by whatever their installation instructions are your platform.

https://protobuf.dev/downloads/

Modern means a protoc that is a recent-ish 3.x (like any 3.x released in the last year or more), I'm not sure which version exactly.

**Comment by stephenh** [comment]
Yeah, no idea where the `23.x` comes from, that might be grpc's version number :shrug: .

> questions about `useDate`

Ah yeah, thanks for asking. I'd prefer not to have issues files for questions, so you can use the Discussions tab, but fwiw I don't have a ton of free time for user support/Q&A.

ts-proto is more of a self-serve project for power users to setup their company's bespoke/internal protobuf stack, and not an out-of-the-box framework with tutorials/onboarding flows/etc.
