### ISSUE TITLE
Use bigint literals instead of BigInt constructor.

### ISSUE THREAD

**Issue by bhollis** [stephenh/ts-proto#928]
Apologies if this has already been discussed, but looking at the output of ts-proto with `--ts_proto_opt=forceLong=bigint`, it uses `BigInt("0")` instead of `0n`, which would be smaller output.

e.g. 

```
message.myId !== BigInt("0")
```

vs.

```
message.myId !== 0n
```

**Comment by jcready** [comment]
Just a guess: some older parsers cannot handle BigInt literals (e.g. Webpack 4's parser), but function calls work just fine :)

**Comment by bhollis** [comment]
That makes sense, though isn't that more the role of Babel to generate downlevel code for older runtimes?

**Comment by stephenh** [comment]
Hi @bhollis , @jcready , I did a quick test of using `0n` and looks like tsc requires a minimum runtime target in `tsconfig.json` to support it:

```
integration/map-bigint-optional/test.ts(127,17): error TS2737: BigInt literals are not available when targeting lower than ES2020.
```

So we could add a flag of like `bigIntLiterals=true/false`, maybe default it to true with the :crossed_fingers: that most users are on post-ES2020 targets.

I had started a PR to just do the find/replace:

https://github.com/stephenh/ts-proto/pull/932

But given it needs an option to avoid breaking pre-2020 runtimes, dunno, may not be worth it?

**Comment by bhollis** [comment]
Makes sense. I don't know how necessary it is, I'm just obsessed with bundle size. I can always write a Babel or Terser plugin to do the transformation.

**Comment by stephenh** [comment]
Cool; fwiw I'm going to close this out b/c I'm personally not going to work on it, but also if a PR showed up that built on #932 but moved the behavior behind a flag (or did `0n` by default, and would let users get the old behavior via a flag), so that pre-2020 runtimes would not break, that'd be great, and I'd definitely accept the PR. Thanks!
