### ISSUE TITLE
--ts_proto_out: protoc-gen-ts_proto: The system cannot find the file specified.

### ISSUE THREAD

**Issue by dayrim** [stephenh/ts-proto#93]
Hello i am having troubles running my script on windows.
This is the script:
```
SRC_DIR="./libs/proto-schema/src/proto/*.proto"
DEST_DIR="./libs/proto-schema/src/"

# node_modules/ts-proto/protoc-gen-ts_proto.cmd
protoc --plugin=protoc-gen-ts_proto=.\node_modules\.bin\protoc-gen-ts_proto.cmd --ts_proto_opt=outputEncodeMethods=true,useEnumNames=false,asClass=false,outputJsonMethods=true,context=true,outputNestJs=true,outputClientImpl=false --ts_proto_out=${DEST_DIR} ${SRC_DIR}
```
Relevant issues:
https://github.com/improbable-eng/ts-protoc-gen/issues/15
https://github.com/stephenh/ts-proto/issues/13

I tried changing the path to --plugin=protoc-gen-ts_proto=.\node_modules\.bin\protoc-gen-ts_proto.cmd and also with %CD%

**Comment by stephenh** [comment]
Does `$DEST_DIR` work on windows? It looks like you might be mixing unix script conventions (`SRC_DIR=...`) and windows conventions (`.cmd`).

Other than that, I don't think I can help much.

If you figure it out and find something that we should specifically highlight in our readme to help future windows users, let me know.

**Comment by PhilipMantrov** [comment]
`protoc --plugin=protoc-gen-ts_proto=%CD%/node_modules/.bin/protoc-gen-ts_proto.cmd --ts_proto_opt=outputClientImpl=grpc-web --ts_proto_out=#{dir} #{dir}\#{base} -I #{dir} #{base}`

%CD% -- resolve this issue
@stephenh add this in readme pls, its will help all windows users

**Comment by stephenh** [comment]
@PhilipMantrov what is the `#{dir}` syntax? Is that windows shell?

**Comment by PhilipMantrov** [comment]
> @PhilipMantrov what is the `#{dir}` syntax? Is that windows shell? powershell?

 `foreach -g \"src/definitions/proto/*f.proto\" -x \"protoc --plugin=protoc-gen-ts_proto=%CD%/node_modules/.bin/protoc-gen-ts_proto.cmd --ts_proto_opt=outputClientImpl=grpc-web --ts_proto_out=./src/definitions/generated #{dir}\\#{base} -I #{dir} #{base}\"`

foreach package (https://www.npmjs.com/package/foreach-cli) for listed all files in dir

**Comment by Icyfirefists** [comment]
Hi, please don't let this close. No matter what I do on windows the error at the top of the page is all that is printed. It seems to only happen with typescript plugins.

Please help.

**Comment by tofluid** [comment]
Found out how to get this to work
Originally i was running the command as it was specified on the main page:
```
protoc -I ./proto --plugin=protoc-gen-ts_proto=.\node_modules\.bin\protoc-gen-ts_proto.cmd --ts_proto_out=./proto ./proto/test.proto
```

I finally got it to work on Windows by adding an extra `\` when specifying the .cmd
```
protoc -I ./proto --plugin=protoc-gen-ts_proto=.\\node_modules\\.bin\\protoc-gen-ts_proto.cmd --ts_proto_out=./proto ./proto/test.proto
```

**Comment by bryding-su** [comment]
> Found out how to get this to work Originally i was running the command as it was specified on the main page:
> 
> ```
> protoc -I ./proto --plugin=protoc-gen-ts_proto=.\node_modules\.bin\protoc-gen-ts_proto.cmd --ts_proto_out=./proto ./proto/test.proto
> ```
> 
> I finally got it to work on Windows by adding an extra `\` when specifying the .cmd
> 
> ```
> protoc -I ./proto --plugin=protoc-gen-ts_proto=.\\node_modules\\.bin\\protoc-gen-ts_proto.cmd --ts_proto_out=./proto ./proto/test.proto
> ```

After many different attempts, this is the only thing that worked for me as well. I had to get rid of the -I arg though.

**Comment by stephenh** [comment]
@bryding-su  / @tofluid thanks for reporting what worked for you; I've linked to this issue from the home page so hopefully it's easier for Windows users to find what works for them.

**Comment by wdaz** [comment]
@tofluid thank you
