### ISSUE TITLE
Enhancement: `json_name` defined in a proto file should be able to be extracted.

### ISSUE THREAD

**Issue by Yo-mah-Ya** [stephenh/ts-proto#942]
I'm wondering if we could support to get only interface declaration with `json_name` defined in a proto file, in other words when `onlyTypes=true` are set, wanna get fields from `json_name` defined in a  proto file.
 
For example, I want the `json_name` named `Alias` shown below proto file. The first letter should be capitalized !
https://github.com/pganalyze/libpg_query/blob/009f19d7f867a699e1beab5fd545fbc07ad35647/protobuf/pg_query.proto#L19

But as long as I see the below part, it seems that only field name, possibly modified by maybeSnakeToCamel though, is supported.
https://github.com/stephenh/ts-proto/blob/12836027621c62dba976189ffd990cbed88838f2/src/main.ts#L877-L880

Ideally I'd like to get field name like shown below.
https://github.com/thesayyn/protoc-gen-ts/blob/a5c306a0d1d864ce5bc1887dfef078d76c0efcc0/src/descriptor.ts#L15-L20

**Comment by stephenh** [comment]
Fixed in #943 , thanks @Yo-mah-Ya !
