### ISSUE TITLE
Configurability of the unrecognized enum type

### ISSUE THREAD

**Issue by vecerek** [stephenh/ts-proto#944]
Hi there 👋 the current default behavior is that the transformer adds an `UNRECOGNIZED` key with the value of `-1`.
Is there a way to configure that an existing key of value X should be used as the unrecognized case?
For example, in our company, we have a standard that dictates always to specify an enum key of `UNKNOWN` or similar (e.g. `UNKNOWN_TYPE`) with the value `0`, i.e. it is always the value 0 that should be treated as the default case. I want to be able to configure that via an option like:

```
--ts_proto_opt=unrecognizedEnumFallback=0
```

**Comment by stephenh** [comment]
Hi @vecerek ; we don't have that option today, but if you'd like to submit a PR, that'd be great! Thanks!

**Comment by paralin** [comment]
My org does the same so this would actually be a very useful option for me as well.

**Comment by vecerek** [comment]
Implemented by [#946](https://github.com/stephenh/ts-proto/pull/946#issuecomment-1755608609) and released as part of `v1.161.0`.
