### ISSUE TITLE
Support for FieldOptions.JSType

### ISSUE THREAD

**Issue by beyers-luno** [stephenh/ts-proto#958]
Reference: https://protobuf.dev/reference/java/api-docs/com/google/protobuf/DescriptorProtos.FieldOptions.JSType

Hi!

In my proto file I have:
```
int64 foobar = 3 [jstype = JS_STRING];
```

In my generated ts file I get:
```
foobar: number;
```

Using the arguments:
```
--ts_proto_opt=onlyTypes=true
```

It should be this?
```
foobar: string;
```

Is there a configuration setting I am missing?

**Comment by beyers-luno** [comment]
The closest configuration setting I can find is `forceLong=string`, which isn't exactly the same thing.

**Comment by stephenh** [comment]
Hi @beyers-luno , you're right, we don't currently support `jstype`--this is the first I'm seeing it.

Happy to have you work on a PR if you'd like to add support for it, although I'm a little worried it might be complicated, like I'm not sure the matrix of "proto type <-> different jstype". I assume that's documented somewhere, but just might be tedious to handle all of the cases.

Would be great if you want to take a look though; thanks!

**Comment by dasco144** [comment]
I'd be willing to take a stab at this

**Comment by stephenh** [comment]
@dasco144 sounds good!

I think the `toTypeName` in `types.ts` is probably the best slice-point to say "this field should _actually_ be type xyz".

Unfortunately that's just the type, and the encoding/decoding of that type is probably scattered around the encode/decode/toJSON/fromJSON methods. Like `getEncodeWriteSnippet` and `getDecodeReadSnippet`.

**Comment by dasco144** [comment]
@stephenh I've got an MR ready for review 🙏
