### ISSUE TITLE
Mistake in nestjs doc: `HeroesService` should be `HeroServiceClient`?

### ISSUE THREAD

**Issue by yeongjet** [stephenh/ts-proto#971]
https://github.com/stephenh/ts-proto/blob/f51b3368b682effd8ec044b94bb9621aa20beea1/NESTJS.markdown?plain=1#L96C63-L96C63

but there is no `HeroesService` in generated file, should I use `HeroServiceClient`?  This doc also note:

> The controller interface name would be HeroServiceController. The client interface name would be HeroServiceClient.

**Comment by stephenh** [comment]
Hi @yeongjet , yep, you're right; I've fixed the example, thanks!
