### ISSUE TITLE
Allow NestJS to leverage Generic definitions

### ISSUE THREAD

**Issue by shohoney** [stephenh/ts-proto#972]
More a question than anything.  Is it possible to have `nestJs=true` not ignore the `outputServices` parameter?  Or, is there a specific option that will give me the portion of `genericDefinitions` that has the "definition" which looks like 
```typescript
export type SomeServieDefinition = typeof SomeServiceDefintion;

export const SomeServicesDefintition = {
  name: 'SomeService',
  fullName: '....',
  methods: {
    ....
  }
}
``` 

We have a utility that we wrote that takes the output encoders/decoders and uses the definition above to adjust the output definitions from `proto-loader` so that Nest is able to leverage the encoders and decoders from `ts-proto`.  I've tinkered with a lot of the options and I wasn't able get my desired result.  I was able to determine that the output I want comes from the `genericDefintions` option, however.

**Comment by stephenh** [comment]
Hi @shohoney ; apologies for the really late reply, I missed your message in my ~every week or so triage of ts-proto issues...

Setting `nestJs=true` does it really skip the other options doesn't it...

Yeah, that seems like an easy fix. Are you still looking for this change to be made?

Fwiw I think the NestJS / proto-loader glue you've written would probably be very useful to others that are working on NestJS as well, is that something you could share/potentially contribute?

Thanks!
