### ISSUE TITLE
Why every message is genereated as optional

### ISSUE THREAD

**Issue by ArielGueta** [stephenh/ts-proto#976]
I have the following message for example:

```
message Foo {
  string one = 1;
}

message Bar {
  Foo foo = 1
}
```

And foo is output as:

```ts
foo: Foo | undefined;
```

How can I remove the `| undefined`. I know it will never be `undefined`.

**Comment by stephenh** [comment]
Hi @ArielGueta , this is just a fundamental aspect of protobuf, and comes from Google's assertion that this behavior is the best for long-term maintenance of schemes.

I personally don't agree, i.e. I like the ability in GraphQL schemes to say "the book.author field is required", but :shrug: , this is just how protobuf works. Sorry!

**Comment by ArielGueta** [comment]
Thanks @stephenh !
