### ISSUE TITLE
Error message type naming collision

### ISSUE THREAD

**Issue by bgentry** [stephenh/ts-proto#987]
Hello, similar to #927, I'm running into an issue because we have a type named `Error` which gets imported in generated structs, causing a collision with `throw new Error(...)` calls in the code. The typescript errors appear to go away if I prefix these like `throw new globalThis.Error(...)`.

Looks like this is one more global type which needs such a prefix added throughout?

**Comment by stephenh** [comment]
Yeah, we're probably just missing the prefix; can you paste ~5-10 lines of code that show the `throw new Error` that's missing the `globalThis`?

**Comment by bgentry** [comment]
Sure thing! Here's a sample of what gets generated for `google/protobuf/wrappers`:

```ts
export const Int64Value = {
  encode(message: Int64Value, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.value !== BigInt("0")) {
      if (BigInt.asIntN(64, message.value) !== message.value) {
        throw new Error("value provided for field message.value of type int64 too large");
      }
      writer.uint32(8).int64(message.value.toString());
    }
    return writer;
  },
```

And here is a sample of the `Error` proto def:

```proto
syntax = "proto3";

package myapp.common.v1;

import "google/protobuf/struct.proto";

message Error {
  string code = 1;
  string message = 2;
  google.protobuf.Struct extra = 3;
}
```

This simple diff:

```diff
       if (BigInt.asUintN(64, message.positiveIntValue) !== message.positiveIntValue) {
-        throw new Error("value provided for field message.positiveIntValue of type uint64 too large");
+        throw new globalThis.Error("value provided for field message.positiveIntValue of type uint64 too large");
       }
```

Is enough to get rid of `tsc` errors on these lines.

**Comment by bgentry** [comment]
Thank you so much for the quick fix @stephenh! :pray: I'll give this a try on Monday and report back if there are any issues.

**Comment by bgentry** [comment]
Works great, thank you again @stephenh 🎉
