### ISSUE TITLE
Should deprecated fields be optional? 

### ISSUE THREAD

**Issue by husseinhere** [stephenh/ts-proto#993]
Given the message:

```
message Amount {
  Currency currency = 1;
  int64    old_value = 2 [deprecated = true];
  double   value = 3;
}
```

ts-proto generates:
```
export interface Amount {
    currency: Currency;
    /** @deprecated */
    oldValue: number;
    value: number;
}
```

But wouldn't it be a lot nicer if `oldValue` was defined as  `oldValue?: number` ?

**Comment by stephenh** [comment]
That seems reasonable; if you want to try adding that check here, we could see what happens:

https://github.com/stephenh/ts-proto/blob/main/src/types.ts#L356

**Comment by stephenh** [comment]
Closing this out thanks to #1010, thank you @tufandevrim !
