### ISSUE TITLE
How to use with node js

### ISSUE THREAD

**Issue by ArielGueta** [stephenh/ts-proto#994]
Hi,

I have generated the following code using the library:

```ts
export class FooClientImpl  {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || Foo;
    this.rpc = rpc;
    this.foo = this.foo.bind(this);
  }
  foo(request: FooRequest): Promise<FooResponse> {
    const data = FooRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "FooService", data);
    return promise.then((data) =>
      Foo.decode(_m0.Reader.create(data))
    );
  }
}

interface Rpc {
  request(
    service: string,
    method: string,
    data: Uint8Array
  ): Promise<Uint8Array>;
}
```

But it's unclear which rpc I need to pass now in order to use it in node js?

```ts
new FooClientImpl(??)
```

Thanks.

**Comment by stephenh** [comment]
Hi @ArielGueta sorry for the late reply, you've probably figured this out or moved on, but ts-proto can be used with a variety of frameworks; there is a grpc-js example here:

https://github.com/stephenh/ts-proto/blob/main/integration/grpc-js/parameters.txt

And there's also:

https://github.com/deeplay-io/nice-grpc

Which sits on top of ts-proto.

I agree the readme could use some work. :-/ 

Thanks!
