### ISSUE TITLE
Oneof objects do not follow generated interface.

### ISSUE THREAD

**Issue by Brammm** [stephenh/ts-proto#998]
I inherited a project that uses ts-proto and @grpc/proto-loader. The protos contain a bunch of oneof fields. Up until now these were modeled "flatly", as the docs say, as is the default. I added the `oneof=unions` option and this generates the interfaces as document, however, these do not match the actual objects that I'm receiving in my code.

A message like
```proto
message DownloadResponse {
    oneof response {
        DownloadSuccessResponse success = 1;
        DownloadFailureResponse failure = 2;
    }
}
```
in the code actually looks like the following type:
```ts
type DownloadResponse = 
  | {
    response: "success";
    success: DownloadSuccessResponse;
  }
  | {
    response: "failure";
    failure: DownloadFailureResponse;
  }
```
Is this some kind of setting I'm missing?

**Comment by stephenh** [comment]
Hi @Brammm , I think this is a dup of #314.

I'm pretty sure the last comment there shows a viable work around, but no one has reworked it into a PR to update the support in ts-proto itself.

Would be great if you want to take a crack at it! Thanks!
